### ISSUE TITLE
Question: Custom button today/now

### ISSUE THREAD

**Issue by fabiopaiva-innovactory** [mmazzarolo/react-native-modal-datetime-picker#100]
Is that possible to add a custom button to select the current date and/or time?

**Comment by mmazzarolo** [comment]
Yep, there are many different props you can use to customize it:

Name | Type | Default | Description
-- | -- | -- | --
cancelTextIOS | string | 'Cancel' | The text on the cancel button on iOS
cancelTextStyle | style |   | The style of the cancel button text on iOS
confirmTextIOS | string | 'Confirm' | The text on the confirm button on iOS
confirmTextStyle | style |   | The style of the confirm button text on iOS
customCancelButtonIOS | node |   | A custom component for the cancel button on iOS
customConfirmButtonIOS | node |   | A custom component for the confirm button on iOS
customTitleContainerIOS | node |   | A custom component for the title container on iOS
datePickerContainerStyleIOS | style |   | The style of the container on iOS
