### ISSUE TITLE
how show month in chinese ？

### ISSUE THREAD

**Issue by ZhouXiongXiong** [mmazzarolo/react-native-modal-datetime-picker#101]
I  want show month in chinese ! please tell func to change it

**Comment by mmazzarolo** [comment]
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
Before reporting a bug, try swapping `react-native-datetime-picker` with react-native original date/time pickers and, if the issue persists, check if it has already been reported as a [react-native issue](https://github.com/facebook/react-native/issues).

**Comment by mmazzarolo** [comment]
Language related issues: #31 #83
