### ISSUE TITLE
When you update the date propriety, onConfirm is not called again

### ISSUE THREAD

**Issue by gabrielvcbessa** [mmazzarolo/react-native-modal-datetime-picker#102]
onConfirm is the only method that can notify the parent component that an update has happened. When passing a new date to the date picker component, the component updates the date internally but doesn't call onConfirm method.

**Comment by mmazzarolo** [comment]
Hi @gabrielvcbessa,
>  When passing a new date to the date picker component

Since you're the one passing the new date to the component, you already are aware of the date your passing... there's no reason to call onConfirm here. Am I missing something?

**Comment by gabrielvcbessa** [comment]
Sorry, there isn't any issue, I was just tired and made a confusion. Closing this issue.
