### ISSUE TITLE
min and max time does not work

### ISSUE THREAD

**Issue by niteshsingh0129** [mmazzarolo/react-native-modal-datetime-picker#103]
### When reporting a bug, please be sure to check if the issue still persists with react-native original date/time pickers:
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
Before reporting a bug, try swapping `react-native-datetime-picker` with react-native original date/time pickers to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [ ] The outcome of the `react-native-modal-datetime-picker` swap described above
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `react-native-modal-datetime-picker` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior

### When you open an issue for a feature request, please add as much detail as possible:
- [x] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

**Comment by niteshsingh0129** [comment]
min and max time validation is used in most of the apps  as min and max date props

**Comment by mmazzarolo** [comment]
Hey @niteshsingh0129, please follow the issue template first (try the native components and provide some code with the expected results). 
I can't understand the description of the issue, I'm issue.

**Comment by niteshsingh0129** [comment]
it's not the issue,it's a feature just like you provide props of minimumDate and maximumDate. there should also props of minimumTime and maximumTime

**Comment by mmazzarolo** [comment]
Oh! Just set the time in either ‘minimumDate’ or ‘maximumDate’

**Comment by niteshsingh0129** [comment]
As you said ,pass the minimum time in minimumDate props but, it does not reflect on the time picker as passing the minimum date in minimumDate props reflect in the date picker . how to fix it please, clarify it

**Comment by mmazzarolo** [comment]
Try using [iOS Datepicker](https://facebook.github.io/react-native/docs/datepickerios.html) and let me know if it works here.

**Comment by rahmanmarija** [comment]
How is this closed? What about Android?

**Comment by FadiAboMsalam** [comment]
@mmazzarolo we need this feature for android in my opinion this feature has high importance!
any solution for max/min time limit to work both on ios and android ?
or workaround i need this!

**Comment by DaniSido** [comment]
> How is this closed? What about Android?

the minumDate work on iOS but not on Android

**Comment by sidnetopia** [comment]
Any update on this? I wanted to also implement min max time on a single day e.g.

July 10, 2022 I can only chose between 8:00 am to 6 pm

**Comment by nassimmiled** [comment]
any update about this one
