### ISSUE TITLE
DatePickerModeAndroid

### ISSUE THREAD

**Issue by johngoren** [mmazzarolo/react-native-modal-datetime-picker#105]
This might be a bad question, but do you know any way to get the old-fashioned TimePickerDialog instead of the clock wheel? 

I thought maybe the DatePickerModeAndroid="spinner" option might switch back to the old kind. But I can't get it to change anything. And I realize that the name strictly refers to "date" rather than "time" so I might be barking up the wrong tree. But as a feature request, I wonder if there's any way the module might be able to summon one of these:

![image](https://user-images.githubusercontent.com/748214/32003558-5bced7b4-b997-11e7-9221-94fa24b0a5ce.png)

**Comment by mmazzarolo** [comment]
Hey @johngoren, unfortunately I don't know any way to use the old Android ICS TimePickerDialog on newer versions of Android and creating a JS version of it is out of the scope of this component, sorry 😞

**Comment by mmazzarolo** [comment]
@henninghall congrats on the picker, it looks really cool! 👏

**Comment by Asmatchd** [comment]
Instead of `DatePickerModeAndroid= 'spinner'` use `timePickerModeAndroid= 'spinner'` worked for me.

**Comment by Asmatchd** [comment]
@mmazzarolo  please add ` timePickerModeAndroid= 'spinner' ` in your documentation old-fashioned TimePickerDialog.

**Comment by Asmatchd** [comment]
@johngoren  Instead of ` datePickerModeAndroid= 'spinner' `use 
` timePickerModeAndroid= 'spinner' ` worked for me.

**Comment by SudoPlz** [comment]
The latest values are `display="spinner` in case anyone is viewing that on >2021
