### ISSUE TITLE
How to change the default theme color

### ISSUE THREAD

**Issue by ugendrang** [mmazzarolo/react-native-modal-datetime-picker#106]
Currently the datetime picker displays title background, date/time selection color and Footer text(Cancel, Ok) color with green color. 

Is it possible to change the default theme color?

**Comment by mmazzarolo** [comment]
Hey @ugendrang , please take a look at #29

**Comment by ugendrang** [comment]
Thank you @mmazzarolo, its working after below changes in 'styles.xml'

<resources>

    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        **<item name="android:datePickerDialogTheme">@style/Dialog.Theme</item>
        <item name="android:timePickerDialogTheme">@style/Dialog.Theme</item>**
    </style>

    <style name="Dialog.Theme" parent="Theme.AppCompat.Light.Dialog">
  	    <item name="colorAccent">#FF0000</item>
  	    <item name="android:textColorPrimary">#0000FF</item>
   	</style>

</resources>

**Comment by SirPhemmiey** [comment]
@ugendrang you missed an opening tag over there. :-)

**Comment by JayKurniawan** [comment]
@ugendrang where can I find the `styles.xml` ?

**Comment by madeeha96** [comment]
It's always showing blue theme. How ever i use "#FFA500" i.e. orange
how can i use this color?

**Comment by blurxs** [comment]
@ugendrang Thank you it works for API 21+. However when I'm changing the color with your solution I get another picker on API 19. Do you know how I can change it there too? 
[API 19](https://ibb.co/jCmpzz)
[API 23](https://ibb.co/cEKWCK)

**Comment by ChenhuaWANG22** [comment]
@mmazzarolo Is it possible to change color with using Expo ? Or we have to eject the project in order to change the color ?

I have read issue #29, issue #106 and some other related thread, edit all styles.xml file in my project folder and even create a android directory tree with styles.xml in it.  
After hours trying, I'm still stuck with the color problem.
So please shed some light on this.

**Comment by mmazzarolo** [comment]
I don't think it's available in Expo yet: https://github.com/expo/expo/issues/313

**Comment by paolospag** [comment]
Hi @mmazzarolo 
this code:

```
<style name="Dialog.Theme" parent="Theme.AppCompat.Light.Dialog">
    <item name="colorAccent">#FF0000</item>
    <item name="android:textColorPrimary">#0000FF</item>
</style>
```

doesn't work for me with `react-native 0.58.6` and `react-native-modal-datetime-picker 6.1.0`.
Any workaround?

**Comment by mmazzarolo** [comment]
@paolospag no idea honestly, have you already tried checking in the React-Native issues? 🤔

**Comment by paolospag** [comment]
ciao @mmazzarolo 😄 
sorry for the late response.

This code:
```xml
<style name="SpinnerDatePickerDialog" parent="android:Theme.Material.Light.Dialog">
    <item name="android:datePickerStyle">@style/MyDatePicker</item>
    <item name="android:colorAccent">@color/colorPrimary</item>
    <item name="android:colorControlNormal">@color/colorPrimary</item>
</style>

<style name="MyDatePicker" parent="android:Widget.Material.DatePicker">
    <item name="android:datePickerMode">spinner</item>
</style>
```

has definitely solved my problem, thank you so much!

**Comment by spidi123q** [comment]
Its not working for me! any other ways

**Comment by ivgraai** [comment]
@ChenhuaWANG22 Try to change [primarycolor](https://docs.expo.io/versions/latest/config/app/#primarycolor) in Expo.

**Comment by animeclover** [comment]
I try the below blog for adding datePickerAndroid and it's working fine also provide when a user has multiple input field for date solution.

https://infinitbility.com/how-to-add-datepickerandroid-in-react-native-with-color-changes

**Comment by nigranac** [comment]
> Thank you @mmazzarolo, its working after below changes in 'styles.xml'
> 
> ```
> 
> <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
>     
>     item name="android:datePickerDialogTheme">@style/Dialog.Theme</item>
>     <item name="android:timePickerDialogTheme">@style/Dialog.Theme</item>
> </style>
> 
> <style name="Dialog.Theme" parent="Theme.AppCompat.Light.Dialog">
>     <item name="colorAccent">#FF0000</item>
>     <item name="android:textColorPrimary">#0000FF</item>
> </style>
> ```
where can I find the styles.xml @mmazzarolo @ugendrang

**Comment by rakesh-201** [comment]
Is there any way to change the theme of date picker in an expo managed react native app ?

**Comment by muheet9** [comment]
> @ugendrang where can I find the `styles.xml` ?

You can find the styles.xml file inside your android/app/src/main/res/values

**Comment by olarcher** [comment]
@rakesh-201 This is now possible with Expo config plugins, see https://stackoverflow.com/q/77703362/4350421
