### ISSUE TITLE
How to select a date, the choice of pop up box, only the year and month?

### ISSUE THREAD

**Issue by springHyc** [mmazzarolo/react-native-modal-datetime-picker#109]
我把`dateFormat`属性设置为了`dateFormat={"YYYY-MM"}`,选择好的数据中只展示，年和月，但是弹出的选择框中还是有日的。

<img width="344" alt="bug" src="https://user-images.githubusercontent.com/18530084/33008498-480d83fc-ce0e-11e7-95b4-dc01a7fc122c.png">

**Comment by mmazzarolo** [comment]
I'm sorry but i cannot understand what you're trying to tell.  
Please [follow the template](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/ISSUE_TEMPLATE.md) and try to write in english if possibile.
