### ISSUE TITLE
How to get time from time object

### ISSUE THREAD

**Issue by meurling** [mmazzarolo/react-native-modal-datetime-picker#112]
Hello!
Currently I am using the datetime picker with `mode={"time"}`. My `onConfirm` looks like this: `onConfirm={(time) => setDateTime(time)}`. Right now the `time` object looks like this: `Sun Nov 26 2017 15:47:00 GMT+0100 (CET)`. My question is; how do I get the time from this object? And also, can I get it in the format: (hh:mm)? Thanks!

**Comment by mmazzarolo** [comment]
That's not exactly a question related to the date picker, however you can manipulate the date with the functions showed [on the left panel of the MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC).  
Also, [here is a related question on stackoverflow](https://stackoverflow.com/questions/15546292/extract-time-from-datetime-using-javascript).  
Have fun! 👍
