### ISSUE TITLE
moment(date) not supporting in android

### ISSUE THREAD

**Issue by loyoliteabid** [mmazzarolo/react-native-modal-datetime-picker#117]
when using moment(date) as default date for time mode it shows the below error

Warning: Failed prop type: Invalid prop `date` of type `Moment` supplied to `CustomDatePickerAndroid`,
  expected instance of `Date`.

`<DateTimePicker
        mode='time'
        is24Hour={false}
        titleIOS='Start Time'
        isVisible={this.state.isTimePickerVisible}
        onConfirm={this._handleTimePicked.bind(this)}
        onCancel={this._hideTimePicker.bind(this)}
        date={
          this.state.startTime !== ''?
            this._combineTimeWithCurrDate(this.state.startTime) : null
        }
      />

_combineTimeWithCurrDate(time){
    if (time) {
      const currDate = new Date();
      const datePart = moment(currDate).format('L');
      const combineTimeWithCurrDate = moment(datePart +' '+ time);
      return combineTimeWithCurrDate;
    }
  }`

 it's pretty easy to work around by passing in Moment.toDate() instead, but it would be nice to be able to pass in the moment directly.

**Comment by mmazzarolo** [comment]
Hi!
For keeping the API as much compatible with the native date/time pickers we'll require a valid Date prop, sorry.
