### ISSUE TITLE
How  Can set Date and Time Same Screen Like iOS to Android

### ISSUE THREAD

**Issue by lavarajallu** [mmazzarolo/react-native-modal-datetime-picker#119]
Actually I am using this  Module , For time and Date . I set the  **mode={'datetime'}** this property Using this 

![screen shot 2017-12-18 at 4 28 00 pm](https://user-images.githubusercontent.com/20550556/34103169-c814feb8-e411-11e7-9f28-49d79138efbe.png)

Above Screen shot  like i want this android.

**Comment by mmazzarolo** [comment]
I'm sorry @lavarajallu but the aim of this package is showing a platform-dependent picker.

**Comment by lavarajallu** [comment]
is iT possible to solve this

**Comment by san1109** [comment]
did anyone manage to get above like date time picker ? @lavarajallu
