### ISSUE TITLE
Why It's not getting datePickerModeAndroid={'spinner'}

### ISSUE THREAD

**Issue by lavarajallu** [mmazzarolo/react-native-modal-datetime-picker#120]
Hello, I think this is not working Actually I getting Default android time Picker but i have Spinner mode i was change in node modules js page  and i was given to Property also but5 it's not getting like this below in android.

```
<DateTimePicker 
                             datePickerModeAndroid= 'spinner' 
                             isVisible={this.state.isTimePickerVisible} 
                             onConfirm={this._handleTimePicked} 
                             is24Hour={true}
                             onCancel={this._hideTimePicker}
                             mode='datetime' 
                             minimumDate={new Date()}
                              />
```

**I want like this!  any one suggest this** 
![screen shot 2017-12-18 at 5 54 41 pm](https://user-images.githubusercontent.com/20550556/34141124-595785d8-e4a5-11e7-9cb1-3877385cd9d4.png)

**Comment by mmazzarolo** [comment]
Please @lavarajallu if you need to submit an issue [follow the issue template](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/ISSUE_TEMPLATE.md), otherwise I won't be able to help/understand you.
