### ISSUE TITLE
App Crashing When I was the Update Date or time (iOS)

### ISSUE THREAD

**Issue by lavarajallu** [mmazzarolo/react-native-modal-datetime-picker#121]
When i was click on the picke select date multiple times and confirm clicking App crashes.I think it is SDk problem please check it once.
```
 <DateTimePicker
                             datePickerModeAndroid= {"spinner" }
                             isVisible={this.state.isTimePickerVisible}
                             onConfirm={this._handleTimePicked}
                             is24Hour={true}
                             onCancel={this._hideTimePicker}
                             mode={"datetime"}
                             minimumDate={new Date()}
                              />
```

**Comment by mmazzarolo** [comment]
Please @lavarajallu if you need to submit an issue [follow the issue template](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/ISSUE_TEMPLATE.md), otherwise I won't be able to help/understand you.
