### ISSUE TITLE
Deprecate `moment`

### ISSUE THREAD

**Issue by Andreyco** [mmazzarolo/react-native-modal-datetime-picker#125]
Looking at code, `moment` lib is used to extract hour of of the date.
Using `moment` brought several issues is past and is not necessary in this time.

If you, maintainers, are open for such change, I am willing to submit PR.

**Comment by mmazzarolo** [comment]
@Andreyco more than open to a new PR. Thanks!

**Comment by mmazzarolo** [comment]
Hey @Andreyco, any progress on this? 👍
