### ISSUE TITLE
Can't display on component mount

### ISSUE THREAD

**Issue by supercamilo** [mmazzarolo/react-native-modal-datetime-picker#126]
I would expect something like this to just display the picker every time my screen loads:

```
constructor(props) {
    super(props);

    this.state = {
        isVisible: true,
    };
}

render() {
    return (
        <DateTimePicker
             isVisible={this.state.isVisible}
             onConfirm={(date) => this.setDateTime(date)}
             onCancel={() => this.hideDatePicker()}
         />
     );
}
```

But it only seems to work when I change visibility via user interaction (on button press for instance):

```
constructor(props) {
    super(props);

    this.state = {
        isVisible: false,
    };
}

render() {
    return (
        <DateTimePicker
             isVisible={this.state.isVisible}
             onConfirm={(date) => this.setDateTime(date)}
             onCancel={() => this.hideDatePicker()}
         />
        <Button onPress={() => this.setState({ isVisible: true })}>
             <Text>Show Picker</Text>
        </Button>
    );
}
```

**Comment by mmazzarolo** [comment]
Android or iOS?
On Android it is a known thing, it could be fixed in [this file](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/CustomDatePickerAndroid/index.js) by copying the same logic done in the `componentDidUpdate` into the `componentDidMount` (if the `isVisible` prop is true).  
Willing to submit and test a PR? :)

**Comment by supercamilo** [comment]
Thanks @mmazzarolo, I just tested it on my Android project and it works. Here's the PR #127

**Comment by mmazzarolo** [comment]
Merged, thanks!
Do you need it asap?
Otherwise I'll wait for [this other PR](https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/125) before publishing on npm.  
Feel free to let me know if you need it soon, I can publish it tomorrow if needed :)

**Comment by supercamilo** [comment]
No hurry @mmazzarolo, I'm using my fork by now :)
