### ISSUE TITLE
Disabling weekends

### ISSUE THREAD

**Issue by rodrix** [mmazzarolo/react-native-modal-datetime-picker#129]
Hi everyone, how I can disable weekend's day selection (Saturday and Sunday)?

Thanks! :dancer:

**Comment by mmazzarolo** [comment]
Hey @rodrix! 
Do the original RN date pickers have this feature?  

Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).
Before reporting a bug, try swapping `react-native-datetime-picker` with react-native original date/time pickers and, if the issue persists, check if it has already been reported as a [react-native issue](https://github.com/facebook/react-native/issues).
