### ISSUE TITLE
state `userIsInteractingWithPicker` problem using `onDateChange` on iOS

### ISSUE THREAD

**Issue by fabiopaiva** [mmazzarolo/react-native-modal-datetime-picker#134]
If I add the method `onDateChange` to my component, the button onConfirm keep disabled even after the user stop interacting.
I noticed that the state is not updated because I did override the function `_handleDateChange` with my `onDateChange` prop.
I think it should update the state and also call my method onDateChange.
I don't want to use `neverDisableConfirmIOS` because I want to wait the user end the interaction.

**Comment by mmazzarolo** [comment]
Hey @fabiopaiva 
thanks for the feedback.  
Your proposal sounds good... maybe you could send a PR with it? 
Thanks!

**Comment by fabiopaiva** [comment]
Yes, working on that

**Comment by WesleyFaveri** [comment]
I got same problem and PR resolve this issue.

**Comment by mmazzarolo** [comment]
@fabiopaiva sorry for the late answer, could you resolve the conflict so that I can merge the PR?
