### ISSUE TITLE
iOS returning current date even my minimum date is something else

### ISSUE THREAD

**Issue by swaroopa94** [mmazzarolo/react-native-modal-datetime-picker#136]
Hi,

This module works great But had a small issue with it

In iOS when I set the minimum time to some April 16 and when I open the picker it is showing correctly
But If I don't scroll the picker and click on confirm then it is returning the current date.
In Android its working fine

Can anyone help me in solving this
Thank you

**Comment by mmazzarolo** [comment]
Could you provide an example?
