### ISSUE TITLE
[Question]: How to set different date/times to the picker each time I show it?

### ISSUE THREAD

**Issue by kalanaw** [mmazzarolo/react-native-modal-datetime-picker#14]
I'm reusing the picker for multiple fields in my screen. I want to set different default times for the picker each time i show it. Setting the 'date' prop doesn't seems to help as the picker always shows user's last selection. Any thoughts?

**Comment by mmazzarolo** [comment]
Hey!  
I proposed a solution to a similar problem in #7: it should work for you too, let me know :)

**Comment by mmazzarolo** [comment]
Closing, feel free to re-open if needed.
