### ISSUE TITLE
Disable DatePicker 

### ISSUE THREAD

**Issue by rubinim1995** [mmazzarolo/react-native-modal-datetime-picker#140]
i want to disable disable date picker and enable TimePicker only......

will this possible??

how can i achieve this??

**Comment by mmazzarolo** [comment]
It's in the FAQs:

### How can I show the timepicker instead of the datepicker?
Just set the `mode` prop to `time`.
You can also display both the datepicker and the timepicker in one step by setting the `mode` prop to `datetime`.

**Comment by rubinim1995** [comment]
its worked...
thank you so much
