### ISSUE TITLE
Data/Time Picker don't work on release - Works with react-native original date/time picker

### ISSUE THREAD

**Issue by ozmaat** [mmazzarolo/react-native-modal-datetime-picker#141]
Hi,

The date time box opens on android simulator but it is not shown on device in release version. No error is thrown but nothing displayed. 

I tested it on two devices with android versions 4.4 and 5.1.

It is also tested on android simulator with android 4.4 and it works on simulator without any issues.

It is tested with "TimePickerAndroid" original date/time picker, and it works and opens the old date/time picker on android 4.4 device.

Module version is 4.13.0.

react-native version is 0.52.0

**Comment by mmazzarolo** [comment]
Hi @ozmaat 

> It is also tested on android simulator with android 4.4 and it works on simulator without any issues.  

You mean that on simulator it works in release mode? 

> It is tested with "TimePickerAndroid" original date/time picker, and it works and opens the old date/time picker on android 4.4 device.  

Thanks for testing it with it too!

Which devices did you use?

**Comment by ozmaat** [comment]
Thanks @mmazzarolo for quick response. 

On simulator, it is tested in debug mode running react-native run-android. 

Devices are Asus Zenfone and Lenovo

**Comment by mmazzarolo** [comment]
Could you try the simulator in release mode to see if the issue persists? thanks

**Comment by ozmaat** [comment]
Release mode doesn't work on simulator also. 

RN date/time picker works on both debug and release mode on simulator.

**Comment by mmazzarolo** [comment]
That's really weird 🤔 I'll try to take a look at it, thank you for opening the issue

**Comment by mmazzarolo** [comment]
@ozmaat Could you give it a try with the example you can find in the `example` directory of this project? It is working fine for me in both dev and release mode.

**Comment by ozmaat** [comment]
thanks @mmazzarolo. I will give it a try and give feedback.

**Comment by ozmaat** [comment]
The sample project does work on release mode.  The code is very simple and I have tried several release builds to find out why it doesn't work but yet to find the reason. Maybe one of the modules interfering but not sure. I will report back here if I find what causes it not to function in every case.
