### ISSUE TITLE
Getting date value after custom confirm button

### ISSUE THREAD

**Issue by temitope** [mmazzarolo/react-native-modal-datetime-picker#15]
First, thanks for the great module.

I am trying to use the custom confirm button option so I create a Button like so
```
<customConfirmButtonIOS={<Button
              title="Confirm"
              onPress={this._handleTimePicked}
              />}
```

the problem is that the onPress function doesn't seem to receive the selected date value in the same way that the built-in confirm button passes it along. I tried setting  ref for the DateTimePicker to simply grab it from the function but I not sure what the path to its value is from the ref....any insight is appreciated.

**Comment by mmazzarolo** [comment]
Hey @temitope,
ad you can see [here](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/CustomDatePickerIOS/index.js#L70) I'm already wrapping your custom button with a `TouchableOpacity`.  
This means that you should remove your `onPress` prop from your component and simply use the `onConfirm` prop just like you'll do wit the build-in confirm button.  
Let me know if it fixes your issue :)

**Comment by temitope** [comment]
ahh yes, that makes sense. but im still not getting the desired behavior. It may be because I am using the Button component from the  [https://github.com/react-native-community/react-native-elements](react-native-elements module? [ https://github.com/react-native-community/react-native-elements) ]

I am getting a debug message of 

> please attach method to this component

from line 12 in the Button.js of that module...hmm i shouldnt need it to be their button, i will try the native buttons not in the module as well.

**Comment by mmazzarolo** [comment]
First of all: yes, that log line is indeed caused by the button you're using.  
Honestly I didn't understand you question regarding `customCancelButton` 🤔 ...  
  
Basically both `customCancelButtonIOS` and `customConfirmButtonIOS` are simple views that you can pass to `react-native-datetime-picker` and they will trigger `onCancel`/ `onConfirm` when pressed.  
The button press interactions are handled internally by `react-native-datetime-picker` and you should not pass a button with an already defined `onPress` (like you were doing).   
Try to pass a simple styled `<View />` to `customConfirmButtonIOS`: you'll see that it will trigger `onConfirm` when pressed :)  
  
I'm going to sleep now, if you have any more question I'll answer tomorrow!

**Comment by temitope** [comment]
Boom! Passing in a simple View with some text did the job. Thanks for the help there. 

this is maybe moot now, but to give more clarity regarding the `customCancelButton`, i was saying that I was able to actually pass an event to the onPress handler using that react-native-element button and have everything worked just fine, but doing the same with the confirmation button didnt work so i didnt suspect that the type of element i was passing in was the issue, since it worked for one and not the other.

**Comment by mmazzarolo** [comment]
Glad it worked.  
>  but doing the same with the confirmation button didnt work  
Probably because the cancel button doesn't return any parameter (so you can handle it even without the `onCancel`), while the confirm button returns the time (that is handled by `onConfirm`).

**Comment by mahamIqbal825** [comment]
Hi there,
this solution is not working for me i am giving the simple view but it's not triggering to the onConfirm function automatically
  <DateTimePickerModal
          isVisible={isDatePickerVisible}
          mode="date"
          dateFormat="dayofweek day month"
          onConfirm={date => {
            handleConfirmShedule(date);
          }}
          onCancel={hideDatePicker}
          textColor={Theme.primaryColor}
          style={styles.datePicker}
          confirmTextIOS="Done"
          customConfirmButtonIOS={() => {
            return (
              <View
                style={{
                  justifyContent: 'center',
                  alignItems: 'center',
                  marginBottom: 10,
                  height: 50,
                  width: '100%',
                  backgroundColor: 'red',
                }}
               ></View>
            );
          }}

          //backdropStyleIOS={{backgroundColor: 'transparent'}}
        />
