### ISSUE TITLE
Wrong time.

### ISSUE THREAD

**Issue by MihaiSandor** [mmazzarolo/react-native-modal-datetime-picker#151]
The outcome of the react-native-modal-datetime-picker swap described above - react-native-datetime-picker (latest)
iOS 11.3 (Iphone X simulator)
What version of react-native-modal-datetime-picker? - latest
What packages or other dependencies you're using? - just react-native-modal-datetime-picker and React Native.
An isolated way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem) - I don't know.
The behavior you expect to see, and the actual behavior? See below
![screen shot 2018-04-02 at 13 49 37](https://user-images.githubusercontent.com/13609095/38193860-f144344e-367c-11e8-83d8-60577861c160.png)
I chose the current time and it came back 3 hours ago.

1:58 current time
10:58 returned

**Comment by mmazzarolo** [comment]
### When reporting a bug, please be sure to check if the issue still persists with react-native original date/time pickers:
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
Before reporting a bug, try swapping `react-native-datetime-picker` with react-native original date/time pickers to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [ ] The outcome of the `react-native-modal-datetime-picker` swap described above
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `react-native-modal-datetime-picker` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior

**Comment by suhabaobaid** [comment]
+1

**Comment by mmazzarolo** [comment]
Hey everyone, could you please read and fill the issue template? 
Thanks

**Comment by MihaiSandor** [comment]
Yes

**Comment by mmazzarolo** [comment]
### When reporting a bug, please be sure to include the following:
- [ ] The outcome of the `react-native-modal-datetime-picker` swap described above
- [x] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [x] What version of `react-native-modal-datetime-picker` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [x] What packages or other dependencies you're using
- [x] The behavior you expect to see, and the actual behavior

**Comment by julestruong** [comment]
Hello

Just adding thoughts, it happens to bug only on device, not on simulator.
This also appears to happen randomly, roughly one in two

**Comment by julestruong** [comment]
Hello @mmazzarolo no its not.

It seems to be related to https://github.com/facebook/react-native/issues/8169. 
So you might not be able to fix this on your library :(

**Comment by mmazzarolo** [comment]
Oh, yeah, the good old issue 8169 😄 
Take a look at this discussion, #115, they seems to have find a way to fix it with a custom picker component
