### ISSUE TITLE
Hiding AM / PM on iOS

### ISSUE THREAD

**Issue by RocKhalil** [mmazzarolo/react-native-modal-datetime-picker#154]
Just a tip, if you want to use the 24 Hours rule on both iOS and Android and see that the `is24Hour` is not working on iOS, then you'll need to force the app to use `en_GB` as default DatePicker locale.

To do so, edit your `AppDelegate.m` file, and add `[[UIDatePicker appearance] setLocale:[[NSLocale alloc]initWithLocaleIdentifier:@"en_GB"]];` to `application didFinishLaunchingWithOptions`

Based on [this comment](https://github.com/xgfe/react-native-datepicker/issues/71#issuecomment-342747019).

**Comment by abarisic86** [comment]
This is useful. I had a situation where time picker would show AM/PM option without actually setting is24Hours to false but when tested on a device it would show 24-hours-time picker.

**Comment by mmazzarolo** [comment]
Hey @RocKhalil thanks a lot 👍 !
Could you send a PR for adding that info in the FAQs question of the README?

**Comment by RocKhalil** [comment]
Created a PR for it [156](https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/156)
