### ISSUE TITLE
minuteInterval always resetting to 1

### ISSUE THREAD

**Issue by zxiest** [mmazzarolo/react-native-modal-datetime-picker#158]
[https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/CustomDatePickerIOS/index.js](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/CustomDatePickerIOS/index.js
)
`Line 52`

should be set to `this.props.minuteInterval` ; no?

**Comment by mmazzarolo** [comment]
Fixed by @gbhasha in #183

**Comment by mmazzarolo** [comment]
Re-opening, see #183 comment by @wildseansy

**Comment by ptboyer** [comment]
Just ran into this issue now also. Would be good to resolve this please! 😄

**Comment by mmazzarolo** [comment]
Hey @ptboyer , do you have any suggestion on how to fix it? Feel free to submit a PR/point out what could be causing the issue!

**Comment by ptboyer** [comment]
@mmazzarolo Well what I find odd is that this is [something wrong with the DatePickerIOS itself](https://github.com/facebook/react-native/issues/9566) potentially.

I just tried all these "set width, minWidth" solutions that seemed to have worked for people in the past, but like a) it's absurd that changing the style of the component fixes a functional issue, b) despite how ridiculous that solution was, it doesn't work on my current version of React Native (0.55.4).

**Comment by mmazzarolo** [comment]
@ptboyer doing so will disable the enter/exit animation of the picker though :/

**Comment by ptboyer** [comment]
@mmazzarolo Ah, well, I would consider then wrapping the component in some kind of state managed component that takes the prop change and then handles the visibility with a timer or similar to accomodate the animation before destroying the picker through the conditional render.

So instead `pickerVisibile` (from my last solution) is a state variable that responds to a prop for visibility, so we can handle destroying the picker after the animation has played.

But at the moment, I'm concerned with functionality, and not aesthetics. I need the intervals.

**Comment by ptboyer** [comment]
Well I hope that `hideModalContentWhileAnimating` actually destroys the Picker, because we're trying circumvent what's wrong with the picker itself, which seems to be its ability to obey the `minuteInterval` prop when other things change, rather than just when it first initialises.

**Comment by mmazzarolo** [comment]
@ptboyer yeah I know, that prop name doesn't seem related but that's what it does under the hood.

**Comment by jordan-thenumber** [comment]
any progress on this?

**Comment by mmazzarolo** [comment]
@jordan-thenumber have you tried the workarounds above?

**Comment by jordan-thenumber** [comment]
@mmazzarolo i tried showing/hiding using js expression but it's not working in react 57. a fix has been pushed to master so you can cherry pick and apply it. 

https://github.com/facebook/react-native/issues/9566

**Comment by mmazzarolo** [comment]
Thanks @jordan-thenumber . 
I'm closing the issue since it's a DatePicker IOS native problem on which we don't have control on :/ 
It should be fixed by [this RN PR](https://github.com/facebook/react-native/pull/23923) soon though!
