### ISSUE TITLE
Differing behavior between iOS and Android without supplying date prop

### ISSUE THREAD

**Issue by jkdf2** [mmazzarolo/react-native-modal-datetime-picker#161]
As of [v4.0.0](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v4.0.0), the iOS and Android pickers behave the same when providing the `date` prop. Great!

However, they behave differently when not providing `date` as a prop. The iOS picker stores the selected date internally as state and thus remembers your previous selection. On Android, it defaults to `new Date()` every time the picker is re-opened.

One option includes making `date` a required prop and eliminating state within the iOS component. This matches the React philosophy of [lifting state up](https://reactjs.org/docs/lifting-state-up.html#lifting-state-up) and avoids potential sync issues while also simplifying the iOS picker code.

Thoughts?

**Comment by mmazzarolo** [comment]
@jkdf2 
thanks for starting the discussion.

> One option includes making date a required prop and eliminating state within the iOS component. This matches the React philosophy of lifting state up and avoids potential sync issues while also simplifying the iOS picker code.

Yes, I absolutely agree with this. 
I thought about making this change in the past but I never had a chance to do it. 
Anyone available for submitting this PR?

**Comment by RusselFourteen** [comment]
how to change datepicker header color on android?

**Comment by RusselFourteen** [comment]
i want to make it blue or something not green? thanks :)

**Comment by mmazzarolo** [comment]
Fixed by #179 , will be released on npm soon
