### ISSUE TITLE
Include `locale` DatePickerIOS prop in typescript definitions

### ISSUE THREAD

**Issue by freakinruben** [mmazzarolo/react-native-modal-datetime-picker#166]
The readme mentions:
> All the DatePickerIOS props are also supported!

Which is great! When I try to use `locale` however, I noticed this iOS property is missing from the typescript definition: 

```ts
    /**
     * The date picker locale.
     */
    locale?: string;
```

See also https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L2565

**Comment by mmazzarolo** [comment]
Do you mind adding it and submitting a PR? :)
