### ISSUE TITLE
reactNativeModalPropsIOS is missed in index.d.ts

### ISSUE THREAD

**Issue by wack17s** [mmazzarolo/react-native-modal-datetime-picker#169]
Hi, `reactNativeModalPropsIOS` is missed here https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/index.d.ts#L9

**Comment by mmazzarolo** [comment]
Hey! Do you mind submitting a PR? Thanks!

**Comment by wack17s** [comment]
#174 Review please.
