### ISSUE TITLE
Will the 24h format be supported in the iOS time picker any time soon?

### ISSUE THREAD

**Issue by SudoPlz** [mmazzarolo/react-native-modal-datetime-picker#17]
I really need this.

**Comment by SudoPlz** [comment]
Ok I've posted about this here too:
https://github.com/facebook/react-native/issues/12405

That might help others looking for this.

**Comment by mmazzarolo** [comment]
I'm sorry man, this component use react-native's own implementation of the datetime picker, so it must be implemented on it first.   
I'm closing the issue, feel free to re-open if needed.

**Comment by SudoPlz** [comment]
You're right..! Roger that.
