### ISSUE TITLE
date prop not working on Android

### ISSUE THREAD

**Issue by Rodrigo77777** [mmazzarolo/react-native-modal-datetime-picker#170]
Hi, I'm having an issue with the date prop on Android. For some reason, no matter what I pass in on the date prop it still defaults to new Date(). I've tried everything I can think of, but no matter what I do it keeps defaulting to today. I know the values themselves are sound, and I've even tried something as simple as  date={new Date('2020-05-05')} but it just ignores it completely?

Am I missing something really obvious or is the date prop currently not working?

Thanks in advance for your help!

**Comment by mmazzarolo** [comment]
Hi @Rodrigo77777 , please check the [issue template](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/ISSUE_TEMPLATE.md) before submitting a new issue.

Could you share a snippet of the code?

**Comment by Rodrigo77777** [comment]
Hey @mmazzarolo, apologies for not following the issue template! Here's the snippet: 

`<DateTimePicker
                        mode={'datetime'}
                        date={new Date(moment(this.props.startTime).format())}
                        isVisible={this.state.dateTimePickerVisible}
                        onConfirm={this._handleDatePicked}
                        onCancel={this._hideDateTimePicker}
                    />`

I've tried quite a few values in there. Everything else is working absolutely fine with the component, it just always defaults to today's date as the selected date! I'm using version 4.13 of the library.

**Comment by Rodrigo77777** [comment]
Hey @mmazzarolo, turns out this was an issue with my code, took me a while to figure it out. Sorry for bothering you and thanks for the quick reply!!
