### ISSUE TITLE
Errors in callbacks (onConfirm, onCancel) show misleading message.

### ISSUE THREAD

**Issue by aivarsliepa** [mmazzarolo/react-native-modal-datetime-picker#173]
Code from library (this pattern is used all across library).
```javascript
_showTimePickerAndroid = async () => {
    try {
      const { action, hour, minute } = await TimePickerAndroid.open({
        hour: this.props.date.getHours(),
        minute: this.props.date.getMinutes(),
        is24Hour: this.props.is24Hour,
        mode: this.props.datePickerModeAndroid
      });
      if (action !== TimePickerAndroid.dismissedAction) {
        let date;
        if (this.props.date) {
          // This prevents losing the Date elements, see issue #71
          const year = this.props.date.getFullYear();
          const month = this.props.date.getMonth();
          const day = this.props.date.getDate();
          date = new Date(year, month, day, hour, minute);
        } else {
          date = new Date().setHours(hour).setMinutes(minute);
        }
        this.props.onConfirm(date);
        this.props.onHideAfterConfirm(date);
      } else {
        this.props.onCancel();
      }
    } catch ({ code, message }) {
      console.warn("Cannot open time picker", message);
    }
  };
```
Notice, that try catch block is around not only async code `await TimePickerAndroid.open()` , but also around synchronous code, which includes callbacks. If there is error in those callbacks, all we get is yellowbox message with **"Cannot open time picker"**.
**Note:** second argument - `message` (not sure why) is not printed out, hence the real cause of error is lost

My suggestion is to just wrap async code with try cach block and let other errors propagate properly.
What do you think?
If you think this is a good idea, I can submit a pull request.

**Comment by mmazzarolo** [comment]
Hey @aivarsliepa , I agree that wrapping all the code in a try/catch is not a nice pattern - I think initially that block of code was built that way by following [the official TimePickerAndroid docs](https://facebook.github.io/react-native/docs/timepickerandroid).  

Open to PR, just make sure to also test it because I won't be able to test it thoroughly for a few day 👍 
Thanks!
