### ISSUE TITLE
warning message Invalid prop `supportedOrientations`

### ISSUE THREAD

**Issue by radjivF** [mmazzarolo/react-native-modal-datetime-picker#176]
Hey guys,

I got this error message when I try to use the datepicker, any idea ? 

```
Warning: Failed prop type: Invalid prop `supportedOrientations` of value `portrait,landscape` supplied to `ReactNativeModal`, expected one of ["portrait","portrait-upside-down","landscape","landscape-left","landscape-right"].
    in ReactNativeModal (at index.js:157)
    in CustomDatePickerIOS (at DateTimePicker.jsx:71)
```

thanks

**Comment by mmazzarolo** [comment]
Ha! This is just a leftover of a previous warn of react-native-modal, will be fixed with with a dependency update in the next version on `react-native-modal-datetime-picker` 👍 Thank you for reporting.
