### ISSUE TITLE
Date Picker always return initial  date

### ISSUE THREAD

**Issue by ZeroCool00** [mmazzarolo/react-native-modal-datetime-picker#178]
react-native-modal-datetime-picker: "^6.0.0",
react-native: "0.55.4"

Platform: **Android**

Date picker open with today's date selected, when i select different date and click **'ok'**,   it return today's date instead of  selected date.

```
<DateTimePicker
            isVisible={this.state.isDateTimePickerVisible}
            onConfirm={this.handleDatePicked}
            onCancel={this.hideDateTimePicker}
          />

handleDatePicked = (date) => {
    const newDate = moment(Date(date)).format('DD-MM-YYYY');
    this.setState({ selectedDate: newDate });
    this.hideDateTimePicker();
 };
```

**Comment by sushant2111** [comment]
Just add date={this.state.selectedDate} selectedDate will be last selected date. 

<DateTimePicker
    isVisible={this.state.isDateTimePickerVisible}
    onConfirm={this.handleDatePicked}
    onCancel={this.hideDateTimePicker}
    date={this.state.selectedDate}
/>
