### ISSUE TITLE
time picker always return invalid date

### ISSUE THREAD

**Issue by onusgit** [mmazzarolo/react-native-modal-datetime-picker#180]
react-native-modal-datetime-picker: "^6.0.0",
react-native: "0.55.4"

Platform: Android

```
handleTimePicked = (time) => {
    console.log(time);    // Invalid date
    this.hideTimePicker();
  };

<DateTimePicker
        mode='time'
        date={new Date(this.state.selectedTime)}
        isVisible={this.state.isTimePickerVisible}
        onConfirm={this.handleTimePicked}
        onCancel={this.hideTimePicker}
      />
```

**Comment by onusgit** [comment]
Its solved now.. just remove date props when only use time mode..

**Comment by nsisodiya** [comment]
@onusgit - How to set initial time for timePicker !!

**Comment by VKGraphics** [comment]
import DateTimePicker from 'react-native-modal-datetime-picker';
import moment from 'moment';

constructor(props) {
    super(props);
    this.state = {
      selectedDate: moment(new Date()).format('DD-MM-YYYY'),
      selectedTime: moment(new Date()).format('HH:mm'),
    };
  }

handleDatePicked = (date) => {
    const newDate = moment(new Date(date.toString().substr(0, 16))).format('DD-MM-YYYY');
    this.setState({ selectedDate: newDate });
    this.hideDatePicker();
  };

<DateTimePicker
        date={new Date(this.state.selectedDate)}
        isVisible={true/false}
        onConfirm={this.handleDatePicked}
        onCancel={this.hideDatePicker}
      />

**Comment by nsisodiya** [comment]
@VKGraphics - you are not getting.
I am asking for 
`mode='time'`
You are giving example for `Date`.

**Comment by nsisodiya** [comment]
@VKGraphics 

worked, like this

Yup, worked, 

```
state = {
    isDateTimePickerVisible: false,
    selectedDate: '07:00 AM'
};

render() {
    return (
      <Container>
        <Text style={{color: 'white'}}>This is SunRise Screen</Text>
        <TouchableOpacity onPress={this.showDateTimePicker}>
          <Text>Show DatePicker</Text>
        </TouchableOpacity>
        <Text>{this.state.selectedDate}</Text>
        <DateTimePicker
          mode="time"
          date={moment(`2000/10/1 ${this.state.selectedDate}`).toDate()}
          is24Hour={true}
          isVisible={this.state.isDateTimePickerVisible}
          onConfirm={this.handleDatePicked}
          onCancel={this.hideDateTimePicker}
        />
      </Container>
    );
  }
```

**Comment by buddhiv** [comment]
Thank for pointing out this and posting the solution!

**Comment by Dharmik6017** [comment]
> @onusgit - How to set initial time for timePicker !!

date={new Date()}
