### ISSUE TITLE
Swap iOS Picker Day and Month

### ISSUE THREAD

**Issue by robertmylne** [mmazzarolo/react-native-modal-datetime-picker#185]
Is there a way to swap the order to be DAY-MONTH-YEAR in the iOS picker? As that is the standard format in places outside the US.

**Comment by mmazzarolo** [comment]
Hi!
Under the hood this component uses [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios) so the only features available are the ones listed in the official docs.
