### ISSUE TITLE
Time picker granularity

### ISSUE THREAD

**Issue by TeunKooijman** [mmazzarolo/react-native-modal-datetime-picker#187]
Is it possible to set the granularity of the time picker to, for example, 30 minutes? Right now the default is 1 minute (on Android - not a clue what it does on iOS).

**Comment by mmazzarolo** [comment]
Hi, `react-native-modal-datetime-picker` uses the original react-native modules under the hood so you can find the available props [here](https://facebook.github.io/react-native/docs/timepickerandroid).
