### ISSUE TITLE
How to set initial time for timePicker.

### ISSUE THREAD

**Issue by nsisodiya** [mmazzarolo/react-native-modal-datetime-picker#188]
how to set initial selected time for timePicker. I tried the `date` parameter but got this bug - 
https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/180

**Comment by mmazzarolo** [comment]
Hi,
please follow [the issue template](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/ISSUE_TEMPLATE.md) before opening a new issue.

**Comment by nsisodiya** [comment]
@mmazzarolo But I think, I gave the minimum sufficient information. Please show me, how to set up the initial pre-selected "time" for the time-picker. I even referenced, another but,  https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/180 Where we get `Invalid Date` issue. Seems like there is no way for set time for TimePicker.

`mode="time"`

**Comment by harikanammi** [comment]
hi @nsisodiya, can you solve this issue???

**Comment by waqaramjad** [comment]
any update ?
