### ISSUE TITLE
You might wanna add locale as a property

### ISSUE THREAD

**Issue by Return-1** [mmazzarolo/react-native-modal-datetime-picker#190]
Id submit a PR if i wasnt so swamped right now haha, sorry for not doing so but its just a passthrough property, wont take a second.

Thanks for the amazing work

**Comment by mmazzarolo** [comment]
Hey @Return-1 , could you be a bit more specific? 😬 Thanks!

**Comment by Return-1** [comment]
Righto, so the DatePickerIos for example has an option to specify the locale so that the days can be displayed in a different language. If you add that to your component and then pass it to that people will be able to change the language of the days and pm,am.

**Comment by mmazzarolo** [comment]
You can already add [all the DatePickerIOS props](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/7e915e3e0bc3b68a3be17dd299240fc444839119/src/CustomDatePickerIOS/index.js#L188) to the component.

**Comment by edoantonioco** [comment]
> You can already add [all the DatePickerIOS props](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/7e915e3e0bc3b68a3be17dd299240fc444839119/src/CustomDatePickerIOS/index.js#L188) to the component.

Does it works on android? since it says IOS
If not, how can I change the language on android?
