### ISSUE TITLE
can we hide "minutes" in time picker ?

### ISSUE THREAD

**Issue by arpitjain-in** [mmazzarolo/react-native-modal-datetime-picker#191]
Hi,

It is an awesome module developed by @mmazzarolo . I have in requirement where I just need to show hours. How it is possible with this module to just show the hours fields and to hide or show `00` as in minutes fields.

Thanks

**Comment by mmazzarolo** [comment]
Hi @arpitjain-in!
Please follow the [issue template](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/ISSUE_TEMPLATE.md) before submitting a new issue.
Thanks!
