### ISSUE TITLE
Is now() included date object from onConfirm?

### ISSUE THREAD

**Issue by oneduckoo** [mmazzarolo/react-native-modal-datetime-picker#192]
### When reporting a bug, please be sure to check if the issue still persists with react-native original date/time pickers:
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
Before reporting a bug, try swapping `react-native-datetime-picker` with react-native original date/time pickers to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [O] The outcome of the `react-native-modal-datetime-picker` swap described above: Expected to get value
- [O] A descriptive title
- [O] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem): Code will be attached below
- [O] What version of `react-native-modal-datetime-picker` you're using, and the platform(s) you're running it on (iOS, Android, device) Expo using iOS 11.4.1
- [O] What packages or other dependencies you're using: Tested on the environment that only installed react-native-modal-datetime-picker after initializing
- [O] The behavior you expect to see, and the actual behavior: now() should return millisecond of time

I am not sure if it is intentional, but now() is not working when I use date object. I doubted if there was any conflict in my app, so I created a new project through "create-react-native-app" (https://facebook.github.io/react-native/docs/getting-started.html), and I launched the app through Expo. As you see below, I could use getFullYear(), getMonth() and getDate(), but only now() is not working. 

import React from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import DateTimePicker from 'react-native-modal-datetime-picker';

export default class App extends React.Component {
  state = {
      isDateTimePickerVisible: false,
    };

    _showDateTimePicker = () => this.setState({ isDateTimePickerVisible: true });

    _hideDateTimePicker = () => this.setState({ isDateTimePickerVisible: false });

    _handleDatePicked = (selectedDate) => {
      let year = selectedDate.getFullYear();
      let month = selectedDate.getMonth() + 1;
      let day = selectedDate.getDate();

      console.log(year); // success: 2018
      console.log(month); // success: 9
      console.log(day); // success: 5
      console.log(selectedDate.now()); // error
      this._hideDateTimePicker();
    };
  render () {
    return (
      <View style={{flex: 1}}> 
        <View style={{ flex: 1 }}>
          <Text>Hello World!</Text>
        </View>
        <View style={{ flex: 1}}>
          <TouchableOpacity onPress={this._showDateTimePicker}>
            <Text>Show DatePicker</Text>
          </TouchableOpacity>
          <DateTimePicker
            isVisible={this.state.isDateTimePickerVisible}
            onConfirm={this._handleDatePicked}
            onCancel={this._hideDateTimePicker}
          />
        </View>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

### Please note by far the quickest way to get a new feature is to file a Pull Request.

**Comment by mmazzarolo** [comment]
🤔AFAIK `now()` should be called on `Date.now()`, [not on a date instance](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now). 
Did you mean `dateInstance.getTime()`?
