### ISSUE TITLE
datePickerModeAndroid='spinner' doesn't work in Android 7.0

### ISSUE THREAD

**Issue by spacewideweb** [mmazzarolo/react-native-modal-datetime-picker#194]
datePickerModeAndroid='spinner' works in Android 8.0, but doesn't work in Android 7.0.

**Comment by mmazzarolo** [comment]
Hey @spacewideweb .
Yes, Android 8.0 doesn't support the spinner picker. That's why the RN Android DatePicker doesn't support it. 
Since we `react-native-modal-datetime-picker` uses the native Android DatePicker we don't support it.
