### ISSUE TITLE
External usage of function "onCancel"

### ISSUE THREAD

**Issue by vasyl91** [mmazzarolo/react-native-modal-datetime-picker#196]
Hi, 
My app activity depends on connection status. I tried to hide DateTimePicker when it is disconnected but it doesn't seem to work (when I put the code to `render`, picker is still visible, app ends up with infinite loop and crashes after while):

```
if (this.props.connectionStatus === config.connectionStatus.DISCONNECTED) {
   this._hideDateTimePicker;
}
```

 So my other idea is to programmatically use `onCancel` function so it could be triggered when app state changes.  Something like:

```
if (this.props.connectionStatus === config.connectionStatus.DISCONNECTED) {
   this."functionThatUsesOnClose"();
}
```

Is there any way to do that? Thank you in advance for reply!

**Comment by mmazzarolo** [comment]
Hey @vasyl91 , maybe I'm missing something but shouldn't this be enough?  

```javascript
render () {
  const isDisconnected =   this.props.connectionStatus === config.connectionStatus.DISCONNECTED
  return (
    <View style={{ flex: 1 }}>
      <DateTimePicker
        isVisible={!isDisconnected}
        {...yourOtherProps}
      />
    </View>
  );
}
```

**Comment by vasyl91** [comment]
Thank you for your reply! Hmm, that's not really what I meant. Your solution also falls into a loop and ends up with an error. 

Anyway I still want to be able to call DateTimePicker so `isVisible` has to contain value `{this.state._isTimePickerVisible}` .

As far as I have noticed there are only three ways to close once opened DateTimePicker: 
1. Click on `Cancel`, 
2. Click on `Ok` 
3. Click somewhere on the outside of the widget. 
Calling `_hideDateTimePicker` in other way doesn't work.

Clarification:
I would like to have DateTimePicker closed (if it had been opened) when app receives status disconnected.

**Comment by mmazzarolo** [comment]
@vasyl91 please try the example in the README.md first, it will work.

Then, do the following:

```
import React, { Component } from 'react';
import { Text, TouchableOpacity, View } from 'react-native';
import DateTimePicker from 'react-native-modal-datetime-picker';

export default class DateTimePickerTester extends Component {
  state = {
    isDateTimePickerVisible: false,
  };
  
  componentDidUpdate(prevProps) {
    const isDisconnected = this.props.connectionStatus === config.connectionStatus.DISCONNECTED;
    const wasDisconnected = prevProps.connectionStatus === config.connectionStatus.DISCONNECTED;
    if (isDisconnected && !wasDisconnected && this.state.isDateTimePickerVisible) {
      this._hideDateTimePicker();      
    } 
  }

  _showDateTimePicker = () => this.setState({ isDateTimePickerVisible: true });

  _hideDateTimePicker = () => this.setState({ isDateTimePickerVisible: false });

  _handleDatePicked = (date) => {
    console.log('A date has been picked: ', date);
    this._hideDateTimePicker();
  };

  render () {
    return (
      <View style={{ flex: 1 }}>
        <TouchableOpacity onPress={this._showDateTimePicker}>
          <Text>Show DatePicker</Text>
        </TouchableOpacity>
        <DateTimePicker
          isVisible={this.state.isDateTimePickerVisible}
          onConfirm={this._handleDatePicked}
          onCancel={this._hideDateTimePicker}
        />
      </View>
    );
  }

}
```  

If the above snippet doesn't work I would suggest you to create a new question on stackoverflow, since this is not a bug report/feature request.

**Comment by vasyl91** [comment]
Sadly it still doesn't work :( anyway thank you for your help! 
Where can I mark it as feature request?

**Comment by mmazzarolo** [comment]
I'm sorry but this is not a feature request, it's just an issue with your code/project (were you able to run the example available in the readme?).  

Just sign-up into [stackoverflow](https://stackoverflow.com/) and ask a new question about the issue you're having.  
I would also suggest to add there a bit more context (e.g. the entire file).

**Comment by mmazzarolo** [comment]
Re-opening. 
Gotcha. I guess you're on Android, right?

**Comment by vasyl91** [comment]
Yes, I'm working on Android ;)

**Comment by vasyl91** [comment]
Not good ;( I'll request them then. Thank you for your reply!
