### ISSUE TITLE
Warning on mode 'datetime'

### ISSUE THREAD

**Issue by Okipa** [mmazzarolo/react-native-modal-datetime-picker#2]
Hi there,

First, thanx for your package that saved me a lot of time !
I just would like to report you a warning that appears when I set the 'datetime' mode :
`Warning: Failed prop type: Invalid prop `mode` of value `datetime` supplied to `CustomDatePickerIOS`, expected one of ["date","time"].`
I think it would be easy to correct.

**Comment by mmazzarolo** [comment]
Hey @Okipa, thank you!  
Should be fixed in `react-native-modal-datetime-picker@1.1.1`, let me know if it works correctly now 👍

**Comment by Okipa** [comment]
Perfect, it works fine without any warning now. Thanx !
