### ISSUE TITLE
How to support landscape orientation for my view??

### ISSUE THREAD

**Issue by samuelltk** [mmazzarolo/react-native-modal-datetime-picker#20]
How to support landscape orientation for this component?

hello @mmazzarolo,
update:
I use your examples, first, let mobile phone in landscape state, your examples app will be in a horizontal screen, and then click 'Show  TimePicker', at this time, app forced change to vertical orientation when show TimePicker...and ui will show the issure.

**Comment by samuelltk** [comment]
@mmazzarolo

**Comment by mmazzarolo** [comment]
Hello @samuelltk 
Could you be a bit more specific?   
What are you trying to achieve?  
Did you already write some code regarding this issue?  
  
[The container modal](https://github.com/mmazzarolo/react-native-animated-modal) should already resize itself correctly after a device rotation.  
I don't know if the native pickers (DatePickerIOS / DatePickerAndroid / TimePickerAndroid) support the device rotation out of the box.

**Comment by mmazzarolo** [comment]
@samuelltk closing, feel free to re-open if needed.

**Comment by samuelltk** [comment]
@mmazzarolo please reopen this issure. tks.
Now, i just try again,,This issure is the same as last time...please help me, follow my step, you will see the issure on ios.  tks

**Comment by AlanFoster** [comment]
@mmazzarolo Running into the same issue; Triggering the modal's visibility seems to force the app's orientation whilst the modal is open for some reason:

![app](https://cloud.githubusercontent.com/assets/1271782/26249027/90dc7858-3c9c-11e7-9d59-29bf964ca955.gif)

**Comment by AlanFoster** [comment]
@mmazzarolo Awesome, I'll try and give that a go. Thanks for the great component :+1:

**Comment by kyangy** [comment]
Hi! @mmazzarolo i was wondering if there was a fix for this yet?

**Comment by mmazzarolo** [comment]
Hey @kyangy, sorry for being late but I've been on holiday.  
I thought the issue was solved in the react-native-modal discussion that was linked above.  
Are you still having the issue? 
Are you on iOS or Android? Which version of RN and dependencies?

**Comment by SevenSinS02** [comment]
@mmazzarolo This issue still exists. I even updated to react-native-modal 4.1.1. 
The date time picker modal always opens in portrait. This happens in IOS btw.

**Comment by mmazzarolo** [comment]
Hey @SevenSinS02 could you try swapping react-native-datetime-picker with react-native original date/time pickers and check if the problem persists?

**Comment by SevenSinS02** [comment]
@mmazzarolo  So sorry! There was some issue with the ios simulator. It works fine on the Ipad.

Apologies for raising the issue.

**Comment by mmazzarolo** [comment]
No worries, glad it's working :)

**Comment by Sridhar1213** [comment]
> @mmazzarolo So sorry! There was some issue with the ios simulator. It works fine on the Ipad.
> 
> Apologies for raising the issue
did you solved this issues? if yes please help me how to solve

**Comment by anshif10** [comment]
while opening modal in ios it's going to portrait mode but fine in android 

          <DateTimePickerModal
               isVisible={open}
               mode="date"
               onConfirm={onConfirm}
               onCancel={dismiss}
               supportedOrientations={['portrait', 'landscape']}
             />

pls help

**Comment by iformal42** [comment]
modalPropsIOS={{
                supportedOrientations: ['portrait', 'landscape'],
            }}
this prop works for me
