### ISSUE TITLE
Is there any way to show the date till yesterday in DatePicker window?

### ISSUE THREAD

**Issue by TechSatya** [mmazzarolo/react-native-modal-datetime-picker#201]
I wanted to show the date till yesterday with time 00:00:00 in Date and Time Picker window. I didn't find any proper way to get it done, so any ideas or suggestions please??

**Comment by mmazzarolo** [comment]
Hey!
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
This means that if your feature is not supported by these components you won't be able to use it with `react-native-datetime-picker` 🙍
