### ISSUE TITLE
Month picker

### ISSUE THREAD

**Issue by gimoteco** [mmazzarolo/react-native-modal-datetime-picker#208]
Is it possible to configure this library to pick only a month (month picker)?

**Comment by mmazzarolo** [comment]
Hey!
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
This means that if your feature is not supported by these components you won't be able to use it with `react-native-datetime-picker` 🙍
