### ISSUE TITLE
iOS datetime picker keeps previous date

### ISSUE THREAD

**Issue by bitsal** [mmazzarolo/react-native-modal-datetime-picker#21]
My situation:
1. A form has your datetime picker field. 
2. When I open the form set time and submit the form.
3. Open the form again with changed time (default value is used).
4. But when you open datetime picker old value is there.

I've reviewed code in https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/CustomDatePickerIOS/index.js and noticed that there is no any code to update `this.state.date`.

There is a workaround: unload form/field and load it again.

Please fix it to avoid component unloading.

**Comment by mmazzarolo** [comment]
I recently merged PR #18 that should address you issue.  
I haven't pushed it to NPM yet, would you mind trying it?  
The best way to try it is pulling the library from the Master branch.  
Alternatively, simply copy-paste the content of [this file](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/CustomDatePickerIOS) in your `node_modules/react-native-modal-datetime-picker/src/CustomDatePickerIOS/index.js`.   
Then just reset the server `npm run start -- --reset-cache` and fire up your emulator.  

P.S.: The interested line is [this one](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/CustomDatePickerIOS/index.js#L36)

**Comment by bitsal** [comment]
@mmazzarolo thank you, I can prove that your fix works. Looking forward to new version.

**Comment by mmazzarolo** [comment]
Cool! Can you also give it a try at the Android version?  If it work correctly I'll release the version soon this evening :)

**Comment by bitsal** [comment]
I see there is only this fix from 3.0.1 version. I don't think it can break Android somehow due to you have different components for iOS and Android.

BTW, I've checked it on Android. It seems to work as expected.

**Comment by mmazzarolo** [comment]
My bad, I didn't wrote it correctly, I simply wanted to know if currently the Date gets updated correctly on Android too (it's important having platform parity!).  
Thank you @bitsal, you should expect a next release soon 👍

**Comment by bitsal** [comment]
Oh, I got it. Be calm the issue was only on iOS side, at least in our app.

**Comment by mmazzarolo** [comment]
@bitsal landed in [release 4.0.0](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v4.0.0)

**Comment by temitope** [comment]
thanks so much for this fix guys!
