### ISSUE TITLE
How can I restrict user to select time in between 8 AM to 3 PM

### ISSUE THREAD

**Issue by blabz-rahulmandalkar** [mmazzarolo/react-native-modal-datetime-picker#211]
In case of time, I want to restrict user to select time in between 8 AM to PM, so as like minimum date and maximum date.How can i apply same to time picker also ?

**Comment by mmazzarolo** [comment]
Hey!
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
This means that if your feature is not supported by these components you won't be able to use it with `react-native-datetime-picker` 🙍
