### ISSUE TITLE
minimumDate and maximumDate not work together

### ISSUE THREAD

**Issue by riaydh06** [mmazzarolo/react-native-modal-datetime-picker#214]
<DateTimePicker
            isVisible={isEndDatePickerVisible}
            onConfirm={this.handleSelectTime}
            onCancel={this.handleDatePickerToggole}
            mode="date"
            minimumDate={new Date(fromDate)}   // fromDate = 2019-01-01
            maximumDate={maxDate}   // new Date()
          />

**Comment by mmazzarolo** [comment]
Hi,
please follow [the issue template](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/ISSUE_TEMPLATE.md) before opening a new issue.

**Comment by uncledent** [comment]
Having same issue

**Comment by idanlevi1** [comment]
> Hi,
> please follow [the issue template](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/ISSUE_TEMPLATE.md) before opening a new issue.

404 :(

**Comment by AsABarranco** [comment]
+1
