### ISSUE TITLE
Date picker error in RN 0.58.x

### ISSUE THREAD

**Issue by nwaughachukwuma** [mmazzarolo/react-native-modal-datetime-picker#220]
Hi @mmazzarolo am getting the error in the attachment after updating to RN 0.58.4. Please what could be the problem?
![whatsapp image 2019-02-11 at 16 23 07](https://user-images.githubusercontent.com/20521315/52638383-288f4a80-2ed2-11e9-8f34-cdfd1866836f.jpeg)

**Comment by marcinolek** [comment]
same here, it occurs when you tap confirm after selecting date (on iOS)

**Comment by nwaughachukwuma** [comment]
@marcinolek I encountered this issue on Android

**Comment by mmazzarolo** [comment]
Hey, could you please follow the issue template ?

### When reporting a bug, please be sure to check if the issue still persists with react-native original date/time pickers:
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
Before reporting a bug, try swapping `react-native-datetime-picker` with react-native original date/time pickers to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [ ] The outcome of the `react-native-modal-datetime-picker` swap described above
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `react-native-modal-datetime-picker` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior


### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

### Please note by far the quickest way to get a new feature is to file a Pull Request.

**Comment by nwaughachukwuma** [comment]
Alright @mmazzarolo this is noted

**Comment by marcinolek** [comment]
@mmazzarolo @nwaughachukwuma I found an issue in my code so the issue became invalid to me. I passed 'null' as date prop to the date picker at some point, which was incorrect. Apparently in previous version of RN it was allowed to pass null via bridge. One more thing, surprisingly it didn't crash (for me) in release builds, only when debugging.

**Comment by mmazzarolo** [comment]
@marcinolek thanks for reporting back :)
