### ISSUE TITLE
Language locale not change in Android 

### ISSUE THREAD

**Issue by Samyak81** [mmazzarolo/react-native-modal-datetime-picker#221]
react-native-modal-datetime-picker , I have given locale string as below. 

  <DateTimePicker
              isVisible={this.state.isDatePickerVisible}
              mode={"date"}
              locale={ "ar"}
              cancelTextIOS={strings("dialog.cancel")}
              confirmTextIOS={strings("dialog.okay")}
              minimumDate={funGetTomorrowDate()}
              onConfirm={this._handleDatePicked}
              onCancel={this._hideDatePicker}
            />

But it opens date and time picker in English language only. For Ios it  works fine. Any solution for this bug then let me know.

**Comment by mmazzarolo** [comment]
Hey!
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
This means that if your feature is not supported by these components you won't be able to use it with `react-native-datetime-picker`.
