### ISSUE TITLE
How do I disable weekends in the react-native-modal-datetime-picker?

### ISSUE THREAD

**Issue by danielst19** [mmazzarolo/react-native-modal-datetime-picker#226]
How to disable weekends in the react-native-modal-datetime-picker?

**Comment by mmazzarolo** [comment]
Hey!
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
This means that if your feature is not supported by these components you won't be able to use it with `react-native-datetime-picker`.
