### ISSUE TITLE
Date ranges on react-native-modal-datetime-picker?

### ISSUE THREAD

**Issue by Danultimate** [mmazzarolo/react-native-modal-datetime-picker#227]
Im trying to implement a the react-native-modal-datetime-picker, I know isn't possible to select a range of times but theres any work around for dates?

**Comment by Makar8000** [comment]
Check the [readme](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/README.md#available-props). You can use the minimumDate and maximumDate props

**Comment by Danultimate** [comment]
> Check the [readme](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/README.md#available-props). You can use the minimumDate and maximumDate props

Thanks, but I meant let the user select a date range for 1 feb to 15 feb for example, not restrict the possible dates.

**Comment by Makar8000** [comment]
Apologies; I misread your post. I am not sure how to do that.

**Comment by alexandrius** [comment]
@Danultimate Try these: https://github.com/wix/react-native-calendars, https://github.com/Tinysymphony/react-native-calendar-select

**Comment by mmazzarolo** [comment]
@Danultimate nope, not doable unless the RN Android/iOS date pickers allow it. 
P.S.: Thanks @Makar8000 and @alexandrius 💯
