### ISSUE TITLE
Does not match the system clock

### ISSUE THREAD

**Issue by gundogduyakici** [mmazzarolo/react-native-modal-datetime-picker#231]
Hello there,
I live in Turkey. If I choose 10:00, it sets the time to 7. 3 hours difference. What is the solution to this?

Thank you.

**Comment by mmazzarolo** [comment]
Hey!
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    

Please check the [How to set locale section in the README](https://github.com/mmazzarolo/react-native-modal-datetime-picker#how-to-set-automatic-locale-in-ios)

**Comment by gundogduyakici** [comment]
Thank you @mmazzarolo
