### ISSUE TITLE
Customized Time

### ISSUE THREAD

**Issue by helloitsm3** [mmazzarolo/react-native-modal-datetime-picker#234]
How do I customize the timing for the time picker? Currently, I'm able to select from 0 - 59 in the minutes column. I would like the user to only use it in a multiple of 5. How do I do it?

**Comment by mmazzarolo** [comment]
Hi! Please follow the issue template before filling a new issue.

**Comment by ansal-exp** [comment]
@helloitsm3 You can use the `minuteInterval` for this. For your case, `minuteInterval={5}`.
Valid prop values are [1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30].
refer: https://facebook.github.io/react-native/docs/datepickerios.html#minuteinterval
Also refer: DatePickerIOS for more details.

**Comment by helloitsm3** [comment]
> 
> 
> @helloitsm3 You can use the `minuteInterval` for this. For your case, `minuteInterval={5}`.
> Valid prop values are [1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30].
> refer: https://facebook.github.io/react-native/docs/datepickerios.html#minuteinterval
> Also refer: DatePickerIOS for more details.

Thank you. I manage to get it working
