### ISSUE TITLE
How to set the maximum year ?

### ISSUE THREAD

**Issue by JayKurniawan** [mmazzarolo/react-native-modal-datetime-picker#235]
I want to set the maximum year only (10 years ago) and make all date is available.
But I can't make it, some date is disabled
Here's some of my code:

```js
var birthDate_max = new Date()
birthDate_max.setDate(birthDate_max.getDate()-3650)

<DateTimePicker
        confirmTextIOS={'OK'}
        titleIOS='Birthdate'
        maximumDate={birthDate_max}
        isVisible={this.state.showDatePicker}
       onConfirm={this.handleBirthDatePicked}
       onCancel={this.hideDatePicker}
/>
```
![Screenshot_20190415-014941](https://user-images.githubusercontent.com/6804018/56097647-7b609f00-5f21-11e9-99c0-b0e29f2d0fd6.png)

**Comment by mmazzarolo** [comment]
Hi! Please follow the issue template before filling a new issue.
