### ISSUE TITLE
Time Format 

### ISSUE THREAD

**Issue by majidalik** [mmazzarolo/react-native-modal-datetime-picker#240]
Can we get formatted time onConfirm? I need only HH:MM:ss.

 <Timepicker
          isVisible={this.state.isDateTimePickerVisible}
          onConfirm={this.handleDatePicked}
          onCancel={this.hideDateTimePicker}
          mode={"time"}
        />

**Comment by mmazzarolo** [comment]
The returned date is a standard [JS date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date), so you can format it using the JS date APIs
