### ISSUE TITLE
Want to get just minute and seconds

### ISSUE THREAD

**Issue by haseebb** [mmazzarolo/react-native-modal-datetime-picker#242]
I just want to get min and sec so how I can get please help.

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/240

**Comment by haseebb** [comment]
No Sir, I want to show min and sec to a user then the user will select min and sec

**Comment by brunohkbx** [comment]
@haseebb did you found a solution? Having the same problem here.

**Comment by SushiWaUmai** [comment]
@haseebb Facing the same problem, just opened a issue on the `react-native-datetimepicker/datetimepicker` library.
