### ISSUE TITLE
 I want to show min and sec to a user then the user will select min and sec

### ISSUE THREAD

**Issue by haseebb** [mmazzarolo/react-native-modal-datetime-picker#243]
Sir
 Actually I want to show min and sec to a user then the user will select min and sec

**Comment by haseebb** [comment]
Like below


<img width="157" alt="Screenshot 2019-05-03 at 9 45 11 AM" src="https://user-images.githubusercontent.com/38561017/57128257-44f1a380-6dac-11e9-940c-8d58294eee16.png">

**Comment by mmazzarolo** [comment]
@haseebb please follow the issue template before opening a new issue. 
### When reporting a bug, please be sure to check if the issue still persists with react-native original date/time pickers:
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
**Before reporting a bug, try swapping `react-native-datetime-picker` with react-native original date/time pickers to check if the problem persists.**
