### ISSUE TITLE
Support for timezones?

### ISSUE THREAD

**Issue by Brqqq** [mmazzarolo/react-native-modal-datetime-picker#245]
## Ask your Question

Say the time is 0:00 UTC and I'm in GMT+1 and I open the timepicker, the time will show 01:00.

What if I want to show 0:00 instead? Do I have to manually do some date shifting based on the UTC offset to get this behaviour? Or is there some way to set a timezone?

**Comment by mmazzarolo** [comment]
👋 this component doesn't the input/output date and/or its manipulation, at least not more than the native components do. So, yes, you'll need to do that directly outside of it.

**Comment by domenbukovac** [comment]
I had the same problem and I solved it using **moment**.

`new Date('2000-01-01T20:00:00')` parses a string as UTC, but time picker will adjust it to local time. So if the local timezone is GMT+1, time picker would display **21:00**.

While moment parses the same string as local time by default.
`moment('2000-01-01T20:00:00').toDate()` on a device with GMT+1 timezone would return a date object with UTC time 19:00 and then time picker will adjust it back to GMT+1 and display it as **20:00**.


So if you want to set initial time from a string, you should set date prop to
```
<DateTimePicker
      mode="time"
      date={moment('2000-01-01T20:00:00').toDate()}
      onConfirm={this._handleTimePicked}
/>
```

No matter the timezone settings, initial time displayed would be 20:00. Then when a user selects time **10:00** in his local time zone, say GMT+3, onConfirm function would return a Date object in UTC time **07:00**. If you want to convert it to local time and display it as a string, you could do it like this:
```
  _handleTimePicked = date => {
    timeStringLocal = moment(date).format("HH:mm"); // "10:00"
    timeStringUTC = moment(date).utc().format("HH:mm"); // "07:00"
    console.log(timeStringLocal);
  };
```

>  If you want to parse a date-time string as UTC with moment, **Z** should be added at the end.
> `moment('2000-01-01T20:00:00Z')` would return an object with UTC time 20:00

**Comment by Brqqq** [comment]
Thanks for the suggestion.

One thing to consider that makes this more confusing is that V8 (so in debug mode) and JavascriptCore have different behaviors here. 

`new Date('2000-01-01T20:00:00')` is actually parsed in local timezone in debug mode. This is according to the latest ECMA spec which states that the lack of timezone specifier in a date time string should mean it's parsed in local timezone. That's what happens in debug mode too.

In non-debug mode, the same line is parsed as UTC like you said. The getTimezoneOffset is the same in either case.
