### ISSUE TITLE
Picker resets to saved date if enclosing component re renders

### ISSUE THREAD

**Issue by hugofelp** [mmazzarolo/react-native-modal-datetime-picker#247]
## Environment
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 98.02 MB / 16.00 GB
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Platforms
iOS

- iOS: 12.2
- react-native-modal-datetime-picker: 7.4.0

## Description

We have a component with a notification counter and a time picker. If a new notification arrives while the user is setting a time, the picker will scroll back to its original position.

## Reproducible Demo
```
import { Text, View } from "react-native";
import TimePicker from "react-native-modal-datetime-picker";
export default class Example extends React.Component {
    constructor( props ) {
        super(props)
        this.state = {
            notificationCount: 0
        }
    }
    componentDidMount() {
        this.timerRef = setInterval(
            () => this.setState( state => ( {
                notificationCount: state.notificationCount + 1
            } ) ),
            2000
        )
    }
    componentWillUnmount() {
        clearInterval( this.timerRef )
    }
    render() {
        var baseDateFromProps = 1557889993116;
        var derivedDate = new Date(baseDateFromProps + 10000);
        return (
            <View>
                <Text>you have {this.state.notificationCount} notifications</Text>
                <TimePicker
                    onConfirm={()=>{}}
                    onCancel={()=>{}}
                    isVisible={true}
                    date={ derivedDate }
                />
            </View>
        )
    }
}
```

**Comment by mmazzarolo** [comment]
Fix merged!
