### ISSUE TITLE
Crashes iOS app when using debugger

### ISSUE THREAD

**Issue by nolan-m** [mmazzarolo/react-native-modal-datetime-picker#25]
While using the in browser debugger with React Native, this library freezes up the iOS app when displaying the modal leading to crash.  I am using the example in the Usage section of the ReadMe.  Works fine when debugger is turned off.

**Comment by mmazzarolo** [comment]
hi, it's a rn issue, fixed in rn 0.43 :)
https://github.com/facebook/react-native/issues/12747
