### ISSUE TITLE
 There must be a clear button to clear the date in android like the image attached with this thread.

### ISSUE THREAD

**Issue by sudhanshu-kiwi** [mmazzarolo/react-native-modal-datetime-picker#250]
Whyyyyyyy?

![Screenshot 2019-05-16 at 5 37 50 PM](https://user-images.githubusercontent.com/47819036/57852818-d415a700-7801-11e9-82b1-1a67a2c1d69f.png)

**Comment by mmazzarolo** [comment]
Please follow the issue template before submitting a new issue 👋

**Comment by dipanshusahu** [comment]
@mmazzarolo i also need this feature, do you have any idea or workaround to add clear button somehow?

**Comment by mmazzarolo** [comment]
@dipanshusahu is it available on the native Android date/time picker?

**Comment by dipanshusahu** [comment]
@mmazzarolo there's 'Context' theme for adding extra button in native android date/time picker and action can also be set on them.

**Comment by mmazzarolo** [comment]
@dipanshusahu I mean in the React-Native original Android pickers. 
Please see [this](https://github.com/mmazzarolo/react-native-modal-datetime-picker#the-component-is-not-working-as-expected).  
Unfortunately if the original React-Native Android pickers don't support it we can't do it.

**Comment by dipanshusahu** [comment]
@mmazzarolo Thanks for quick reply, I really appreciate your answers. For now i have included one clear button in my app for clearing the date field. If in future you add this functionality it would be very helpful. Again thanks a lot.
