### ISSUE TITLE
DateTimePicker is not appearing the second time.

### ISSUE THREAD

**Issue by mubashirsaleemi** [mmazzarolo/react-native-modal-datetime-picker#251]
## Ask your Question

When I press on the input for the first time the Time Picker popup appears and let me select a time, after selecting time the time picker popup hides but when I press the input again the popup doesn't appear. why is this happening??

**Comment by mmazzarolo** [comment]
Please check the issue template before submitting an issue, thanks!

**Comment by Zangetsu0** [comment]
Any solution? Date picker not appearing second time. (Only in android), ios working fine.

**Comment by Shivani12345** [comment]
I am facing same issue with android device. Can you please help?

**Comment by sanjeevkse** [comment]
Hi,

I am also facing the same issue. Is there any workaround or anything we could get as help!

**Comment by bvangrimberge** [comment]
I was facing the same issue but realised I did not hide the modal manually in the onConfirm handler.

Make sure you set your isVisible variable to false in the onConfirm handler.

Example : 

const [isDatePickerVisible, setDatePickerVisibility] = useState(false);

<DateTimePickerModal
        isVisible={isDatePickerVisible}
        mode="date"
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
      />
...

  const handleConfirm = (date) => {
    setDatePickerVisibility(false);
  };
