### ISSUE TITLE
using state.date with redux form.

### ISSUE THREAD

**Issue by superandrew** [mmazzarolo/react-native-modal-datetime-picker#252]
## Ask your Question
Note: This question have been asked on stackoverflow [here](https://stackoverflow.com/questions/56308834/binding-redux-form-input-value-to-a-datetimepicker) on its redux form specificity, but as a general question I would like to understand how to "show" a date value without calling redux form's onChange or setting its value.

I am using this library with a <Input> field with a redux form, so I created a custom component which ties together the picker and the input field to show the selected value. When I press the touchable opacity, the picker shows, the "onChange" event is fired, so the value is set on the input field using `this.state.date`.

But when should I update the state date with the values passed from redux-form? it should be before the render method, otherwise I finish in an infinite loop. My component always shows gg/mm/aaaa unless someone changes the date. But the value is there, because if I open the picker it shows the redux form date it is supposed to.

here's my component code:

```
import React, { Component } from "react";
import { TouchableOpacity, StyleSheet } from "react-native";
import { Text, theme, Button, Block, Input } from "galio-framework";
import DateTimePicker from "react-native-modal-datetime-picker";

export class DateInputField extends Component {
  constructor(props) {
    super(props);
    this.state = { isDateTimePickerVisible: false };
    this.handleChange = this.handleChange.bind(this);
  }
  showDateTimePicker = () => {
    this.setState({ isDateTimePickerVisible: true });
  };
  hideDateTimePicker = () => {
    this.setState({ isDateTimePickerVisible: false });
  };
  handleChange = date => {
    console.log("date->" + date);
    this.setState({ isDateTimePickerVisible: false, date: date });
    this.props.input.onChange(date);
  };
  render() {
    const { input, meta, ...inputProps } = this.props;
    return (
      <Block style={styles.container}>
        <TouchableOpacity onPress={this.showDateTimePicker}>
          <DateTimePicker
            date={new Date(input.value)}
            
            onDateChange={this.handleChange}
            cancelTextIOS="Annulla"
            confirmTextIOS="Conferma"
            isVisible={this.state.isDateTimePickerVisible}
            onConfirm={this.handleChange}
            onCancel={() => this.setState({ isDateTimePickerVisible: false })}
            label
          />

          <Input
            color={"black"}
            editable={false}
            // onTouch={this.showDateTimePicker}
            // onFocus={this.showDateTimePicker}
            label={this.props.label}
            style={styles.input}
            placeholder={this.props.placeholder}
            value={
              this.state.date != undefined
                ? this.state.date.getDate() +
                  "/" +
                  (this.state.date.getMonth() + 1) +
                  "/" +
                  this.state.date.getFullYear()
                : "gg/mm/aaaa"
            }
          />
        </TouchableOpacity>
      </Block>
    );
  }
}
export const styles = StyleSheet.create({
  container: {},
  label: {},
  input: { flex: 1, color: "red", padding: 0, height: 50 }
});

```

Ideas? Any help is appreciated.

**Comment by mmazzarolo** [comment]
Not sure I'm following... It has been year since the last time I used redux-form. 
Why is it ending in an infinite loop?  
Also, if you're using redux-form, why are you also keeping the date in the component state? 🤔

**Comment by superandrew** [comment]
Ok probably this is related to my "noobieness" 😬

In redux-forms I have `input.value` which is the value provided by the form and `input.onChange` to handle the change in the control as it happens and to propagate it back to redux-forms.

The reason I used the component's state was to store the selected date so that the DateTimePicker was using that date, but probably that was a wrong experiment.

My main confusion is related to the conversion between the string value coming from redux-forms, its date representation, and the display on the field, because most of the examples of this component start with a button which doesn't display a date.

So are you suggesting, I should always use input.value, converting its value to a date to feed it to the datetimepicker and from the date to the proper format to display it in the text field before and after the choosing of the date?

**Comment by mmazzarolo** [comment]
> So are you suggesting, I should always use input.value, converting its value to a date to feed it to the datetimepicker and from the date to the proper format to display it in the text field before and after the choosing of the date?
Yes, I would suggest to stick to one "store" and follow that path. So, if you're using redux-form, I would provide to both the DateTimePicker and to the input the same value (that comes from redux) and format it accordingly.

**Comment by superandrew** [comment]
this way it works, posting it on stackoverflow in case it helps anyone having the same problem understanding the flow as I did. Thanks!
