### ISSUE TITLE
Setting maximumDate to null crashes android

### ISSUE THREAD

**Issue by pmo022** [mmazzarolo/react-native-modal-datetime-picker#253]
## Platforms
Android only

## Versions
Android
- react-native-modal-datetime-picker: v.7.4.2
- react-native: 0.59.3
- react: 16.8.6

## Description
Setting maximumDate to `null` will crash the android implementation of the datePicker. 
Note that setting it to `undefined` works as it should. Component stability could be improved by doing a check in the constructor of the component.

## Reproducible Demo
Install react-native-modal-datetime-picker v 7.4.2. in a react native project.
Import the component on any screen of your app.
Use the component, setting maximumDate to `null`.

Expected behaviour - no maximum date exists.
Actual behaviour - component crashes with nullpointer.

**Comment by mmazzarolo** [comment]
@pmo022 thanks for reporting.
This issue is still happening with the native Android picker though, am I right?

**Comment by pmo022** [comment]
I haven't tried the native android picker - it might be.

The reason why I reported it here / considered it a bug in this library instead of checking the native implementation is that the behaviour an RN Component should be similar on android and ios given the same input. The fix should be easy, you can essentially just add `this.props.maximumDate |= undefined`  to your components constructor

**Comment by mmazzarolo** [comment]
Yup, makes sense! Was just wondering if if was an error specific to this component :)

**Comment by mmazzarolo** [comment]
Thanks for reporting, it will be fixed once [this PR](https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/262) gets merged.

**Comment by mmazzarolo** [comment]
Closing in favour of #301, which fixes the issue.
