### ISSUE TITLE
minuteInterval prop doesn't work in production

### ISSUE THREAD

**Issue by rauldeheer** [mmazzarolo/react-native-modal-datetime-picker#254]
## Environment

I'm using Expo SDK v33 with React Native 0.59.

## Platforms

This prop isn't available on Android so it is iOS only. The bug only occurs on a build tested through Testflight.

## Versions

- Android: x
- iOS: 12.3.1
- react-native-modal-datetime-picker: 7.4.2
- react-native: 0.59
- react: 16.8.3

## Description

While I'm developing and testing the app everything works fine, but in the production build the picker prop `minuteInterval` isn't working.

**Comment by mmazzarolo** [comment]
Hey! Thanks for reporting. 
Could you please follow the issue template in its entirety?
