### ISSUE TITLE
Not work in "Remote JS Debug" mode

### ISSUE THREAD

**Issue by HermitCarb** [mmazzarolo/react-native-modal-datetime-picker#26]
Versions:
```
"react": "15.4.2",
"react-native": "0.42.0",
"react-native-modal-datetime-picker": "^4.1.0",
```

I just copy the code from READEME.md. 
In "Remote JS Debug" mode, it don't work in simulator. The ```TouchableOpacity``` just keep highlight and nothing happens. When some other operations taked, it will crash. My iPhone(6s Plus, 10.2.1), same as simulator. 

But not in "Remote JS Debug" mode, it works well both simulator and iPhone. 

Edit: On android(SAMSUNG Galaxy S6, Android 5.1.1) all works well.

**Comment by mmazzarolo** [comment]
Hi @HermitCarb !
It is a known react-native issue #25, it is fixed in 0.43 :)
