### ISSUE TITLE
disable minutes in timepicker

### ISSUE THREAD

**Issue by abodehq** [mmazzarolo/react-native-modal-datetime-picker#260]
How can i disable minutes in timepicker and set it always to 00 , i want users to select only hours ??

please help.

**Comment by mmazzarolo** [comment]
That's not supported, sorry.

**Comment by roshan-rently** [comment]
is setting the picker for hours and disabling the minutes section supported now.? or any plans for supporting it.?

**Comment by mmazzarolo** [comment]
nope, unfortunately, that's not something in our control, this kind of feature would need to land in the community date-time-picker first.

**Comment by lavanyasundararajan** [comment]
is this available now, even i want to disable the minutes, it should automatically set to 00

**Comment by ankittrootech123** [comment]
Yes we can disable minutes to provide minuteInterval={60}

**Comment by KasundananjayaT** [comment]
I set minuteInterval= {60} but nothing change neh?

**Comment by AliAbbasTX** [comment]
```javascript
<DateTimePickerModal
        date={selectedDate}
        isVisible={datePickerVisible}
        mode="time"
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
        minuteInterval={60}
      />
``` 

It says 
`type '60' is not assignable to type '20 | 15 | 1 | 5 | 3 | 10 | 4 | 2 | 6 | 12 | 30'.`
What other solution we can try??
