### ISSUE TITLE
How to display selected datetime in ISO format

### ISSUE THREAD

**Issue by emclab** [mmazzarolo/react-native-modal-datetime-picker#261]
## Ask your Question
I would like to display the datetime selected in ISO format like this:

       YYYY-MM-DDTHH:MM

I did not find format related property to set. Here is what I have now:

          <DateTimePicker
                isVisible={this.state.startDateTimePickerVisible}
                onConfirm={this.handleStartDatePicked}
                onCancel={this.hideStartDateTimePicker}
                datePickerModeAndroid='spinner'
                timePickerModeAndroid="spinner"
                minuteInterval={10}
                mode="datetime"
                is24Hour={false}
            />

Here is the datetime displayed:

![Capture1](https://user-images.githubusercontent.com/946013/61230908-d69c5c00-a6df-11e9-8e16-9bc8bba93dd3.JPG)

Also how can I setup the time interval to 10min in Android? There is a time interval for IOS only.

**Comment by kishansbs** [comment]
getting this ----  Fri Jul 19 2019 20:09:00 GMT+0530 (India Standard Time)
i want to convert it into -- DD-MM-YYYY HH:mm

when i using moment.js, I am getting this warning--

**Comment by emclab** [comment]
When I use date.toISOString(), then the time is converted to UTC time which is offset by +7 hour compared with PDT time. Is there a way I can convert to ISO date format in PDT time? Should I use module moment or date-fns to handle this conversion?

**Comment by emclab** [comment]
`kishansbs` , did you try date-fns module for conversion? You can import format only to reduce the size imjported.

**Comment by mmazzarolo** [comment]
Hey @kishansbs , the Date returned from the component is a standard JS date, so you can use any library/API you want to interact with it (moment, date-fns, or even just the plain JS api)

**Comment by mmazzarolo** [comment]
P.S.: Minute interval for android is not supported

**Comment by Razorholt** [comment]
You also use split(). Example:

```
handleDatePicked = date => {
   const mdate = date.toString().split(" ");
   this.setState({
       newFormat : mdate[1] + " " + mdate[2] + ", " + mdate[3]
   });
}
```
