### ISSUE TITLE
12 hour time picker without AM/PM?

### ISSUE THREAD

**Issue by 0Shift** [mmazzarolo/react-native-modal-datetime-picker#264]
is there a way of creating a 12 hour time picker? or any other restricted time picker?

**Comment by mmazzarolo** [comment]
This component supports all the [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios) and [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid) props, so you might wanna look into them... but as far as I know there's no way to restrict the picker that way.
