### ISSUE TITLE
How to set 24 hours in iOS in one easy step

### ISSUE THREAD

**Issue by hetmann** [mmazzarolo/react-native-modal-datetime-picker#265]
## Suggestion

Not a question just a suggestion to maybe update the README for **"How to set 24 hours in iOS ?"**

This is working for me by just adding **locale="en_GB"**
```jsx
<DatePicker
  mode="time"
  locale="en_GB"
  date={new Date()}
/>
```

**Comment by mmazzarolo** [comment]
Ha! Thanks, wasn't aware of this! Adding it now.
