### ISSUE TITLE
 Add a point (.) to AM and PM and library translation

### ISSUE THREAD

**Issue by pixsolution** [mmazzarolo/react-native-modal-datetime-picker#267]
Hi, I am using this package and it works fine for me, attached captures:

![Captura de Pantalla 2019-08-13 a la(s) 4 32 24 p  m](https://user-images.githubusercontent.com/47191848/63007637-4fc6d480-be81-11e9-87dd-28cadcfde84f.png)
![Captura de Pantalla 2019-08-13 a la(s) 4 33 03 p  m](https://user-images.githubusercontent.com/47191848/63007643-53f2f200-be81-11e9-9d27-e84c8058a17b.png)

But I need 2 things:

1. How do I add a point (.) to AM and PM format? I need to display A.M and P.M because the api that I am using in this project is like this and does not accept it without a point.

2. How to translate the library into Spanish? to display date in spanish

Thanks in advance
regards

**Comment by hetmann** [comment]
@pixsolution 

1. is seams that you're sending the time to the API in a format that it doesn't accept it. You need to format the string you're sending to the API.
2. use prop locale="es_ES"

**Comment by mmazzarolo** [comment]
Yup, I agree with @hetmann (thanks for posting). 

Regarding the first question, `react-native-modal-datetime-picker` uses the standard JS date format, so you should be able to format it manually.

**Comment by pixsolution** [comment]
Thank you for your answers @hetmann @mmazzarolo but:
1. OK
2. The language did not work, I attached the 2 options I tried. I don't know if you see something that is not right?

`//option 1
NSLocale * locale = [[NSLocale alloc] initWithLocaleIdentifier:@"es_ES"];
   datePicker.locale = locale;
   datePicker.calender = [locale objectForKey:NSLocaleCalender];
   
//option 2 
NSString *currentLanguage = [[NSLocale preferredLanguages] firstObject];
  [[UIDatePicker appearance] setLocale:[[NSLocale alloc]initWithLocaleIdentifier:@"es_ES"]];`

attached also capture of the device so that you see that it is configured in Spanish, and nothing it keeps showing everything of the package in English
![Captura de Pantalla 2019-08-14 a la(s) 3 40 10 p  m](https://user-images.githubusercontent.com/47191848/63051437-8599a680-bedd-11e9-850b-f4f66107cfd2.png)

**Comment by hetmann** [comment]
@pixsolution the **[locale](https://facebook.github.io/react-native/docs/datepickerios#locale)** prop is used to render the date/time based on regions, basically it will translate it to Spanish: Monday -> Lunes

The idea is that the **DateTimePicker** will give you a value and you can format that value based on your needs.

Formatting is done using libraries like this:
- **dayjs**: https://github.com/iamkun/dayjs
- **momentjs**: https://github.com/moment/moment/
