### ISSUE TITLE
not supporting on react native web

### ISSUE THREAD

**Issue by theZulqarnain** [mmazzarolo/react-native-modal-datetime-picker#268]
when I'm using it on react native web it does not support time and date picker.

**Comment by mmazzarolo** [comment]
@theZulqarnain Under the hood react-native-modal-datetime-picker uses react-native original DatePickerAndroid, TimePickerAndroid and DatePickerIOS.
Do they support react-native-web?

**Comment by shamoons** [comment]
Looks like the answer is no?

**Comment by mmazzarolo** [comment]
Mine was an open question, I have no idea id they do 🤷 If they do, we can support it, otherwise nope

**Comment by chansk131** [comment]
According to the documentation, they do support Picker.
https://github.com/necolas/react-native-web

**Comment by theZulqarnain** [comment]
@chansk131 did you implemented, because I'm getting an error
```
Stanclinic/node_modules/react-native-modal-datetime-picker/src/index.js
Module not found: Can't resolve './DateTimePickerModal' in '/Users/abdullazulqarnain/stanplus/projects/Stanclinic/node_modules/react-native-modal-datetime-picker/src' 
```

Please let me know how to solve it.

**Comment by theZulqarnain** [comment]
any update...?

**Comment by mmazzarolo** [comment]
> According to the documentation, they do support Picker.
> https://github.com/necolas/react-native-web

Picker is not the DateTimePicker.

**Comment by theZulqarnain** [comment]
can please update according to this ticket https://github.com/react-native-community/datetimepicker/pull/80 . at least UI won't break

**Comment by mmazzarolo** [comment]
@theZulqarnain , can't right now, but feel free to submit a PR 👍

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/426
