### ISSUE TITLE
iOS: Dismiss animation not work

### ISSUE THREAD

**Issue by dhananjay2011** [mmazzarolo/react-native-modal-datetime-picker#269]
When I dismiss date picker in iOS, Datepicker flickering on screen.

`constructor(props) {
        super(props);
        this.state = {
            isDateTimePickerVisible: false
        };
    }

    showDateTimePicker = () => {
        this.setState({ isDateTimePickerVisible: true });
    };

    hideDateTimePicker = () => {
        this.setState({ isDateTimePickerVisible: false });
    };

    handleDatePicked = date => {
        console.log("A date has been picked: ", date);
        this.hideDateTimePicker();
    };

    render() {
        return (
            <SafeAreaView style={{ flex: 1 }}>
                <View style={styles.mainViewContainer}>
                    <Button title="Show DatePicker" onPress={this.showDateTimePicker} />
                    <DateTimePicker
                        mode='datetime'
                        isVisible={this.state.isDateTimePickerVisible}
                        onConfirm={this.handleDatePicked}
                        onCancel={this.hideDateTimePicker}
                    />
                </View>
            </SafeAreaView>
        )
    }`

**Comment by mmazzarolo** [comment]
Hey! Do you mind following the issue template in its entirety please? Thanks!

**Comment by Bang9** [comment]
@dhananjay2011 try this props
```jsx
<DateTimePicker 
    reactNativeModalPropsIOS={{
        useNativeDriver:true,
        hideModalContentWhileAnimating:true
    }}
/>
```

**Comment by mmazzarolo** [comment]
@Bang9 if the issue is caused by the nativedriver it should be fixed in `v8`.
