### ISSUE TITLE
react-native-animated-modal has been renamed to react-native-modal

### ISSUE THREAD

**Issue by joncursi** [mmazzarolo/react-native-modal-datetime-picker#27]
Yarn produces the following warning:

```
warning react-native-modal-datetime-picker > react-native-animated-modal@1.1.0: This module has been moved to react-native-modal
```

See: https://github.com/react-native-community/react-native-modal#warning

**Comment by mmazzarolo** [comment]
Thanks for the issue but no worries, I'm maintaing react-native-modal too, so I'll update this lib soon :)

**Comment by mmazzarolo** [comment]
Update on version `4.2.0` :)
