### ISSUE TITLE
Migrate to community version

### ISSUE THREAD

**Issue by FDiskas** [mmazzarolo/react-native-modal-datetime-picker#276]
Please migrate to [react-native-community/react-native-datetimepicker](https://github.com/react-native-community/react-native-datetimepicker)
to get latest updates

**Comment by shahzore-qureshi** [comment]
Warning: that new repo does not work with Expo at this time. If you are using Expo, I would suggest holding off on migrating.

**Comment by mmazzarolo** [comment]
@shahzore-qureshi thanks for reporting! Do you know if the issue is already being tracked in the `react-native-datepicker` repo?

**Comment by shahzore-qureshi** [comment]
Hi mmazzarolo. Not yet. However, I will go ahead and do so!
