### ISSUE TITLE
Translation of properties "confirm, cancel and pick a date" on iOS

### ISSUE THREAD

**Issue by francbelak** [mmazzarolo/react-native-modal-datetime-picker#279]
## Platforms

iOS only

## Versions

- iOS: 12.4
- react-native-modal-datetime-picker: ^7.5.0
- react-native: 0.59.2
- react: 16.8.3

## Description

Hi Matteo,

thank you very much for writing this wrapper! I would like to know if it is possible to translate the properties "confirm, cancel and pick a date" from the native iOS datepicker. I have already gone through the "locale" property https://facebook.github.io/react-native/docs/datepickerios and setting it to "de" or "ger" as described here "https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html" did not work for me. I tried setting it to "FR" too, since I saw it working in this screenshot (https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/189#issuecomment-429781116) but this did not work for me.

This issue only targets the labels "pick a date, confirm and cancel". Month names are translated properly in my case.

Thanks!

## Reproducible Demo

```
<DateTimePicker
  isVisible={this.state.isDateTimePickerVisible}
  onConfirm={this._handleDatePicked}
  onCancel={this._hideDateTimePicker}
  mode={this.state.datePickerMode}
  locale='de'
  is24Hour={true}
/>
```

**Comment by mmazzarolo** [comment]
👋 @francbelak , you can pass your own translated strings to the `cancelTextIOS`, `confirmTextIOS` and `titleIOS` props.

**Comment by mbbzrc** [comment]
@mmazzarolo Thanks for the guidance here. I noticed, though, that one of those props is missing from the "Available props" section of the Readme, and that instead of `titleIOS` it is actually called `headerTextIOS`. It would be great if you could add that in the documentation. Much appreciated!
