### ISSUE TITLE
Crashing on Android 9

### ISSUE THREAD

**Issue by arunraj-qburst** [mmazzarolo/react-native-modal-datetime-picker#282]
## Environment
Android: Ver 9
"react-native": "0.59.1"
"react-native-modal-datetime-picker": "^7.5.0"

## Platforms
Android only. Only from Android ver 9

## Versions
Android ver 9

"react-native-modal-datetime-picker": "^7.5.0"
- Android:9
- iOS: Working fine
- react-native-modal-datetime-picker:^7.5.0
- react-native: 0.59.1
- react:16.8.3

## Description
When the component gets rendered, the app got crashed. This is happening only with Android 9+

## Reproducible Demo
Open the component in Android ver 9+

**Comment by mmazzarolo** [comment]
👋 @arunraj-qburst please provide a reproducible example, Android 9 is working fine from the example dir:
<img width="571" alt="Screenshot 2019-09-22 at 11 08 11" src="https://user-images.githubusercontent.com/9536354/65384982-4acf2d80-dd29-11e9-8345-d7cd466177a6.png">

**Comment by arunraj-qburst** [comment]
This issue is happening only if we set the mode as  " mode={'datetime'}"
Also the start and end time has created based on user specific timezone (not just new Date())
------------------------
Code:
```
<DateTimePicker
                      mode={'datetime'}
                      maximumDate={this.state.endDate}
                      minimumDate={this.state.startDate}
                      titleIOS={"choose date"}
                      isVisible={this.state.isDateTimePickerVisible}
                      onConfirm={this.handleDateSelected}
                      onCancel={this.hideDateTimePicker}
                    /> 
```
------------------------
Date calculation:
`new Date(DateFormatter.convertUtcToUserTz(minDateInUTC))`

------------------------
Current behaviour:

1. iOS: Start and end dates are not setting on iPhone 6, version 12.3.1 (need to test other versions as well )
2. Android: Crashing the app from OS ver 9
