### ISSUE TITLE
iOS 13.0 dark mode support

### ISSUE THREAD

**Issue by luisjimenezorozcoGL** [mmazzarolo/react-native-modal-datetime-picker#283]
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 6.44 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.1
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.0 => 0.60.0
  npmGlobalPackages:
    react-native-cli: 2.0.1

iOS 13.0

- Android:
- iOS:
- react-native-modal-datetime-picker:
- react-native:
- react:

![IMG_9855](https://user-images.githubusercontent.com/54149984/65361257-1b50e180-dbc0-11e9-99cf-2300565700ac.jpg)

**Comment by mmazzarolo** [comment]
@luisjimenezorozcoGL have you tried it on the original react-native pickers? (See the issue template)

**Comment by arjunnaha** [comment]
I believe this is a dark mode/light mode issue. While the dates look empty, you can feel the haptic response when scrolling, and switching to light mode brings up the dates again.

**Comment by mmazzarolo** [comment]
@arjunnaha thanks for reporting! I can't test it on iOS13 yet, but I guess this is more of a react-native picker issue than one specific to this current. 
It would also be interesting knowing if the community [`react-native-datetimepicker`](https://github.com/react-native-community/react-native-datetimepicker) solves the issue (#276)
I'm leaving the issue open.

**Comment by RuslanShlinchak** [comment]
@arjunnaha 
I also managed to reproduce this problem on dark theme

**Comment by mohamedabusrea** [comment]
in Dark theme, the text color will be white so it won't be visible with the container white box.

**Comment by PaitoAnderson** [comment]
Just a workaround, but I added this to the `Info.plist` to disable dark mode for now:
```
<key>UIUserInterfaceStyle</key>
<string>Light</string>
```

**Comment by mmazzarolo** [comment]
@PaitoAnderson you might wanna try #288

**Comment by emildancescu** [comment]
> @PaitoAnderson you might wanna try #288

I've tried it, but for some reason even explicitly setting isDarkModeEnabled={true} does not work. The background is still white.

**Comment by mmazzarolo** [comment]
@emildancescu you sure the new version was being picked up by react-native? (you can check it directly in `node_modules`). 
That's weird, setting `isDarkModeEnabled={true}` in the example works for me.

**Comment by emildancescu** [comment]
@mmazzarolo yes, I checked node_modules before writing; I've checked the implementation and I saw nothing wrong. I'll see what I can do.

**Comment by mmazzarolo** [comment]
@emildancescu now the PR is released on npm

**Comment by emildancescu** [comment]
![IMG_4844](https://user-images.githubusercontent.com/2664205/65645461-42fcdb00-e000-11e9-8dd9-5af1bf5d517f.png)
I'm running the app with the Expo client.

**Comment by rxhivzero** [comment]
Now there is the same problem in version 7.6

**Comment by rxhivzero** [comment]
I use appearance fix this

import { Appearance } from 'react-native-appearance'

const colorScheme = Appearance.getColorScheme()
const isDarkModeEnabled = colorScheme === 'dark'

<DateTimePicker
 isDarkModeEnabled={isDarkModeEnabled}
/>

**Comment by mmazzarolo** [comment]
🎈 https://github.com/mmazzarolo/react-native-modal-datetime-picker#is-the-ios-dark-mode-supported

**Comment by Fernando922** [comment]
@PaitoAnderson SOLLLLLLLLLLVEDDDD!! thank you!

**Comment by martabacc** [comment]
I just want to say thank you for this comment, this saved my day. God bless ^^
