### ISSUE TITLE
DatePickerIOS moving to @react-native-community

### ISSUE THREAD

**Issue by Thomazella** [mmazzarolo/react-native-modal-datetime-picker#292]
## Environment

info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 61.37 MB / 16.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.11.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 27, 28
      Build Tools: 23.0.1, 23.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.0, 28.0.3, 29.0.0, 29.0.1
      System Images: android-21 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1

## Platforms

both

## Versions

- Android:
- iOS:
    "react-native-modal-datetime-picker": "^7.5.0",
- react-native:
- react:

## Description

https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/0c7c0cfe7709824bb8601b191946db919ac39e7d/src/CustomDatePickerIOS.js#L4

would have to be imported from community dep instead. 
![Screen Shot 2019-10-02 at 1 13 47 PM](https://user-images.githubusercontent.com/15015324/66061766-7bc41500-e516-11e9-8a2b-dd5b55ebd92d.png)

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/262

**Comment by Thomazella** [comment]
Great! :)

**Comment by mmazzarolo** [comment]
@Thomazella you can now use the new version at #301

**Comment by Thomazella** [comment]
Great!
