### ISSUE TITLE
Can't see dates in iOS

### ISSUE THREAD

**Issue by pedroomedicina** [mmazzarolo/react-native-modal-datetime-picker#294]
## Environment
Expo (?)

## Platforms

iOs

## Versions

- Android: 9
- iOS: 12
- react-native-modal-datetime-picker: 7.6.0
- react-native: Expo sdk 34.0
- react: 16.8.3

## Description

Opening a datetimepicker will show me the modal on both android and iOS, but in iOS i'm not able to see dates nor hours to pick. have been developing a project for two months without a single issue and today I wanted to test a feature that involved interacting with the datetimepicker and encountered myself with this issue.

**Comment by mmazzarolo** [comment]
@pedroomedicina hi! 👋 

This is probably related to the iOS dark mode support.  
Please see the [README](https://github.com/mmazzarolo/react-native-modal-datetime-picker#i-cant-see-the-picker-on-ios--the-picker-is-white-on-ios) and the other related issues:
- #293 
- #283
