### ISSUE TITLE
Platform IOS:  I choose the date in May and April of 1975, it will subtract 1 day

### ISSUE THREAD

**Issue by tunm1228** [mmazzarolo/react-native-modal-datetime-picker#298]
## Versions

- Android:
- iOS:
- react-native-modal-datetime-picker:
- react-native:
- react:

**Comment by whalemare** [comment]
Why this issue is closed without comments? This bug is still reproduced in 9.2.0

**Comment by tunm1228** [comment]
> Why this issue is closed without comments? This bug is still reproduced in 9.2.0

You get this error same me?

**Comment by tunm1228** [comment]
I had to use the solution that was to manually customize the input field according to the date format.

**Comment by mmazzarolo** [comment]
> Why this issue is closed without comments?

Because it didn't follow the issue template. It's clearly stated in the template, when you open an issue, that if it's not followed the issue won't be supported.
