### ISSUE TITLE
v8.0.0 release (@react-native-community pickers support)

### ISSUE THREAD

**Issue by mmazzarolo** [mmazzarolo/react-native-modal-datetime-picker#301]
👋As you may already know, the react-native date and time pickers have recently been moved to a new [`@react-native-community`](https://github.com/react-native-community/react-native-datetimepicker) repository.  

The original react-native date and time pickers (used by `react-native-modal-datetime-picker < 8.0.0`) are now deprecated. 
The `v8` of `react-native-modal-datetime-picker` takes care of this by starting to use the new pickers. 
You can install it by following the instructions on [this branch README](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/next-major/README.md).  

Please notice that there are breaking changes and deprecations, and that we did our best to report them trough yellow warning. 
We also took a chance to remove `react-native-modal` in favour of a lighter solution (that provides the same functionality). 

**Deprecated props**:
A few prop names are going to be changed (the old name will still work for some time though). 
- `titleIOS` → `headerTextIOS`
- `customTitleContainerIOS` → `customHeaderIOS`
- `onHideAfterConfirm` → `onHide`
- `customDatePickerIOS` → `customPickerIOS`

**Breaking changes**:
The following props are not supported anymore:
- `cancelTextStyle` → Please use `customCancelButtonIOS` to override the component instead
- `confirmTextStyle` → Please use `customConfirmButtonIOS` to override the component instead
- `datePickerModeAndroid` → Please use the `display` prop of  `@react-native-community/react-native-datetimepicker` instead
- `dismissOnBackdropPressIOS` → This is now the default behaviour on iOS
- `hideTitleContainerIOS` → Please set `customHeaderIOS` to `null` instead
- `neverDisableConfirmIOS`→ This behaviour was causing a few issues with the new picker
- `pickerRefCb`→ Not supported by the new picker
- `reactNativeModalPropsIOS` → `react-native-modal` is not being used anymore

**If you tested v8 and it worked well for you please add a 👍 to this post.**
**Otherwise, if you've noticed an issue, please report it in a comment below.**
**Thank you! ❤️**

**Comment by Barney4242** [comment]
https://registry.npmjs.org/@react-native-community%2freact-native-datetimepicker
{"error":"Not found"}

**Comment by mmazzarolo** [comment]
@Barney4242 thank you for reporting, I updated the README: it's `@react-native-community/datetimepicker`

**Comment by OshaFoster** [comment]
Hi, I am having an issue on iOS, the dates do not show up on the picker, the rest of the shape is fine. I thought I may be missing a new style object or something. 
Bellow is the component: 
![IMG_5931](https://user-images.githubusercontent.com/31053423/67031188-3aaf3180-f0ce-11e9-9ede-31087dff0adc.jpg)

    <DateTimePickerModal
            isVisible={this.state.hidePicker}
            onConfirm={this.handleDatePicked}
            onCancel={this.hideDatePicker}
            headerTextIOS='EXPIRE DATE'
            date={selectedDateUpper}
            cancelTextStyle={style.cancelTextStyle}
            confirmTextStyle={style.confirmTextStyle}
            titleStyle={style.titleStyle}
            minimumDate={minimumDateUpper}
            maximumDate={maxDateUpper} />

**Comment by mmazzarolo** [comment]
Hey @OshaFoster ! 
That issue is probably caused by the iOS dark mode. 
See the [README](https://github.com/mmazzarolo/react-native-modal-datetime-picker#i-cant-see-the-picker-on-ios--the-picker-is-white-on-ios) for a fix/workaround and the other related issues:
- #293 
- #283 
- #294  
- #296

**Comment by OshaFoster** [comment]
Thanks mmazzarolo, I look through the issues posted. The rest of my app does not support dark mode, I would like to use the picker in light mode only, is there a solution for this, can you point me to it? From what I read it seems like you have to switch it to dark mode to be visible, did I miss something?

**Comment by mmazzarolo** [comment]
@OshaFoster You can use [this solution](https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/296#issuecomment-542212552)

**Comment by pani7** [comment]
I have issue with android mode={'datetime'} after update to version 8.0.0. It opens time picker twice, so first it shows date picker, after confirm it displays time picker and after confirm it diplays time picker again.

**Comment by mmazzarolo** [comment]
@pani7 thanks for reporting, mind showing the code for the picker? The issue sounds similar to another one that was reported last month that I wasn't able to reproduce.

**Comment by pani7** [comment]
Nothing special, just: 

`<DateTimePicker
            isVisible={isDatePickerVisible}
            onConfirm={this.handleDatePicked}
            onCancel={this.toggleDatePicker}
            date={moment().toDate()}
            mode={'datetime'}
          />`

**Comment by pani7** [comment]
Also, i suppose on RN 0.62.1 i do not need to link manually, just npm install both packages and then pod install without updating manually podfile and that is it?

Thanks for fast response

**Comment by mmazzarolo** [comment]
> Also, i suppose on RN 0.62.1 i do not need to link manually, just npm install both packages and then pod install without updating manually podfile and that is it?

That's correct. 

Thanks for reporting the issue, I'll try to investigate a bit more (could you try the example in your own app using `datetime` to see if it works? it does for me)

**Comment by pani7** [comment]
Resolved the issue, for some reason when i was calling 2 asynchronous functions one after other - 1. api call, 2. setState({isDatePickerVisible: false}) -> on click date picker ok, it would dismiss and show again, but when i put api call, as callback to set state it works ok. Strange. On version 7.6.0 version it was working ok. Maybe it is community date picker issue. Anyway thanks for your help

**Comment by mmazzarolo** [comment]
No worries, thanks for reporting back what was causing the issue!

**Comment by mikehardy** [comment]
I just integrated this with my work project via the `@next-major` tag - all seems fine

Might be nice to have a quick migration guide from v7->v8 (I think it's just the yarn dependencies that change? an add for the new one, and a remove for the modal?)

Nice work!

**Comment by mmazzarolo** [comment]
> Might be nice to have a quick migration guide from v7->v8 (I think it's just the yarn dependencies that change? an add for the new one, and a remove for the modal?)

Regarding the dependencies, installing the updated version + the new community pickers is enough (the modal was a built-in dependency, so you don't have to explicitly remove it). This means that the update install is the same as a brand-new installation.  

There are some deprecations and breaking changes that I included at the top of the post, do you think I should highlight them more? (The top post is already linked in the README.md).  

Thanks for the feedback!

**Comment by mikehardy** [comment]
> This means that the update install is the same as a brand-new installation.

That explains why I couldn't find any part to remove :-), excellent I'm all set then and the docs seem fine as well then

> 
> There are some deprecations and breaking changes that I included at the top of the post, do you think I should highlight them more? (The top post is already linked in the README.md).

No - I thought the call-out for breaking changes was in a good spot and seemed fine to me

Cheers

**Comment by itaygolbary** [comment]
Hey,
Can't figure out this error:

> Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePickerAndroid.open'

refrence to `@react-native-community\datetimepicker` liabrary.

installed and linked `react-native-modal-datetime-picker` and `@react-native-community/datetimepicker`

what am i doing wrong?

**Comment by mmazzarolo** [comment]
@itaygolbary does using the [datetimepicker](https://github.com/react-native-community/react-native-datetimepicker) alone work?

**Comment by itaygolbary** [comment]
> @itaygolbary does using the [datetimepicker](https://github.com/react-native-community/react-native-datetimepicker) alone work?
> Also, did you reset your metro server and reinstalled the app after installing the datetimepicker?

Tried `react-native-modal-datetime-picker` alone, although the version was 8.0.1. Do you think I should try v7?

Forgot to mentioned I'm using expo and my android device.

**Comment by mmazzarolo** [comment]
> Tried react-native-modal-datetime-picker

You should try the [datetimepicker from the community](https://github.com/react-native-community/react-native-datetimepicker).  

> Forgot to mentioned I'm using expo and my android device.

🤔 hm... I guess that's probably what is causing the issue. 
I took a quick look at the Expo planning and it looks like the community datetimepicker [will be added on SDK36](https://expo.canny.io/feature-requests/p/add-react-native-datetimepicker-module-to-expo).   The current one seems to be SDK35.

**Comment by itaygolbary** [comment]
So this one too, thought it was referring to a different library. Thanks.

**Comment by kaisv7n** [comment]
Please take a look at line 49 in file DateTimePickerModal.android.js. You need use getDate() instead of getDay(). It return wrong date when I use datetime mode in android. getDay func to get day of week, no get day of month.

**Comment by mmazzarolo** [comment]
Nice catch @kaisv7n , thanks!

**Comment by thabemmz** [comment]
What should be the correct usage of `customCancelButtonIOS` and `customConfirmButtonIOS`? In v7 and the Typescript and PropType definitions it states it should contain a `node` / `JSX.Element`, though the code and the documentation state that it should contain a `Component`.

Though I expect this to be a typing issue, I'd like to verify this before filing a PR.

**Comment by mmazzarolo** [comment]
@thabemmz yeah, I think we're just using the wrong terminology somewhere. 
You can see from [here](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/41b0853465fe5e18fe349d95d10f0f816d581c3b/src/DateTimePickerModal.ios.js#L162) that they should be React components (classes/functions). They should **not** be instances of components.

**Comment by thabemmz** [comment]
@mmazzarolo PR can be found with the link above.

**Comment by mmazzarolo** [comment]
merged! thank you

**Comment by addingama** [comment]
@mmazzarolo The cancel or confirm button cannot be clicked on v.8.0.3


<img width="554" alt="image" src="https://user-images.githubusercontent.com/2896774/69197607-e08e0a00-0b6c-11ea-992c-0f0f6a58380f.png">


<img width="341" alt="image" src="https://user-images.githubusercontent.com/2896774/69197625-f3a0da00-0b6c-11ea-947e-45ee9e4b50d3.png">

**Comment by mikehardy** [comment]
@addingama strangely it's working for me though when I integrated it I did notice an oddity I couldn't pin down https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/262#issuecomment-536017873 - I'm definitely using 8.0.3 with success on android+ios dark mode or not

**Comment by mmazzarolo** [comment]
@addingma I'm curious, could you try refactoring your cancel `onPress` by moving the callback in a class method?

e.g.:
```js
handleCancel = () => {
  if (this.props.onNext) this.props.onNext();
}
```

**Comment by chakrihacker** [comment]
@addingama can you try withou Debug JS Remotely, I had the same issue

**Comment by mmazzarolo** [comment]
@mikehardy FYI I think the issues you had in #262 might be related to https://github.com/react-native-community/react-native-datetimepicker/issues/54

**Comment by chakrihacker** [comment]
@mmazzarolo can we add to README stating to hide picker first and do rest of the stuff🤔🤔🤔

**Comment by mmazzarolo** [comment]
@chakrihacker 🤔 you mean as a workaround for the datetimepicker issue that I posted? Can you confirm that the issue is there?
(I just pinged the author of that lib)

**Comment by chakrihacker** [comment]
Yes, issue 54 where picker appears twice and it's happening when the mode is time or date also. I tried to reproduce in the fresh app but not able to do it. In my case I am calling prop which triggers render with state visible true and then second render with state visible false

```
handleConfirm = (date) => {
	if(someBool) {
		this.props.someRandomeProp(date)
	}
	if(anotherBool) {
		this.props.anotherProp(date)
	}	
	this.setState({visible: false})
		
}
```

My function is something like this with few conditionals
and if I do setState first and then call props the issue will not occur

**Comment by ali-hellani** [comment]
When i change date and click cancel and then reopen the picker the default value is the last changed one, is there an option to make the picker shows every time the initial value i gave to it?

**Comment by mmazzarolo** [comment]
> When i change date and click cancel and then reopen the picker the default value is the last changed one, is there an option to make the picker shows every time the initial value i gave to it?

iOS/Android? does it also happen if you directly use the community picker? https://github.com/react-native-community/react-native-datetimepicker

**Comment by arnaultBreuil** [comment]
Hi mmazzarolo, thank you for your work.
Just to let you know, i had an issue with the v8, with multiple datepicker.
I have a startTime and endTime, and when the startTime is modified, i have to keep the interval between those dates, and update on the fly the endTime.
My issue was that the endTime was modified in my store, but the component kept the old value when the datepicker modal was opened. I tried many things, and finally i had to revert to the current stable version

**Comment by mmazzarolo** [comment]
hey @arnaultBreuil : Android/iOS? Are you able to share a reproducible repo?

**Comment by arnaultBreuil** [comment]
[test.zip](https://github.com/mmazzarolo/react-native-modal-datetime-picker/files/3927480/test.zip)

Here are the 2 files concerned. I do not know if it is of any use.

**Comment by MarioSilvaPrada** [comment]
Hey mmazzarolo, thanks for your amazing work!
After this update I am with an issue on Android where I cant get the confirm and cancel buttons:
![image](https://user-images.githubusercontent.com/35892161/70737296-22444780-1d0a-11ea-9440-e2b59cb03d3a.png)

Code:
`<InputContainer
            datepicker
            isVisible={isDatePickerVisible}
            mode="date"
            label="Date"
            minimumDate={today}
            onPress={() => this.handleDateTimePicker('date')}
            onConfirm={(newDate) => this.handleDatePicked(newDate, 'date')}
            onCancel={() => this.hideDateTimePicker('date')}
            dateTimeSelect={date}
            style={{ marginRight: 40 }}
          />`
(InputContainer tag here results in DateTimePicker tag)

Thank you,
Mário

**Comment by mmazzarolo** [comment]
@MarioSilvaPrada does it also happen if you directly use the community picker? https://github.com/react-native-community/react-native-datetimepicker

`react-native-modal-datetime-picker` is not changing the picker behaviour on Android, so it could be a problem of the library used underneath :/

**Comment by MarioSilvaPrada** [comment]
@mmazzarolo apparently the buttons are there if you look closely. The color of the font is almost the same as the background. Do we have any way to change this color?

**Comment by mmazzarolo** [comment]
@MarioSilvaPrada `react-native-modal-datetime-picker` is not changing the style of the picker. Please try using directly the community pickers (https://github.com/react-native-community/react-native-datetimepicker) to see if the issue is persists.

**Comment by Alex-Bond** [comment]
@mmazzarolo hi! Can you please merge my last PR (export props) into 8.*.* branch as well?

**Comment by mmazzarolo** [comment]
@Alex-Bond done! Available in `v8.0.4`

**Comment by mmazzarolo** [comment]
Expo SDK 36 is not available. Can anyone test it?

**Comment by mmazzarolo** [comment]
Just a quick update.
I'm on vacation, but @brentvatne and @satya164 had a chance to give v8 on Expo SDK36 (the version which includes the community pickers) a try and it seems to be working fine (thanks 🙏!) 
Once I'm back from vacation I'll test and prepare the release:
https://twitter.com/notbrent/status/1210748246148046848

Again, thanks to everyone who contributed, helped and tested it so far 🙌

**Comment by brentvatne** [comment]
@mmazzarolo - might be worth updating the readme to suggest `expo install react-native-modal-datetime-picker @react-native-community/datetimepicker` when using `expo-cli` because this will pick the compatible version of datetimepicker :)

**Comment by simonasdev** [comment]
`customConfirmButtonIOS`, `customCancelButtonIOS`, `customHeaderIOS` and `customPickerIOS` props are typed incorrectly. `React.ComponentType` accepts type parameter for Props, which should be specified because it is clearly defined what kind of props are being passed to these components: https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/next-major/src/DateTimePickerModal.ios.js#L195, https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/next-major/src/DateTimePickerModal.ios.js#L201, https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/next-major/src/DateTimePickerModal.ios.js#L187, https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/next-major/src/DateTimePickerModal.ios.js#L189.
So for example `customConfirmButtonIOS` should be typed something like `React.ComponentType<{ isDisabled: boolean, onPress: (event: GestureResponderEvent) => void, label: string }>`. Ideally it could be a separate interface which would be used by our custom components

**Comment by simonasdev** [comment]
As of now I'm getting `Type '({ isDisabled, label, ...props }: ButtonProps) => JSX.Element' is not assignable to type 'FunctionComponent<{}>'.` or `Type 'FC<ButtonProps>' is not assignable to type 'FunctionComponent<{}>`

**Comment by mmazzarolo** [comment]
> @mmazzarolo - might be worth updating the readme to suggest `expo install react-native-modal-datetime-picker @react-native-community/datetimepicker` when using `expo-cli` because this will pick the compatible version of datetimepicker :)

Done, thanks!

@simonasdev thanks for the reporting... wanna tackle it with a PR? that would be great :D

**Comment by simonasdev** [comment]
sure, the PR should target `next-major` branch, right?

**Comment by mmazzarolo** [comment]
@simonasdev yes! Thank you!

**Comment by eightyfive** [comment]
Just a heads up. [`@react-native-community/datetimepicker`](https://github.com/react-native-community/react-native-datetimepicker) does not seem to support non-AndroidX projects (`react-native < 0.60`):
https://github.com/react-native-community/react-native-datetimepicker/issues/11

**Comment by mikehardy** [comment]
@eightyfive I'd be surprised if that was actually the case, though if you want to stay on support libraries at this point you've got to get savvy with jetifier in reverse mode 

https://github.com/mikehardy/jetifier#to-reverse-jetify--convert-node_modules-dependencies-to-support-libraries

**Comment by Phillip-Cognativ** [comment]
Awesome work! Works great for me.

Only issue I found is this work around for hiding the title container on IOS:
> * `hideTitleContainerIOS` → Please set `customHeaderIOS` to `null` instead

The header is determined with the following lines (165-166 in `DateTimePickerModal.ios.js`):
```
const HeaderComponent =
    customTitleContainerIOS || customHeaderIOS || Header;
```

So setting customHeaderIOS to null does not remove the header as null is a falsy value and the HeaderComponent will resolve to the default Header anyway

**Comment by AnasAlamin** [comment]
the component is no longer working ios, any new updates?

**Comment by mmazzarolo** [comment]
@AnasAlamin what do you mean? Mind adding some more details?

**Comment by mmazzarolo** [comment]
v8 is not out of beta :) Thanks to anyone who contributed to it!

**Comment by zain148** [comment]
@mmazzarolo  Sir, I have thoroughly readout all of Issues Created then SomeOne In above have same issue that I'm faCing right now.
I have CorreCtly installed this library in my expo project  using
expo install react-native-modal-datetime-picker @react-native-community/datetimepicker v8.1
And i'm using SDK35 right now with 
Can't figure out this error:

Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePickerAndroid.open'

**Comment by mmazzarolo** [comment]
@zain148 , `react-native-modal-datetime-picker` v8 works only on Expo SDK36. 
If you can't upgrade you can still use v7 though.

**Comment by zain148** [comment]
@mmazzarolo  In above bugs someOne asked you to fixed an error in v7 probably it was getDay in DateTimePickerAndroid.js 
Is't resolved for v7 for now?

**Comment by mmazzarolo** [comment]
@zain148 please check the [release](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases) page to see the current state of the release. 
Please notice that from now on only > v8 will be actively supported/maintained.

**Comment by zain148** [comment]
@mmazzarolo Thanks For Your kind Response!

**Comment by AKKIDETROJA** [comment]
**_In info.plist file add this lines_**

<key>UIUserInterfaceStyle</key>
<string>Light</string>

**Comment by smriti-spotnana** [comment]
I have started getting this error now -
1- not using expo, using android sdk emulator
2- "@react-native-community/datetimepicker": "^2.4.0",
    "react-native-modal-datetime-picker": "^8.6.0"
3- and the datepicker (mode="date") doesn't show up on button click

```
Possible Unhandled Promise Rejection (id: 1):
TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePickerAndroid.open')
open$@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:153696:96
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:26952:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27128:32
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:26952:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27028:30
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27058:19
tryCallTwo@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:28899:9
doResolve@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:29063:25
Promise@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:28922:14
callInvokeWithMethodAndArg@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27057:33
enqueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27062:157
async@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27079:69
open@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:153690:42
RNDateTimePicker@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:153532:60
renderWithHooks@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:16140:33
mountIndeterminateComponent@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:18335:34
beginWork$$1@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:23958:31
performUnitOfWork@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:23107:30
workLoopSync@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:23089:45
performSyncWorkOnRoot@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:22784:29
performSyncWorkOnRoot@[native code]
```

**Comment by abdulghanitech** [comment]
> I have started getting this error now -
> 1- not using expo, using android sdk emulator
> 2- `"@react-native-community/datetimepicker": "^2.4.0", "react-native-modal-datetime-picker": "^8.6.0"`
> 3- and the datepicker (mode="date") doesn't show up on button click
> 
> ```
> Possible Unhandled Promise Rejection (id: 1):
> TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNDatePickerAndroid.open')
> open$@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:153696:96
> tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:26952:23
> invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27128:32
> tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:26952:23
> invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27028:30
> http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27058:19
> tryCallTwo@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:28899:9
> doResolve@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:29063:25
> Promise@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:28922:14
> callInvokeWithMethodAndArg@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27057:33
> enqueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27062:157
> async@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27079:69
> open@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:153690:42
> RNDateTimePicker@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:153532:60
> renderWithHooks@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:16140:33
> mountIndeterminateComponent@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:18335:34
> beginWork$$1@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:23958:31
> performUnitOfWork@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:23107:30
> workLoopSync@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:23089:45
> performSyncWorkOnRoot@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:22784:29
> performSyncWorkOnRoot@[native code]
> ```

same issue here!

**Comment by mikehardy** [comment]
@abdulghanitech Classic failure to correctly link in the native module, could be for a variety of reasons, but is project-specific

**Comment by abdulghanitech** [comment]
> @abdulghanitech Classic failure to correctly link in the native module, could be for a variety of reasons, but is project-specific

I had to edit the datepicker.android.js file. It was having RNDatePicker.open had to change it to DatePicker.open (similiar method)

I don't remember the exact line numbers but this what I had to do to get it running!

**Comment by mikehardy** [comment]
@abdulghanitech that sounds like a much much more serious issue, if the underlying object names changed - could you open a new issue? Also, you may want to use https://github.com/ds300/patch-package to persist your change locally if you've never seen patch-package before

**Comment by abdulghanitech** [comment]
> @abdulghanitech that sounds like a much much more serious issue, if the underlying object names changed - could you open a new issue? Also, you may want to use https://github.com/ds300/patch-package to persist your change locally if you've never seen patch-package before
> 

Yes! I've used patch-package for persisting my local changes 🙌🏻. 
Sure, I'll open a new issue.

**Comment by mmazzarolo** [comment]
> I had to edit the datepicker.android.js file. It was having RNDatePicker.open had to change it to DatePicker.open (similiar method)

There's no trace of `RNDatePicker.open` in [`DateTimePickerModal.android.js`](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/DateTimePickerModal.android.js) 🤔 ... also, `datepicker.android.js` is the name the file had before v8... so I guess it's something that didn't work correctly during the npm/yarn update of the component

**Comment by mikehardy** [comment]
`npx react-native-clean-project` and try again is my goto there

**Comment by avenyproduction** [comment]
> 👋As you may already know, the react-native date and time pickers have recently been moved to a new [`@react-native-community`](https://github.com/react-native-community/react-native-datetimepicker) repository.
> 
> The original react-native date and time pickers (used by `react-native-modal-datetime-picker < 8.0.0`) are now deprecated.
> The `v8` of `react-native-modal-datetime-picker` takes care of this by starting to use the new pickers.
> You can install it by following the instructions on [this branch README](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/next-major/README.md).
> 
> Please notice that there are breaking changes and deprecations, and that we did our best to report them trough yellow warning.
> We also took a chance to remove `react-native-modal` in favour of a lighter solution (that provides the same functionality).
> 
> **Deprecated props**:
> A few prop names are going to be changed (the old name will still work for some time though).
> - `titleIOS` → `headerTextIOS`
> - `customTitleContainerIOS` → `customHeaderIOS`
> - `onHideAfterConfirm` → `onHide`
> - `customDatePickerIOS` → `customPickerIOS`
> 
> **Breaking changes**:
> The following props are not supported anymore:
> 
> * `cancelTextStyle` → Please use `customCancelButtonIOS` to override the component instead
> * `confirmTextStyle` → Please use `customConfirmButtonIOS` to override the component instead
> * `datePickerModeAndroid` → Please use the `display` prop of  `@react-native-community/react-native-datetimepicker` instead
> * `dismissOnBackdropPressIOS` → This is now the default behaviour on iOS
> * `hideTitleContainerIOS` → Please set `customHeaderIOS` to `null` instead
> * `neverDisableConfirmIOS`→ This behaviour was causing a few issues with the new picker
> * `pickerRefCb`→ Not supported by the new picker
> * `reactNativeModalPropsIOS` → `react-native-modal` is not being used anymore
> 
> **If you tested v8 and it worked well for you please add a 👍 to this post.**
> **Otherwise, if you've noticed an issue, please report it in a comment below.**
> **Thank you! ❤️**

Link to the Readme file is broken, can you please update with working one?
