### ISSUE TITLE
Splitting Time and Date 

### ISSUE THREAD

**Issue by MHaseebKhalid** [mmazzarolo/react-native-modal-datetime-picker#302]
Hot to split Time and date ?????

**Comment by MHaseebKhalid** [comment]
How to split Date and Time while using mode="datetime" to store both value in DB but want to show them separately
?

**Comment by mmazzarolo** [comment]
Hey @MHaseebKhalid , this is actually more of a JS question for StackOverflow: it's not specifically related to `react-native-modal-datetime-picker`, and it depends on how you're storing the date in the DB.
