### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Barney4242** [mmazzarolo/react-native-modal-datetime-picker#303]
## How to install the latest version

I try 'yarn add react-native-modal-datetime-picker@latest @react-native-community/datetimepicker'

But in terminal I see the following:
Success Saved 2 new dependencies.
info Direct dependencies
├─ @react-native-community/datetimepicker@2.1.0
└─ react-native-modal-datetime-picker@7.6.0
info All dependencies
├─ @react-native-community/datetimepicker@2.1.0
└─ react-native-modal-datetime-picker@7.6.0
✨  Done in 8.61s.

What I'm doing wrong?

Thank you very much!

**Comment by mmazzarolo** [comment]
@Barney4242 hey! 
You're right, `@latest` seems to not install version 8. 
I updated the README:
```bash
# using npm
$ npm i react-native-modal-datetime-picker@8.x.x @react-native-community/datetimepicker

# using yarn
$ yarn add react-native-modal-datetime-picker@8.x.x @react-native-community/datetimepicker
```

Let me know if it works! If it doesn't, add your feedbacks to #301
