### ISSUE TITLE
issues with linking

### ISSUE THREAD

**Issue by KhushbuThakkar** [mmazzarolo/react-native-modal-datetime-picker#305]
Unable to resolve "./CustomDatePickerAndroid" from "node_modules\react-native-modal-datetime-picker\src\index.js"
Failed building JavaScript bundle.

Is it linking issue? 

## Versions

- Android:
- iOS:
- react-native-modal-datetime-picker:
- react-native:
- react:

**Comment by mmazzarolo** [comment]
Hey @KhushbuThakkar 👋 
please follow the issue template before submitting an issue, thank you!

**Comment by hugopretorius914** [comment]
I have this same issue

**Comment by boraerbasoglu** [comment]
i have this same issue too ? any solution ?

**Comment by sistemasjhdez** [comment]
Estoy trabajando con expo sdk 37.0.0 y me apareció el mismo error. La solución la encontré en la pagina de npm [https://www.npmjs.com/package/react-native-modal-datetime-picker]. Ahí aparecia la opcion de instalar con expo, mientras que lo estaba haciendo con npm. Los pasos que segui fueron:

1 npm uninstall @react-native-community/datetimepicker
2 npm uninstall react-native-modal-datetime-picker
3 rm -rf node_modules
4 npm i
5 expo install react-native-modal-datetime-picker @react-native-community/datetimepicker

Espero les sirva. Saludos.
