### ISSUE TITLE
Can't see the date in release mode. Can hear the scrolling sound.

### ISSUE THREAD

**Issue by kasback** [mmazzarolo/react-native-modal-datetime-picker#308]
Hello, in the release mode in ios, the modal works fine in the emulator, but in my device ( iphone 6S ios 13) the dates are invisible in the modal, pressing the confirm button does pick the invisible date and i can hear the scrolling sound.

**Comment by thiagoferolla** [comment]
This is probably related to dark mode. There's a workaround in the [README](https://github.com/mmazzarolo/react-native-modal-datetime-picker#i-cant-see-the-picker-on-ios--the-picker-is-white-on-ios) or you can see related issues: 
#283
#294  
#296

**Comment by mmazzarolo** [comment]
Thanks @thiagoferolla !
Should I highlight it at the top of the README.md until it gets fixed by RN?

**Comment by thiagoferolla** [comment]
I don't think that's actually an React Native issue. It seems to be related to how the modal-datepicker is made. In iOS 13 dark mode, the system datepicker font is white for the selected date ,which is the color of this library's modal,  so we're unable to see.

**Comment by mmazzarolo** [comment]
@thiagoferolla https://github.com/facebook/react-native/issues/26299

**Comment by mmazzarolo** [comment]
basically, for now there are two solutions:
- force the light mode 
- show the picker color based on the OS color theme: unfortunately `react-native-modal-datetime-picker` for now can't do it without some manual changes (see the README.md) because react-native is not exposing (yet) a way to check the theme color
