### ISSUE TITLE
how can I change lang？

### ISSUE THREAD

**Issue by skyworld** [mmazzarolo/react-native-modal-datetime-picker#31]
I want to change English to chinese， how？

**Comment by mmazzarolo** [comment]
Hi @skyworld, 
this component uses React-Native's Android TimePicker/DatePicker APIs under the hood, and as far as I know the language of the pickers are handled by the language set on the device.

**Comment by mmazzarolo** [comment]
Hints on picker languages: https://github.com/facebook/react-native/issues/12405

**Comment by dungnguyen10989** [comment]
I tested origin Lib: PickerIOS on 2 devices, 1 on ios 9.3 and 1 on ios 12.0.
On 9.3 version, picker language will change when device language change but on 12.0 version it is not. I don't know what is reason and how to fix it ?

**Comment by kquoc887** [comment]
locale props not working on android ?
