### ISSUE TITLE
user must check minutes picker and select value incase pass minuteInterval prop,

### ISSUE THREAD

**Issue by mustafaskyer** [mmazzarolo/react-native-modal-datetime-picker#310]
## Ask your Question
user must check minutes picker and select value incase pass minuteInterval prop,

```js
<DateTimePicker
      isVisible={props.isVisible}
      onConfirm={onConfirm}
      onCancel={onCancel}
      minuteInterval={10}
      minimumDate={new Date()}
      date={props.date}
      mode={datetime}
     ... />
```
if user dosen't change the minutes picker,  got the current minute as a result,
i want to make sure that user must select minute from picker

**Comment by mmazzarolo** [comment]
You can force the picker to stay open by checking the date in “onConfim”, hiding the picker only if the date suits your use case.
