### ISSUE TITLE
Change picker Text color on iOS

### ISSUE THREAD

**Issue by dharmrajacharya** [mmazzarolo/react-native-modal-datetime-picker#311]
How to change picker text color on iOS.
![Screenshot 2019-10-29 at 11 10 58 AM](https://user-images.githubusercontent.com/15356248/67740746-e6e10880-fa3c-11e9-9bdf-e8707847f640.png)

**Comment by mmazzarolo** [comment]
👋 As far as I know you can't change the picker color. 
You might wanna ask for more details to [the datetimepicker repo](https://github.com/react-native-community/react-native-datetimepicker) or, even better, on StackOverFlow

**Comment by dharmrajacharya** [comment]
Thanks for replay @mmazzarolo 
I have made some changes to the core library its works for me but is not a good idea.
https://github.com/facebook/react-native/pull/10356/files/8eaa4c438e61362cd2f2f651e4e5b8838c72a58f
