### ISSUE TITLE
iOS dark mode the default style is white on white.

### ISSUE THREAD

**Issue by vlenoach** [mmazzarolo/react-native-modal-datetime-picker#313]

**Comment by vlenoach** [comment]
On iOS dark mode the default style of the selector is a white background with white text. Can a property be added to alter the date selector text color along with making the default style in dark mode a black background with white text.

**Comment by mmazzarolo** [comment]
This is related to the iOS dark mode support.  
Please see the [README](https://github.com/mmazzarolo/react-native-modal-datetime-picker#i-cant-see-the-picker-on-ios--the-picker-is-white-on-ios) for a fix/workaround and the other related issues:
- #293 
- #283 
- #294  
- #296
