### ISSUE TITLE
picker v7 doesn't work on IOS

### ISSUE THREAD

**Issue by duanyachao** [mmazzarolo/react-native-modal-datetime-picker#315]
## Ask your Question
RN version:0.44
react-native-modal-datetime-picker : v7.6
when i use the picker on IOS there is no error but don't show , for it show or hide  by the action  this.setState({ startDateTimePickerVisible: true });  though  isVisible={this.state.startDateTimePickerVisible}, so i config the isVisible={true}, and . reload it's work........ i lost my mind. Can anyone help  me 

@mmazzarolo

**Comment by leon2835** [comment]
Have you call any function to trigger the setState? e.g

showModal(){
this.setState({
    startDateTimePickerVisible:true
})
}

<TouchableOpacity onPress={()=>this.showModal()}>
      <Text>Show date picker</Text>
</TouchableOpacity>

//Put this under
 <DateTimePicker
            isVisible={this.state.isDateTimePickerVisible}
            onConfirm={date => {
            //set your date
            }}
            onCancel={() => {
              this.setState({ isDateTimePickerVisible: false });
            }}
          />

**Comment by mmazzarolo** [comment]
👋 @duanyachao please follow the issue template before submitting a new issue. Thank you!

**Comment by thitoo** [comment]
i have the same issue help me please
