### ISSUE TITLE
App crashes on minimumDate

### ISSUE THREAD

**Issue by arabscimitar** [mmazzarolo/react-native-modal-datetime-picker#32]
Setting minimum date crash app
```javascript
<DateTimePicker
    isVisible={this.state.isDateTimePickerVisibleTo}
    onConfirm={this._handleDatePickedTo}
    onCancel={this._hideDateTimePickerTo}
    minimumDate={this.state.dateFrom}
    maximumDate={new Date()}
     />
```
this.state.dateFrom cames from another date picker
and the code was working before when I commented minimumDate every thing works fine

**Comment by mmazzarolo** [comment]
Hi!
What version of RN are you using? Does the bug happens on both iOS and Android?  
It sounds more like a bug of react-native's own pickers, could you try to use them and see if they work correctly?  
Thanks!

**Comment by arabscimitar** [comment]
Hi,
I use react native 0.43.3
it crashes on both android and ios
when i setted datePickerModeAndroid as spinner works fine on android 
also the datePicker android works fine with both calendar and spinner with minDate
I didn't try it yet on ios after i setted datePickerModeAndroid

**Comment by stephanedemotte** [comment]
same here on 0.43.4

<img width="367" alt="screen shot 2017-04-27 at 08 13 28" src="https://cloud.githubusercontent.com/assets/2158130/25482865/8ad226ba-2b21-11e7-82f4-f26dec572e3e.png">

**Comment by mmazzarolo** [comment]
Does the following example work for you?  
Here I'm setting `minimumDate` with the last picked date from the picker and it is working fine for me (iOS).  🤔 
  
```javascript
import React, { Component } from 'react';
import { Text, TouchableOpacity, View } from 'react-native';
import DateTimePicker from 'react-native-modal-datetime-picker';
import styles from './app.style';

export default class DateTimePickerTester extends Component {
  state = {
    isDateTimePickerVisible: false,
    minimumDate: new Date(),
  };

  _showDateTimePicker = () => this.setState({ isDateTimePickerVisible: true });

  _hideDateTimePicker = () => this.setState({ isDateTimePickerVisible: false });

  _handleDatePicked = date => {
    console.log('A date has been picked: ', date);
    // Setting the minimumDate as the last picked date
    this.setState({ minimumDate: date });
    this._hideDateTimePicker();
  };

  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={this._showDateTimePicker}>
          <View style={styles.button}>
            <Text>Show DatePicker</Text>
          </View>
        </TouchableOpacity>
        <DateTimePicker
          isVisible={this.state.isDateTimePickerVisible}
          onConfirm={this._handleDatePicked}
          onCancel={this._hideDateTimePicker}
          minimumDate={this.state.minimumDate}
        />
      </View>
    );
  }
}
```

**Comment by arabscimitar** [comment]
Try with setting maximumDate with minimumDate

**Comment by arabscimitar** [comment]
my code works on ios and android  after i setted datePickerModeAndroid as spinner

**Comment by mmazzarolo** [comment]
> Try with setting maximumDate with minimumDate  

I did, it's working fine.  

> my code works on ios and android after i setted datePickerModeAndroid as spinner  

That's weird, because `datePickerModeAndroid` is not even checked by iOS, maybe it was a caching issue?

**Comment by arabscimitar** [comment]
My code still gives error when I remove datePickerModeAndroid on android and ios
but I can't reproduce and I tried Your code is working fine
I tried it with resetting minimumDate dynamically and also work fine
so thank You a lot if You want You can close this issue

**Comment by mmazzarolo** [comment]
Feel free to re-open if you'll be able to reproduce it!

**Comment by lavarajallu** [comment]
Hello, @arabscimitar Actually I am  using this module .
My  ```
"react": "16.0.0-alpha.12",
       "react-native": "0.46.1",

```
But, **you are saying that to change react-native version 0.43.3**. But I am using another module **urban airship But it's accepts  react-native-version>= 0.44.0,**
what can I do But i want to show an ,
datePickerModeAndroid={'spinner'}

**Comment by arabscimitar** [comment]
i could not reproduce i am not sure why it is happens

**Comment by lavarajallu** [comment]
But I want Spinner Mode in android but it shows default mode

**Comment by mubashiralisiddiqui** [comment]
Need to reopen this issue as its still persist

Having the same issue only on Android with mode "date"
if you  try to add the minimumDate props with mode "date" on android App is crashed 
working fine on Ios and also working fine with other mode like datetime,time

this will only happen if we passed minimumDate prop on date mode (Android)

   "react-native-modal-datetime-picker": "^9.0.0",
     "react-native": "0.63.3",
