### ISSUE TITLE
Expo: Unable to force light mode to datepicker component

### ISSUE THREAD

**Issue by Joaaofiilho** [mmazzarolo/react-native-modal-datetime-picker#320]
## Environment

System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 986.64 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

## Platforms

iOS

## Versions

iPad OS (13.1.1) and iOS 13+

## Description

The text changes to white while the background maintains the white color.

![Captura de Tela 2019-12-12 às 19 51 42](https://user-images.githubusercontent.com/26173202/70755521-e94aa980-1cee-11ea-88d8-ee8b07d7bd02.png)

## Reproducible Demo

Just let isDarkModeEnabled as false (default)

**Comment by Riseley** [comment]
I confirm the bug and successfully reproduced it. Texts are white when phone is set to Dark Mode, yet background continues to be white, making it unreadable.

Screenshot when point to today's date:
![Screenshot from 2019-12-13 14-10-01](https://user-images.githubusercontent.com/8508355/70770830-55421600-1db2-11ea-8e3a-093f893106b3.png)

Screenshot after moving it around and go over "maximum" or "minimum" date:
![Screenshot from 2019-12-13 14-09-41](https://user-images.githubusercontent.com/8508355/70770847-64c15f00-1db2-11ea-87bb-0c001e4f59a6.png)

**Comment by Riseley** [comment]
https://github.com/expo/expo/issues/5897

**Comment by Riseley** [comment]
Seems like it is an issue of the underlying library in V7, don't know if it affects the new V8 library.

**Comment by mmazzarolo** [comment]
> Seems like it is an issue of the underlying library in V7, don't know if it affects the new V8 library.

V8 library is not compatible with Expo SDK35, we’re waiting for Expo SDK36.
