### ISSUE TITLE
Change year order?

### ISSUE THREAD

**Issue by abjacs** [mmazzarolo/react-native-modal-datetime-picker#329]
## Can we change the order of any picker items?

Really enjoy this component! Very easy to use. I'd like to swap the order of the Year in the Picker such that scrolling down reveals Years in DESCENDING order.

For example, when entering a **Date Of Birth** in a mobile app, it's common that the Year is before the current year. So...flipping the order of the picker would be ideal.

![Screen Shot 2019-12-19 at 3 49 40 PM](https://user-images.githubusercontent.com/982125/71212703-748be800-2277-11ea-87fa-161dfcf64492.png)

**Comment by mmazzarolo** [comment]
Hey @abjacs 👋 
Unfortunately this is something that can't be controlled by this component, you should check the library used underneath it (the original RN pickers or the community ones for the V8 for this component).  
Spoiler alert: I don't think it's doable :/
