### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by Haper** [mmazzarolo/react-native-modal-datetime-picker#334]
Two warnings when I use the component with RN 0.61:
 - Warning: DatePickerIOS has been merged with DatePickerAndroid and will be removed in a future release. It can now be installed and imported from '@react-native-community/datetimepicker' instead of 'react-native'. See https://github.com/react-native-community/react-native-datetimepicker

- Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

## Platforms
iOS

## Versions
- iOS: 13
- react-native-modal-datetime-picker: - ^7.6.1
- react-native: 0.61.4
- react: 16.9.0

**Comment by mmazzarolo** [comment]
@Haper will be fixed by #301
