### ISSUE TITLE
Doesn't display scroll wheels when using Expo on actual iPhone

### ISSUE THREAD

**Issue by mercurjl** [mmazzarolo/react-native-modal-datetime-picker#335]
## Environment

Expo on iPhone 7 plus

## Platforms

iOS

## Versions

- iOS on phone: 13.3
- iOS on Expo: 12.4
- react-native-modal-datetime-picker: ^7.6.1
- react-native: 35.0.0
- react: 16.8.3

## Description

The date picker works on both and iPhone Xr and iPhone 7+ in the emulator with Expo, but when I open the app up in Expo on my actual device, which is an iPhone 7+ the selector wheels don't render. I'll attach screen shots of what this looks like:

![File_001](https://user-images.githubusercontent.com/10855137/71705172-409edf80-2dac-11ea-9563-b078ec050251.png)

And here it is rendering fine in the emulator:
![Screen Shot 2020-01-02 at 10 03 09 PM](https://user-images.githubusercontent.com/10855137/71705184-54e2dc80-2dac-11ea-8eeb-1f61f6d422f1.png)

**Comment by mmazzarolo** [comment]
👋 @mercurjl please see [the README.md](https://github.com/mmazzarolo/react-native-modal-datetime-picker#i-cant-see-the-picker-on-ios--the-picker-is-white-on-ios)

**Comment by ayeshasaeed94** [comment]
This is happening because of dark mode. Either disable dark mode in your app or handle it.
