### ISSUE TITLE
Android: datetime picker cancelText and confirmText props

### ISSUE THREAD

**Issue by sossargsyan** [mmazzarolo/react-native-modal-datetime-picker#34]
Hi Matteo,
I would like to use custom texts for "Confirm" and "Cancel" buttons in Android platform.
Is it possible?
Thanks!

**Comment by mmazzarolo** [comment]
Hey @sossargsyan 
This component is just a wrapper over [react-native's datePickerAndroid/timePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), so if you can change their text label button you'll be able to change the label of this component too.  

Let me know if you need more info on the matter (I never changed them, but I guess you should take a look [here](https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=datepickerandroid%20) first).
