### ISSUE TITLE
Options text in IOS white on white background

### ISSUE THREAD

**Issue by psyfire25** [mmazzarolo/react-native-modal-datetime-picker#341]
## Environment

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 176.11 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Platforms

iOS

## Versions
"@react-native-community/datetimepicker": "^2.1.0",
    "expo": "^35.0.0",
    "moment": "^2.24.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-ionicons": "^4.6.3",
    "react-native-modal-datetime-picker": "^7.6.1",

## Description

When the modal pops in IOS the text is white on a white background

## Reproducible Demo

`import React, { Component } from "react";
import { Text, TouchableOpacity, View, StyleSheet } from "react-native";
import DateTimePicker from "react-native-modal-datetime-picker";

export default class Picker extends Component {
  state = {
    isDateTimePickerVisible: false
  };

  _showDateTimePicker = () => this.setState({ isDateTimePickerVisible: true });

  _hideDateTimePicker = () => this.setState({ isDateTimePickerVisible: false });

  _handleDatePicked = date => {
    console.log("A date has been picked: ", date);
    this._hideDateTimePicker();
  };

  render() {
    return (
      <View style={{ flex: 1 }}>
        <TouchableOpacity
          style={styles.pickerBtn}
          onPress={this._showDateTimePicker}
        >
          <Text>Pick your morning reminder</Text>
        </TouchableOpacity>
        <DateTimePicker
          isVisible={this.state.isDateTimePickerVisible}
          onConfirm={this._handleDatePicked}
          onCancel={this._hideDateTimePicker}
          mode={"time"}
          titleIOS={""}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  pickerBtn: {
    backgroundColor: "#f6c532",
    justifyContent: "center",
    alignItems: "center",
    width: "80%",
    height: 100,
    borderRadius: 25,
    padding: 15
  },
  btnText: {
    fontSize: 23,
    color: "#fff"
  }
});`

!-- Please follow the guidelines for providing a minimal example: https://stackoverflow.com/help/mcve -->

**Comment by psyfire25** [comment]
This was down to my iso device being in darkmode is there a way to check for this and render accordingly?

**Comment by mmazzarolo** [comment]
👋 @psyfire25  please see [the README.md](https://github.com/mmazzarolo/react-native-modal-datetime-picker#i-cant-see-the-picker-on-ios--the-picker-is-white-on-ios)
