### ISSUE TITLE
Date/Time pop up again even after date/time is selected in Android

### ISSUE THREAD

**Issue by yash1511** [mmazzarolo/react-native-modal-datetime-picker#355]
## Environment
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 90.88 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4

## Platforms
Android

## Versions

- Android: 28
- iOS: N/A
- react-native-modal-datetime-picker: 8.1.1
- react-native: 0.61.4
- react: 16.9.0

## Description
I just updated to ```v8.1.1``` and both Date and Time picker pop up twice even after ```OK``` is pressed and the selected time is confirmed.

## Reproducible Demo
```yarn add react-native-modal-datetime-picker @react-native-community/datetimepicker```
```npx react-native run-android```
Select Date/Time, press ```OK``` and the same modal will pop up again.

**Comment by mmazzarolo** [comment]
Hey @yash1511 , thanks for opening the issue.
This seems to be a known problem of [`@react-native-community/datetimepicker`](https://github.com/react-native-community/react-native-datetimepicker/issues/54). 
Please see if the workarounds reported in that issue work for you. Unfortunately we can't fix it on our side. 
I'll keep the issue open for visibility.

**Comment by galvana** [comment]
Hi @yash1511, I ran into the same thing today. This comment was useful:

https://github.com/react-native-community/react-native-datetimepicker/issues/54#issuecomment-553826672

I closed the modal in my onConfirm function before doing anything with the value and the issue went away.

**Comment by parth-koshta** [comment]
> Hi @yash1511, I ran into the same thing today. This comment was useful:
> 
> [react-native-datetimepicker/datetimepicker#54 (comment)](https://github.com/react-native-datetimepicker/datetimepicker/issues/54#issuecomment-553826672)
> 
> I closed the modal in my onConfirm function before doing anything with the value and the issue went away.

Thanks @galvana
