### ISSUE TITLE
onChange does not receive 'event' argument

### ISSUE THREAD

**Issue by okputadora** [mmazzarolo/react-native-modal-datetime-picker#356]
In the documentation it says that all props from react-native-community/react-native-datetimepicker are available. While this is true, the onChange prop in react-native-datetimepicker receives an event object and the date object as arguments while the onChange prop in this library seems to only receive the date. 

https://github.com/react-native-community/react-native-datetimepicker#onchange-optional

Lack of access to the event is causing issues for me because I am trying to implement a fix to set the initial date value described here: https://github.com/react-native-community/react-native-datetimepicker/issues/94 currently there is no way to set an initial value in either library. 

Thanks in advance for any advice or help you might be able to provide me

**Comment by mmazzarolo** [comment]
@okputadora thanks for submitting the issue!
Just to clarify: is the "event" parameter just needed because of the issue #94 ?
If that's the case, I _feel_ i should be solved there first...

Otherwise, if the "event" parameter provides informations that are not available anywhere else I agree with you and we should look into exposing it.

**Comment by okputadora** [comment]
@mmazzarolo Thanks for the quick response! 

at the moment, I only need it because of the issue with react-native-community/react-native-datetimepicker#94 . I agree it should be fixed there, however, it seems like the repo is not well supported anymore, so I wonder if that is going to happen any time soon. Additionally, while I don't currently need any other information from the 'event' parameter,  I feel like it could be useful to other users for determining when the date is 'set' (for the first time) vs. 'changed'

**Comment by mmazzarolo** [comment]
> I agree it should be fixed there, however, it seems like the repo is not well supported anymore, so I wonder if that is going to happen any time soon.

:/ 

>  I feel like it could be useful to other users for determining when the date is 'set' (for the first time) vs. 'changed'

🤔 I'm curious, can't this be done directly with a state check (e.g.: by keeping track of the number of times the component has been updated)? it seems to be a more elegant solution to me since it's a controlled component.

**Comment by okputadora** [comment]
hmmmm...now that I'm looking at the proposed solution more closely, its seems like it wouldn't fix the issue of setting an initial date. Because the datetimepicker never reads the value passed to the `value` prop there is no way to set an initial date

**Comment by mmazzarolo** [comment]
Closing, let me know if we still need to discuss this issue further and I'll reopen it :)

**Comment by WoodyWoodsta** [comment]
I think there is value in keeping this issue open. When used in a Typescript project, the type of `onChange` suggests that the event is passed as the first argument. However, this is not actually the case.

**Comment by pvanny1124** [comment]
did you ever resolve this? For some reason, I also don't get the event object when I first scroll through the picker.
