### ISSUE TITLE
titleStyle doesn't work, props for changing confirm / cancel button text styles should be added also

### ISSUE THREAD

**Issue by summerkiflain** [mmazzarolo/react-native-modal-datetime-picker#364]
Hi There,

There is no implementation present for `titleStyle ` in `DateTimePickerModal.ios.js`.

P.S styles should be customizable for confirm / cancel buttons text components, Nobody would like to implement their own confirm / cancel buttons just to change the text color of the buttons. DarkMode also doesn't change the background color of cancel button in dark mode.

Regards.

**Comment by mmazzarolo** [comment]
Hi @summerkiflain !


> There is no implementation present for titleStyle in DateTimePickerModal.ios.js.

Good catch. The `titleStyle` prop is not supported in the latest version, I forgot to remove it from the README. 

Styles are not "customizable" for a couple of reasons:
1. This component aims at looking "native" out of the box. If the style you want to apply to the header/buttons has the goal of making it look more in line with the iOS guideline, feel free to open a PR to update the style of the component 👍 If the style that you're applying is not in line with the iOS guidelines, you can still provide your own header/buttons. 
2. Better maintainability.

**Comment by mmazzarolo** [comment]
#365

**Comment by mmazzarolo** [comment]
> DarkMode also doesn't change the background color of cancel button in dark mode.

It should 🤔... see [this](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/107ad71ac42d31a2d1ff7680085f739590866668/src/DateTimePickerModal.ios.js#L296-L298). 

If you can still reproduce it, do you mind creating an issue for it (with a screenshot maybe?) That would be great. Thanks!
