### ISSUE TITLE
How to test the date time picker

### ISSUE THREAD

**Issue by br3ncha** [mmazzarolo/react-native-modal-datetime-picker#367]
Hi all,

I am currently creating a component that uses the modal date time picker and I am required to do testing. I've been trying to use the react native testing library to test the onConfirm and onCancel events but I keep getting errors. I will attach screenshots, but could someone let me know if I am testing incorrectly or if this isn't even possible atm?

Thanks!

Component code
<img width="736" alt="Screen Shot 2020-02-14 at 3 11 49 PM" src="https://user-images.githubusercontent.com/20421949/74568035-bf0aa780-4f3c-11ea-85f3-5692d1976c99.png">
<img width="746" alt="Screen Shot 2020-02-14 at 3 11 56 PM" src="https://user-images.githubusercontent.com/20421949/74568044-c2059800-4f3c-11ea-8a01-f969226c5716.png">

Tests
<img width="1440" alt="Screen Shot 2020-02-14 at 3 11 14 PM" src="https://user-images.githubusercontent.com/20421949/74568061-cc279680-4f3c-11ea-952a-dfd51780e6b7.png">

Errors
<img width="837" alt="Screen Shot 2020-02-14 at 3 12 11 PM" src="https://user-images.githubusercontent.com/20421949/74568080-d5186800-4f3c-11ea-909f-2d8269b8b6a8.png">

**Comment by mmazzarolo** [comment]
👋 @br3ncha . 
This is more a StackOverflow question than an issue, mind posting it there? 
Thanks!
