### ISSUE TITLE
Missing TypeScript props

### ISSUE THREAD

**Issue by KDederichs** [mmazzarolo/react-native-modal-datetime-picker#371]
## Environment

System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 23.39 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

## Platforms

both

## Versions

- Android: all
- iOS: all
- react-native-modal-datetime-picker:8.2.0
- react-native: all
- react: all

## Description

Hey you say in your documentation `Please notice that all the @react-native-community/react-native-datetimepicker props are also supported!`
while that's true, typescript doesn't seem to agree with you since it's complaining about missing props such as: `display` which is definitely there for the android version of react-native-datetimepicker

`TS2769: No overload matches this call.   Overload 1 of 2, '(props: Readonly<DateTimePickerProps>): DateTimePicker', gave the following error.     Type '{ isVisible: boolean; date: Date; isDarkModeEnabled: boolean; display: string; onConfirm: (date: Date) => void; onCancel: () => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<DateTimePicker> & Readonly<DateTimePickerProps> & Readonly<...>'.       Property 'display' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<DateTimePicker> & Readonly<DateTimePickerProps> & Readonly<...>'.   Overload 2 of 2, '(props: DateTimePickerProps, context?: any): DateTimePicker', gave the following error.     Type '{ isVisible: boolean; date: Date; isDarkModeEnabled: boolean; display: string; onConfirm: (date: Date) => void; onCancel: () => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<DateTimePicker> & Readonly<DateTimePickerProps> & Readonly<...>'.       Property 'display' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<DateTimePicker> & Readonly<DateTimePickerProps> & Readonly<...>'.`
## Reproducible Demo

Install typescript and set display prop -> error missing prop

**Comment by mmazzarolo** [comment]
Anyone willing to submit a PR for this?
