### ISSUE TITLE
After adding minimum date scrolling is not getting selected on the very first time.

### ISSUE THREAD

**Issue by Akshaykapadi** [mmazzarolo/react-native-modal-datetime-picker#373]
After adding minimum date on scrolling date it is not getting stop for the first time on another date it comes back to current date. Please help to solve the problem .

Please have a look on video it will help you to understand the issue

![dateVideo-min](https://user-images.githubusercontent.com/58328620/75092949-1fd05a80-55a3-11ea-9fd4-cfd07d410278.gif)

**Comment by mmazzarolo** [comment]
Hey @Akshaykapadi , thanks for reporting but we need all the information required in the issue template (with a reproducible minimum example).

**Comment by Akshaykapadi** [comment]
Hi @mmazzarolo i will share the code and example
