### ISSUE TITLE
After adding minimum date scrolling is not getting selected on the very first time. 

### ISSUE THREAD

**Issue by Akshaykapadi** [mmazzarolo/react-native-modal-datetime-picker#375]
Hi @mmazzarolo , Here is my code:
<DateTimePicker 
                              isVisible={this.state.isVisible}
                              onConfirm={this.handlePicker}
                              onCancel = {this.hidePicker}
                              mode = "datetime"
                              is24Hour={false}
                              minuteInterval={30}
                              minimumDate={this.state.minimumDate}
                              maximumDate={this.state.maximumDate}
                             
                            />

The issue is, when the user is selecting a date & time, them modal appears and on the very first time when the user scrolls the date, the date needs to be selected as random date on scrolling but it is not getting selected and it comes back to current date but when the user selects for the second time it works fine. The issue is in adding minimum date or  when the modal appears it is giving problem on scroll. Please help on this asap

Please find below the GIF and check the flow as , i have described above. 
![dateVideo-min](https://user-images.githubusercontent.com/58328620/75130459-70a39880-56f4-11ea-898c-4e6d28220a66.gif)

**Comment by mmazzarolo** [comment]
@Akshaykapadi please follow the issue template guideline before creating a new issue:
## Reproducible Demo

Let us know how to reproduce the issue. Include a code sample or share a project that reproduces the issue.
Please follow the guidelines for providing a minimal example: https://stackoverflow.com/help/mcve

### We cannot fix a bug without a minimal reproducible example.
