### ISSUE TITLE
I want to close android Date & time picker by specific method called.

### ISSUE THREAD

**Issue by Sameer-Jani** [mmazzarolo/react-native-modal-datetime-picker#377]
## Ask your Question

How can I close opened date or time picker dialog after it's open I want to close it by any specific method.

By the way I want to close it when app goes into background and come to foreground again that time picker dialog should be closed.
I have background callback via AppState but I could not close dialog.

there is isVisible props available and I set it's value as local state.
But after opened dialog it's not closed even that props value pass as false.

What can I do here, Inside code I have check there is event "dismissed" you are getting and invoke callback but it's after it's close the it will invoke callback but how to close programmatically from react native side.

**Comment by mmazzarolo** [comment]
@Sameer-Jani setting `isVisible` to `false` should work.  
Make sure the issue isn't caused by AppState. Try setting a `setTimeout` that sets the `isVisible` prop to `false` for example, to see if it works.

**Comment by Sameer-Jani** [comment]
@mmazzarolo 
Thanks for quick reply. I appreciate it.

I have checked it by that way too.
I am attaching demo code here.
can you please check it ?

import React, { Component } from "react";
import { Button, View } from "react-native";
import DateTimePickerModal from "react-native-modal-datetime-picker";

class Example extends Component {
    constructor(props){
        super(props);
        this.state = {
            isDatePickerVisible: false,   
        }
    }

  setDatePickerVisibility(isVisible){
      this.setState({
          isDatePickerVisible: isVisible
      },()=>{
          console.log("isDatePickerVisible value : ",this.state.isDatePickerVisible);
      })
  }

  showDatePicker = () => {
    this.setDatePickerVisibility(true);
    setTimeout(() => {
        this.hideDatePicker();
    }, 2000);
  };

  hideDatePicker = () => {
    console.log("called ","hideDatePicker");
    this.setDatePickerVisibility(false);
  };

  handleConfirm = date => {
    console.warn("A date has been picked: ", date);
    this.hideDatePicker();
  };

  render(){
  return (
    <View>
      <Button title="Show Date Picker" onPress={()=>{this.showDatePicker()}} />
      <DateTimePickerModal
        isVisible={this.state.isDatePickerVisible}
        mode="date"
        onConfirm={()=>{this.handleConfirm()}}
        onCancel={()=>{this.hideDatePicker()}}
      />
    </View>
  );
};
}

export default Example;

**Comment by mmazzarolo** [comment]
Try this:
```js
import React, { Component } from "react";
import { Button, View } from "react-native";
import DateTimePickerModal from "react-native-modal-datetime-picker";

class Example extends Component {
  state = {
    isDatePickerVisible: false
  };

  handleButtonPress = () => {
    this.showDatePicker();
    setTimeout(this.hideDatePicker, 5000);
  };

  showDatePicker = () => {
    this.setState({ isDatePickerVisible: true });
  };

  hideDatePicker = () => {
    this.setState({ isDatePickerVisible: true });
  };

  handleConfirm = date => {
    console.warn("A date has been picked: ", date);
    this.hideDatePicker();
  };

  render() {
    return (
      <View>
        <Button title="Show Date Picker" onPress={this.handleButtonPress} />
        <DateTimePickerModal
          isVisible={this.state.isDatePickerVisible}
          mode="date"
          onConfirm={this.handleConfirm}
          onCancel={this.hideDatePicker}
        />
      </View>
    );
  }
}

export default Example;

```

**Comment by Sameer-Jani** [comment]
@mmazzarolo 
Thanks again.

I have checked above code.
I am checking with Android device. still It's not working as expected.
Have you checked in Android device?

**Comment by mmazzarolo** [comment]
Ha, if it's on Android then do it like this:
```js
import React, { Component } from "react";
import { Button, View } from "react-native";
import DateTimePickerModal from "react-native-modal-datetime-picker";

class Example extends Component {
  state = {
    isDatePickerVisible: false
  };

  handleButtonPress = () => {
    this.showDatePicker();
    setTimeout(this.hideDatePicker, 5000);
  };

  showDatePicker = () => {
    this.setState({ isDatePickerVisible: true });
  };

  hideDatePicker = () => {
    this.setState({ isDatePickerVisible: true });
  };

  handleConfirm = date => {
    console.warn("A date has been picked: ", date);
    this.hideDatePicker();
  };

  render() {
    return (
      <View>
        <Button title="Show Date Picker" onPress={this.handleButtonPress} />
        {isDatePickerVisible && <DateTimePickerModal
          isVisible={this.state.isDatePickerVisible}
          mode="date"
          onConfirm={this.handleConfirm}
          onCancel={this.hideDatePicker}
        />}
      </View>
    );
  }
}

export default Example;
```

**Comment by Sameer-Jani** [comment]
@mmazzarolo 

Thanks for reply again.
Above code is still not working.

As I did little bit R&D and my understanding. as above last code should work perfectly but it's working if it's rendered dialog showing through react native only. But actually it's showing native android dialog and after it's appeared it could not disappeared(dismiss) from react native code. I think there is need to create one @ReactMethod annotated java native method and inside that method dismiss dialog code should perform and need to make it available at React native side.

at react native side there is props function should be available to call that java function.

**Comment by mmazzarolo** [comment]
@Sameer-Jani if that is not working It's probably a https://github.com/react-native-community/react-native-datetimepicker issue then :/
