### ISSUE TITLE
Warning: DatePickerIOS has been merged with DatePickerAndroid and will be removed in a future release. It can now be installed and imported from '@react-native-community/datetimepicker' instead of 'react-native'.

### ISSUE THREAD

**Issue by pankajguptablueivory** [mmazzarolo/react-native-modal-datetime-picker#378]
Warning: DatePickerIOS has been merged with DatePickerAndroid and will be removed in a future release. It can now be installed and imported from '@react-native-community/datetimepicker' instead of 'react-native'.

## Environment

react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
## Platforms

iOS

## Reproducible Demo

import DateTimePicker from 'react-native-modal-datetime-picker'

`<DateTimePicker
          isVisible={isDateTimePickerVisible}
          onConfirm={handleDatePicked}
          onCancel={hideDateTimePicker}
        />`

**Comment by Dyshay** [comment]
You need to update manually (uninstall & install) the version 8.5.1

**Comment by mmazzarolo** [comment]
@pankajguptablueivory you should install the latest version (> v8)

**Comment by pankajguptablueivory** [comment]
@Dyshay @mmazzarolo thanks worked :)
