### ISSUE TITLE
Expo: Spinner crashes after a device rotation change

### ISSUE THREAD

**Issue by KevinWilliams89** [mmazzarolo/react-native-modal-datetime-picker#379]
## Environment

Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      npm: 6.9.0 - ~/.npm-packages/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.2.2
    npmGlobalPackages:
      expo-cli: 3.11.7

## Platforms

Only tested on iOS.

## Versions

- Android: n/a
- iOS: 13
- react-native-modal-datetime-picker: v8.5.0 +
- react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz
- react: 16.9.0

## Description

Hi,

I've come across an issue where the picker either errors (on Expo) or shows a blank screen on opening of the picker after the screen orientation has changed.

Everything works fine initially, but when I rotate the device to change its orientation, it then causes problems. In Expo I get the following error:

![Simulator Screen Shot - iPad Air (3rd generation) - 2020-03-02 at 11 20 58](https://user-images.githubusercontent.com/43469795/75673176-3ef17b00-5c7a-11ea-8b26-5534d322ad01.png)

When replicating on an iPad, the picker just doesn't appear after opening when the orientation has changed. 

I've found that if I rollback to v8.4.0 of this picker, then it works as expected.

## Reproducible Demo

To reproduce:

1. You can copy and paste the example code in the "Usage" section of the readme, into a project
2. Run it on the simulator with Expo or on a device (I used an iPad)
3. Click on the button to open the picker - it works fine as expected
4. Close the picker
5. Rotate the device to change it's orientation
6. Click on the button again to open the picker, in Expo it will show an error similar to the above. On a device the picker will no longer be visible.

**Comment by mmazzarolo** [comment]
Should be fixed by https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/403 once merged 👍
