### ISSUE TITLE
Persisting the user's selected date and time after selection.

### ISSUE THREAD

**Issue by ismaelbarry** [mmazzarolo/react-native-modal-datetime-picker#380]
Hi all!!

I'm currently using the` react-native-model-datetime-picker 8.1.1` and running `react native 0.61.4`. Is it possible to have the user's date and time selection persist after they make their selection? Currently, users have to completely set a new date and time selection because the picker doesn't remember the user's choice. Instead, it defaults to the current date and time.

Thanks in advance for any help--really appreciate it!

**Comment by mmazzarolo** [comment]
@ismaelbarry hey!
Have you already tried using the `date` prop to set the initial date on the component?

**Comment by ismaelbarry** [comment]
> @ismaelbarry hey!
> Have you already tried using the `date` prop to set the initial date on the component?

Awesome! I got it to work. Thanks!

Do you know when the library will be able to support dark mode for the date time picker? Currently, users are wondering why it doesn't work when the app is in dark mode. I followed the instructions in the documentation and added the following to the info.plist file in my app.json.

```
      "infoPlist": {
        "UIUserInterfaceStyle": "Light",
      }
```
