### ISSUE TITLE
Date Picker not working on real iOS device but work on simulator

### ISSUE THREAD

**Issue by iamapinan** [mmazzarolo/react-native-modal-datetime-picker#382]
## Environment
```
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 24.95 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```
## Platforms
`iOS`

## Versions

- Android:`9pie`
- iOS:`13.2`
- react-native-modal-datetime-picker: `7.6.0`
- react-native:`0.61.4`
- react:`16.9.0`

## Description
Below is my code.

When I run on the simulator device it works perfectly. But when I publish to AppStore and download to real devices time picker is working except date picker is not working it locked.
It makes me hard to correct a problem.
![](https://trello-attachments.s3.amazonaws.com/5e4e2d5e3b4ede1988c684b0/5e5fc39fe3dae56c389509f0/7b7f9769a38064b1944467a669d0c383/%E0%B9%85%E0%B9%85%E0%B9%85%E0%B9%85%E0%B9%85%E0%B9%85%E0%B9%85%E0%B9%85.jpg)
## Reproducible Demo

```
<DateTimePicker
    mode='date'
    minimumDate={new Date()}
    pickerTextEllipsisLen={15}
    isVisible={this.state.isDatePickerVisible}
    onConfirm={this._handleDatePicked}
    onCancel={this._hideDatePicker}
/>
```

**Comment by selcukitmis** [comment]
I am also have the same problem
