### ISSUE TITLE
When add date prop and minimum date prop, time selection popup comes twice.

### ISSUE THREAD

**Issue by BSThisarasinghe** [mmazzarolo/react-native-modal-datetime-picker#383]
In my date picker I added date prop. Then after running the app, date field comes first, and then time selector pops up twice. Same thing happened when I added minimum date field.

`<DateTimePickerModal
                            date={new Date()}
                            isVisible={this.state.isEndDatePickerVisible}
                            onConfirm={this.handleEndDatePicked}
                            onCancel={this.hideEndDatePicker}
                            datePickerModeAndroid='calendar'
                            mode='datetime'
                     />`

I hope my problem is clear. If anyone can suggest me any solution, please advise.

**Comment by dane8373** [comment]
I have this issue as well, it is not present when I downgrade to 8.0.6

**Comment by fasalir** [comment]
> I have this issue as well, it is not present when I downgrade to 8.0.6

Hi i followed your solution by downgraded to 8.0.6, but popup still comes twice

**Comment by omair2010** [comment]
guys u can do this 

    hideDatePicker();
    setValue(newDate);

hide the picker before changing the value try it

**Comment by mmazzarolo** [comment]
Hey! Please follow the issue template before creating a new issue, thanks!
