### ISSUE TITLE
disable time before problem

### ISSUE THREAD

**Issue by omair2010** [mmazzarolo/react-native-modal-datetime-picker#385]
## Ask your Question
we can do minimumDate={new Date()} to disable the date before today but we cant do that to disable the hours before the time exemple we have minumumDate like this
11/30/2020 15:30
we still can pick this date time
11/30/2020 14:30
there is any solution to make it disable the time before?

**Comment by mmazzarolo** [comment]
Hey! Please use StackOverflow for troubleshooting, thanks!
