### ISSUE TITLE
Spinner style on Android

### ISSUE THREAD

**Issue by fadhilmi** [mmazzarolo/react-native-modal-datetime-picker#390]
**Spinner On Android**
is there any option to change the modal from default datepicker style to spinner style on android?

**Comment by mmazzarolo** [comment]
Hey @fadhilmi , [here are the available display options for android](https://github.com/react-native-community/datetimepicker#display-optional-android-only)

**Comment by SeanDunford** [comment]
Just as an FYI for anyone else searching. This lib spreads all the props you send into it to the [DateTimePicker component](https://github.com/react-native-community/datetimepicker#display-optional-android-only)

which you can see [here](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/DateTimePickerModal.android.js#L55)

Meaning that you can simply do:

```
import DateTimePicker from 'react-native-modal-datetime-picker';
<DateTimePicker
  isDarkModeEnabled={colorScheme === 'dark'}
  display="spinner"
/>
```

to achieve the `spinner` style on either platform. 

If i get the time. I will try to submit pr for documentation to make that more clear.

**Comment by hardikjs** [comment]
![646d6b7d-5618-4af3-a155-c7199d31430a](https://user-images.githubusercontent.com/33776753/106032747-e0858480-60f6-11eb-8a13-a168a386d3e7.png)

@mmazzarolo Even I have `display="spinner"` still it display calendar in samsung tablet but don't show in mobile.

How to fix it?

**Comment by raghavendra726** [comment]
Hi ,

I am facing same issue in Android Tablet. 
Please let me know if any fixes for the above issue.

Using below pacakage:

"react-native-modal-datetime-picker": "9.1.0",

**Comment by raghavendra726** [comment]
Is there any fixes for the above issue?
Unable to fix calendar overlapping issue in Android Tablet.

Currently using below package:
react-native-modal-datetime-picker: 9.1.0,
react-native-cli: 2.0.1
react-native: 0.60.5

![image](https://user-images.githubusercontent.com/8320217/149291334-d54b3af2-3dcf-4e72-8d7d-aad800e09c6d.png)
