### ISSUE TITLE
Force dark mode

### ISSUE THREAD

**Issue by IngenieroLata** [mmazzarolo/react-native-modal-datetime-picker#391]
## Force dark mode in ios and Android

Is it possible to force the dark mode in ios and Android? I tried to add the prop isDarkModeEnabled and kind of work in iOS but not in Android.

<img width="431" alt="Screen Shot 2020-03-20 at 12 01 34 PM" src="https://user-images.githubusercontent.com/5667514/77187522-a09b4d00-6aa2-11ea-93fa-e2d69d1583c4.png">

<img width="369" alt="Screen Shot 2020-03-20 at 12 01 54 PM" src="https://user-images.githubusercontent.com/5667514/77187537-a4c76a80-6aa2-11ea-83a8-72f34eaf4450.png">

**Comment by mmazzarolo** [comment]
Hey! This is more of an Android native-layer question and this component doesn't have do anything on that side. You should probably check how to do that on [the community picker (used under the hood by this lib)](https://github.com/react-native-community/datetimepicker) or on react-native itself.
