### ISSUE TITLE
Android calendar picker overlaping maximum or minimum date

### ISSUE THREAD

**Issue by hadisuria** [mmazzarolo/react-native-modal-datetime-picker#392]
## Environment
System:
OS: macOS 10.15.3
CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
Memory: 53.82 MB / 8.00 GB
Shell: 5.7.1 - /bin/zsh

## Platforms
Android OS

## Versions

- Android: PIE 9.0
- react-native-modal-datetime-picker: 6.0.0
- react-native: 0.61.5
- react: 16.9.0

## Description
Android calendar datepicker can overlap the maximum or minimum date.  On the third picture if I press ok, it will set the date to 31 march 2020, which is overlaping the maximum date 21 march 2020.

![Screen Shot 2020-03-21 at 15 03 43](https://user-images.githubusercontent.com/32417244/77222406-5f2f9e00-6b85-11ea-9d9a-7a8628c54eec.png) ![Screen Shot 2020-03-21 at 15 04 33](https://user-images.githubusercontent.com/32417244/77222407-6191f800-6b85-11ea-8a3b-c51560c0419b.png) ![Screen Shot 2020-03-21 at 15 04 47](https://user-images.githubusercontent.com/32417244/77222408-62c32500-6b85-11ea-9760-aa4f426f4cc5.png)

**Comment by mmazzarolo** [comment]
Under the hood react-native-modal-datetime-picker uses [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker).
Before reporting a bug, swap react-native-datetime-picker with [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker) to check if the problem persists. If it does please report the issue in the [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker) repo instead.
