### ISSUE TITLE
Picker value does not change after choosing new date

### ISSUE THREAD

**Issue by bryanbcheng** [mmazzarolo/react-native-modal-datetime-picker#393]
## Environment

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 339.21 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 24, 26, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1

## Platforms

Occurs on both iOS and Android

## Versions

- react-native-modal-datetime-picker: 8.5.1
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 2.1.0
- react-native: 0.61.5
- react: 16.9.0

## Description

After changing the date, when I reopen the picker, the selected date is the original date provided in the value field. I tried using react-native-community/datetimepicker and the value seems to update when I reopen the picker on Android (could not test on iOS since could not close the picker)

For example, if the default date is March 23, 2020. Once I open the picker and select March 22, 2020 and click OK (or Confirm on iOS). The picker closes and the UI of my app updates to the new date value. But when I click to open the picker again, the date shows March 23, 2020 again.

## Reproducible Demo

```
import React, { Component } from 'react';
import { Text, View, Button } from 'react-native';
import DateTimePickerModal from 'react-native-modal-datetime-picker';

import moment from 'moment';

class CreateScreen extends Component {
  static navigationOptions = ({ navigation }) => {
    return {
      title: 'Test'
    }
  };

  constructor(props) {
    super(props);

    this.state = {
      date: new Date(),
      showDatePicker: false
    }
  }

  setDate = date => {
    this.setState({
      date: date,
      showDatePicker: false
    });
  }

  showDatePicker = () => {
    this.setState({ showDatePicker: true });
  }

  hideDatePicker = () => {
    this.setState({ showDatePicker: false });
  }

  render() {
    const { showDatePicker, date } = this.state;

    return (
      <View>
        <View>
          <Button
            title={ moment(date).format('MMM Do YYYY') }
            onPress={ () => this.showDatePicker() }
          />
        </View>
        <DateTimePickerModal
          isVisible={ showDatePicker }
          value={ date }
          mode='date'
          onConfirm={ this.setDate }
          onCancel={ this.hideDatePicker }
        />
      </View>
    );
  }
}

export default CreateScreen;
```

**Comment by Atharva13** [comment]
Yeah @bryanbcheng I have also received the same issue.

**Comment by mmazzarolo** [comment]
👋 See the [props section](https://github.com/mmazzarolo/react-native-modal-datetime-picker#available-props). 
You should use the `date` prop instead of the `value` one.

**Comment by bryanbcheng** [comment]
Thank you! That fixed it =)

**Comment by Dustin2** [comment]
i dont understand not work for me
