### ISSUE TITLE
Date time labels are black when isDarkModeEnabled is true

### ISSUE THREAD

**Issue by NewBieBR** [mmazzarolo/react-native-modal-datetime-picker#395]
## Platforms

both

## Versions

- Android:
- iOS:
- react-native-modal-datetime-picker: 8.1.3
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):2.2.1
- react-native:0.61.5
- react:16.12.0

## Description

Date time labels are black when isDarkModeEnabled is true and the phone's dark mode is disabled. Users should be able to choose to use a dark theme of an app without having to enable the phone dark mode.

## Reproducible Demo

- Install
- Add <DateTimePickerModal isDarkModeEnabled={true}

**Comment by mmazzarolo** [comment]
> Date time labels are black when isDarkModeEnabled is true and the phone's dark mode is disabled. Users should be able to choose to use a dark theme of an app without having to enable the phone dark mode.

Sorry, this is not (and won't be) supported.
