### ISSUE TITLE
How can I add display="spinner' just for time using mode="datetime"?

### ISSUE THREAD

**Issue by DivinoMatheus** [mmazzarolo/react-native-modal-datetime-picker#399]
I was using the `timePickerModeAndroid` prop to display just the time as spinner when using a `<DateTimePickerModal  mode="datetime"/>` with `mode` prop using 'datetime'. But now I updated all the packages and that prop doesn't exists anymore.

Is still possible do something like that in the new version?

**Comment by mmazzarolo** [comment]
This lib also support the [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker) props that you can find [here](https://github.com/react-native-community/datetimepicker#props). I guess you need the `display` one.
