### ISSUE TITLE
Is there a way to have the minutes be incremental?

### ISSUE THREAD

**Issue by switch13** [mmazzarolo/react-native-modal-datetime-picker#400]
## Ask your Question

I'm looking to have the minutes for the 'time' mode only show 15-minute intervals for faster form submission because I have users filling this out in a form for open and close hours for every day of the week and it's a lot for them to do 14 times. Is that currently possible?

If not, I'm not savvy enough build...is there some sort of feature request I can fill out?

Thanks so much in advance!

**Comment by mmazzarolo** [comment]
Hey @switch13 , this behaviour is controlled by the [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker), and as far as I know it's not possible to change.

**Comment by shafqatbari** [comment]
you can use minuteInterval 

import DateTimePickerModal from 'react-native-modal-datetime-picker';
 
   <DateTimePickerModal
                        isVisible={timeModal}
                        minuteInterval={15}
                        mode="time"
                    />
