### ISSUE TITLE
How do you set the value prop?

### ISSUE THREAD

**Issue by GollyJer** [mmazzarolo/react-native-modal-datetime-picker#401]
👉 Please notice that all the `@react-native-community/react-native-datetimepicker` props are also supported!

But it has a value prop to set the initial value when the picker opens. I can't get it to work with `react-native-modal-datetime-picker`.

**Comment by mmazzarolo** [comment]
You should use the `date` prop instead

**Comment by sanjeevkse** [comment]
@mmazzarolo It works Thank you.

Please add it to the documentation
