### ISSUE TITLE
Please set useNativeDriver to true or false (Yellowbox is whining)

### ISSUE THREAD

**Issue by jasonb12** [mmazzarolo/react-native-modal-datetime-picker#402]
https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/dde0a2f3d074526063584f9ccf0166d45ec83418/src/Modal.js#L89

**Comment by mmazzarolo** [comment]
hey! have you seen the comment on top of that?
also, on what version of react-native are you?

**Comment by mmazzarolo** [comment]
Should be fixed by https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/404
