### ISSUE TITLE
Change the picker text style 

### ISSUE THREAD

**Issue by hasithaWalpola** [mmazzarolo/react-native-modal-datetime-picker#405]
Is there way to change the picker container text styles like change the text color and size etc.?

**Comment by mmazzarolo** [comment]
Hey @hasithaWalpola , please see https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/366

**Comment by hasithaWalpola** [comment]
Hey @mmazzarolo  not the button text color, I need to change the picker container text color, Is there any solution for that?

**Comment by mmazzarolo** [comment]
AFAIK it's not possible, because they're native components. You should head to https://github.com/react-native-community/datetimepicker for more info
