### ISSUE TITLE
showing both date and time 

### ISSUE THREAD

**Issue by ramisalem** [mmazzarolo/react-native-modal-datetime-picker#406]
Hello I am using DateTime mode and I am looking for a way to display selected date and time in the picker input

**Comment by mmazzarolo** [comment]
I'm sorry @ramisalem , I can't understand your question. Please also add more details (e.g. Android/iOS)

**Comment by FDiskas** [comment]
If I setup `mode="datetime"` on Android I get console warning
```
Cannot open time picker TimePickerAndroid has been removed from React Native. It can now be installed and imported from '@react-native-community/datetimepicker' instead of 'react-native'.
```

**Comment by glacjay** [comment]
@mmazzarolo That means, show date and time part at the same time in the modal, mainly for iOS.
