### ISSUE TITLE
DateTimePickerModal causes issues with Backhandler

### ISSUE THREAD

**Issue by DChiuch** [mmazzarolo/react-native-modal-datetime-picker#408]
If I have a DateTimePickerModal in my component, then registering a BackHandler listener will no longer work. eg. if I have:

```
componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.handleBackButton);
}
```

as well as a DateTimePickerModal in the component – then _handleBackButton_ never gets called.

**Comment by mmazzarolo** [comment]
👋 @DChiuch , please follow the issue template before submitting a new issue.  
From a first glance I'm not sure what is happening btw, we're not overriding the BackHandler in this component.
