### ISSUE TITLE
How do I set the time and date for the different time zones?

### ISSUE THREAD

**Issue by lixiaobin0303** [mmazzarolo/react-native-modal-datetime-picker#41]
I didn't get the time with the local time. I think it's because of the time zone problem. How can I solve it? Thank you

**Comment by mmazzarolo** [comment]
Hi! 
This component uses React-Native's Android TimePicker/DatePicker APIs under the hood, and as far as I know the timezone of the pickers are handled by them directly.  
I suggest you to check if React-Native's Android TimePicker/DatePicker APIs return the right dates.  
If they still have a wrong timezone you should open an issue on the [React Native repo](https://github.com/facebook/react-native/issues) or even better ask for help in [StackOverflow](https://stackoverflow.com/) by tagging it with "react-native".  
I'll leave the issue open for a bit, let me know if you fix it :)

**Comment by lixiaobin0303** [comment]
Thank you for solving the problem for me because of the use of the simulator

**Comment by mmazzarolo** [comment]
Mh... Glad you solved it? (Hope I got your comment right 😄 ).  
Closing, feel free to reopen if needed!

**Comment by lixiaobin0303** [comment]
I feel shy to the real machine test a bit or the date with the real time difference a day and time is not correct

**Comment by mmazzarolo** [comment]
Sorry man, can't understand what you're saying :(

**Comment by lixiaobin0303** [comment]
I tested it with my cell phone, but it wasn't the right time
