### ISSUE TITLE
Ios dark mode: Dates are not showing

### ISSUE THREAD

**Issue by sachin-varshney** [mmazzarolo/react-native-modal-datetime-picker#410]
In the iphone of any version, the date is not showing if the we switched from light mode to dark mode.
Do let us know how can we change the color of date.
Please provide a solution

**Comment by michalzuk** [comment]
@sachin-varshney
From docs:

> Please notice that all the @react-native-community/react-native-datetimepicker props are also supported!

You can use the property `textColor` to change it.
