### ISSUE TITLE
Dates are not visible on iOS device while dark mode active

### ISSUE THREAD

**Issue by adamvx** [mmazzarolo/react-native-modal-datetime-picker#411]
## Environment

System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 63.06 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

## Platforms

iOS

## Description

When opening date picker in iOS while dark mode is activated, dates are not visible but still selectable. After turning off dark mode labels are again visible.

## Screenshot

https://snipboard.io/VAgRel.jpg

**Comment by shlaing** [comment]
Please read the Readme. 
There is an answer.

Thank you.

**Comment by mmazzarolo** [comment]
Can confirm. Thanks @shlaing :)

**Comment by adamvx** [comment]
Thank you for the answer! I totally missed that.

**Comment by jinguohao1991** [comment]
So, what is the answer?

**Comment by hamzaouhssain1993** [comment]
there is a variable called "isDarkModeEnabled" that you able to TRUE if you have darkMode

**Comment by EricLewe** [comment]
Worth to note is that if you have class based components you will get errors calling the following line specified in the docs 
`const colorScheme = useColorScheme();`

I solved it by attach an event listener as was provided by react natives docs:
https://github.com/facebook/react-native/blob/master/RNTester/js/examples/Appearance/AppearanceExample.js

**Comment by crobinson42** [comment]
@jinguohao1991 I'm fixing this now for our iOS app ;-)
