### ISSUE TITLE
minimumDate not working on Android

### ISSUE THREAD

**Issue by DaniSido** [mmazzarolo/react-native-modal-datetime-picker#413]
## Environment
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 811.82 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.17.0 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Platforms
Android

## Versions
- Android: 10QKQ1.190825.002
- react-native-modal-datetime-picker: ^8.5.4
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 2.2.2
- react-native: sdk-37.0.0
- react: 16.9.0

## Description
Hi,
This to report that the minimumDate on Android it's not working properly because it consider only the date and ignore the date's time.

So, doing an example:

localDateTime: 2020-04-21 15:00

If I'll set the minimum date to 2020-04-22 15:00 (so +24hours from now), the datepicker will show the correct date (2020-04-22) but with the wrong time (in fact I can select as a date, also for example, 2020-04-22 00:00).

I've underlined Android because in iOS all of this works perfectly.

How could i fix this issue?

Thank you.
Daniele.
![Screenshot_2020-04-21-15-10-52-678_host exp exponent](https://user-images.githubusercontent.com/57174489/79870857-e02bc080-83e3-11ea-8dfc-486d096f400b.jpg)

**Comment by mmazzarolo** [comment]
Ciao @DaniSido 👋 
Puoi ri-creare una issue completando tutto il template? (testando con il community picker + esempio minimo). 
Grazie!

**Comment by aglSourabh** [comment]
Facing the same issue.

**Comment by RxmvnLD** [comment]
Any news on this issue? Did anyone found a fix?
