### ISSUE TITLE
minimumDate not working on Android

### ISSUE THREAD

**Issue by DaniSido** [mmazzarolo/react-native-modal-datetime-picker#414]
Environment
System:
OS: macOS 10.15.4
CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
Memory: 811.82 MB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.17.0 - /usr/local/bin/node
npm: 6.11.3 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
IDEs:
Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
npmPackages:
react: 16.9.0 => 16.9.0
react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
npmGlobalPackages:
react-native-cli: 2.0.1

Platforms
Android

Versions
Android: 10QKQ1.190825.002
react-native-modal-datetime-picker: ^8.5.4
react-native-community/datetimepicker: 2.2.2
react-native: sdk-37.0.0
react: 16.9.0

## Description

Ciao @mmazzarolo,
ho provato con il community date picker ma il datetime non è supportato da android, e testando solo la modalità "time" posso comunque settare un orario antecedente a quello indicato.

Come posso risolvere?
Grazie

## Reproducible Demo

`<DateTimePickerModal
                        isVisible={isEventDatePickerVisible}
                        cancelTextIOS="Cancella"
                        confirmTextIOS="Conferma"
                        date={new Date(moment().add(24, "hours"))}
                        minimumDate={new Date(moment().add(24, "hours"))}
                        locale="it_IT"
                        mode="datetime"
                        minuteInterval={15}
                        onConfirm={(date) => {
                          setEventDatePickerVisibility(false);
                          setEventFinishDate("");
                          setFinishDisplayDate("");
                          setExpiryDate("");
                          setExpiryDisplayDate("");
                          setEventDate(moment(date).format("YYYY-MM-DD HH:mm"));
                          setEventDisplayDate(moment(date).format("LLLL"));
                        }}
                        onCancel={() => setEventDatePickerVisibility(false)}
                      />`

**Comment by mmazzarolo** [comment]
> Ciao @mmazzarolo,
ho provato con il community date picker ma il datetime non è supportato da android, e testando solo la modalità "time" posso comunque settare un orario antecedente a quello indicato.
Come posso risolvere?

Purtroppo se non e' supportato dal community picker allora nemmeno questo repo puo' supportarlo, sorry. 

eng: Since the minimum date/time is not supported by the community picker, we can't support it here
