### ISSUE TITLE
Display year with type 'datetime'

### ISSUE THREAD

**Issue by gerryfletch** [mmazzarolo/react-native-modal-datetime-picker#420]
## Ask your Question
The mode `date` displays `MM/DD/YYYY` as options. `datetime` displays `day+month/hour/second/am+pm`. I am interested in displaying the year too, which is available on Android but not iOS. Ideally, `day+month/hour/year`, though any complete date-time with year would work too.

Is this level of customisation available in the library?

**Comment by mmazzarolo** [comment]
> Is this level of customisation available in the library?

Nope, but you can probably look into the community datetime picker (that is being used under the hood by this library) 👍

**Comment by gerryfletch** [comment]
Great, thanks for the prompt reply @mmazzarolo and your hard work on the library!
