### ISSUE TITLE
textColor prop

### ISSUE THREAD

**Issue by Asim-A** [mmazzarolo/react-native-modal-datetime-picker#421]
In the readme it says: "👉Please notice that all the [@react-native-community/react-native-datetimepicker](https://github.com/react-native-community/datetimepicker) props are also supported!". 

They have a prop called "textColor", does your component support that? I doesn't seem to be working for me.

Btw. Lovely modal!

**Comment by mmazzarolo** [comment]
👋 
Make sure you're using the correct version on the community picker, because [we're spreading in it all the props](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/aa14a77beff681fca22edb679b8ff5223b935396/src/DateTimePickerModal.ios.js#L141) so if it supports that prop it should work 👍

**Comment by Asim-A** [comment]
Maybe I've misunderstood the use of that prop then. Is it suppose to change the color inside modal? I've provided a picture to clarify. 
![bilde](https://user-images.githubusercontent.com/32423298/81322494-5b53ce80-9094-11ea-99e5-65ddcd139bce.png)

The reason I am wondering this is because of the ios dark mode non compatability. I just want to change the color of the text based on the device theme mode on ios. It's not a big deal though, I'll just use the method described in the readme. 

Thank you for answering and thank you for your contribution. :)

**Comment by mmazzarolo** [comment]
> Is it suppose to change the color inside modal?

No idea honestly, it's their prop 🤷 

In these cases I would suggest you to swap the modal picker with the community picker just to see if it fixes the issue.

**Comment by mmazzarolo** [comment]
Could be related to https://github.com/react-native-community/datetimepicker/issues/131 ?
