### ISSUE TITLE
iOS DateTimePicker ignores the passed date in props

### ISSUE THREAD

**Issue by HaidarZ** [mmazzarolo/react-native-modal-datetime-picker#425]
## Environment

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 906.57 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
## Platforms

iOS
## Versions

- iOS: 13.4.1
- react-native-modal-datetime-picker: 8.6.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 2.4.0
- react-native: 0.61.5
- react: 16.9.0

## Description

iOS DateTimePicker ignores the passed date props . So that when the picker is opened it shows the correct date props selected , but if I select "Confirm" it passes the current date to the `onConfirm `function

## Reproducible Demo

[Video for the case](https://drive.google.com/file/d/1kj1yAnDKDooI_MlLEggOrBSxOHKiNobB/view?usp=sharing)

Below is the code

```
const minimumDate = getTomorrow();

const pickDateEnd = selectedDate => {
  setShowDateEndPicker(false);
  if (selectedDate) {
    itinerary.dateEnd = selectedDate;
  }
};

<DateTimePickerModal
  isVisible={showDateEndPicker}
  mode="date"
  minimumDate={itinerary.dateBeg || minimumDate}
  date={itinerary.dateEnd || minimumDate}
  onConfirm={pickDateEnd}
  onCancel={() => setShowDateEndPicker(false)}
/>
```

**Comment by mmazzarolo** [comment]
@HaidarZ 👋 
Could you please follow the reproducible step instructions of the issue template? Thanks! 

> Let us know how to reproduce the issue. Include a code sample or share a project that reproduces the issue. 
Follow the guidelines for providing a minimal example: https://stackoverflow.com/help/mcve 
Please notice that WE WON'T SUPPORT ISSUE REPORTS THAT DON'T HAVE A MINIMAL REPRODUCIBLE EXAMPLE.
