### ISSUE TITLE
Date picker pops up 2 times

### ISSUE THREAD

**Issue by akug17** [mmazzarolo/react-native-modal-datetime-picker#427]
when i am showing the datepicker and then after selecting a date it atleast pops up for 2 times in android ,also i am setting the isDatePickerVisible correctly

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker#the-picker-shows-up-twice-on-android

**Comment by rezasazesh** [comment]
This should not be closed, this library wraps datetimepicke so should it not also have one of the work arounds implemented?

**Comment by mmazzarolo** [comment]
@rezasazesh this should be fixed on the picker side, we won't add patches on top of issues not related to the code we control.

**Comment by rosnaib11** [comment]
+1 using latest version
