### ISSUE TITLE
Time picker show wrong time in ios 

### ISSUE THREAD

**Issue by sid-metiz** [mmazzarolo/react-native-modal-datetime-picker#428]
Showing not current time in ios while android its showing perfect.

**Comment by sid-metiz** [comment]
why you closed issue?

**Comment by sid-metiz** [comment]
mode='time' and check in ios its not showing current time

**Comment by enriqueao** [comment]
use the issue template

> mode='time' and check in ios its not showing current time

**Comment by Garamani** [comment]
The datetime output is time with timezone. to get the Hours and Minutes:
```
console.log("A date has been picked - hours: ", date.getHours());
console.log("A date has been picked - minutes: ", date.getMinutes());
```
