### ISSUE TITLE
ios modal container style

### ISSUE THREAD

**Issue by ezha86** [mmazzarolo/react-native-modal-datetime-picker#43]
nice and lite component. 
would be great to see possibility to change modal container in the same way as     customTitleContainerIOS,  datePickerContainerStyleIOS done

**Comment by mmazzarolo** [comment]
Hey @ezha86,
thanks!

Adding a `modalStyleIOS` prop shouldn't  be trivial, could you try adding it to [this style line](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/CustomDatePickerIOS/index.js#L114) and see if it fits your tastes?  
If it works correctly I can officially add it to `react-native-modal-datetime-picker` and release it no npm (or you could submit a PR too).

**Comment by ezha86** [comment]
hey @mmazzarolo 
im talking about this : 
see my [gist](https://gist.github.com/ezha86/384083e89e5f119fe3ce93d359057298)
than in my code pass as props -  contentContainerStyleIOS={myStyle.contentContainer}

**Comment by ezha86** [comment]
I have created a small PR. Please review it.
Thanks

**Comment by mmazzarolo** [comment]
Merged! I'll post here when I'll release it on npm :) Thanks!
