### ISSUE TITLE
Only month/year date

### ISSUE THREAD

**Issue by limoli** [mmazzarolo/react-native-modal-datetime-picker#430]
## Ask your Question
Is it possible to implement a new mode where only month/year are provided?

Something like this: [react-native-month-year-picker](https://www.npmjs.com/package/react-native-month-year-picker)

**Comment by mmazzarolo** [comment]
Hey @limoli, this component doesn't have any native code. This seems to be something you should ask to https://github.com/react-native-community/react-native-datetimepicker (that we're using under the hood).
