### ISSUE TITLE
react-native-community/datetime-picker as a peer dependency in a package with react-native-modal-datetime-picker should fail?

### ISSUE THREAD

**Issue by smriti-spotnana** [mmazzarolo/react-native-modal-datetime-picker#431]
When we say `react-native-modal-datetime-picker` uses `react-native-community/datetime-picker` internally, what does that mean? 
- I installed `react-native-modal-datetime-picker` in my package, and mentioned `react-native-community/datetime-picker` as a peerDependency, and it worked fine. 
- But, according to my understanding, peer dependencies are not installed.
- => I didn't have a `react-native-community/datetime-picker` in my node_modules. 
- so, how did `react-native-modal-datetime-picker` work fine?
- I was just import from `react-native-modal-datetime-picker` in that package, and exporting the DateTimeModal and the types for props, and then importing this package1 into another package2, when I was using the DateTimeModal
- and this package2 did have `react-native-community/datetime-picker` in it's node_modules though
- But, since I do import from the library in package1, => I am making use of this lib, even if it is to just export stuff. Why did package1 not throw any error?

Thank you, 
You can direct me to any articles too! Happy to read and research too. I want to understand this stuff, but not able to find many resources on this

**Comment by smriti-spotnana** [comment]
ok, I just learnt that , although peer dependencies are not installed, but we can still use them and import from them!! This is magic. I will next need to figure out how this is possible

**Comment by mmazzarolo** [comment]
Hey @smriti-spotnana  :)
I'm glad you're figuring out how this all works but this is not the right place for general discussions :/ If you're interested in the topic, I'd suggest you check https://nodejs.org/es/blog/npm/peer-dependencies/
