### ISSUE TITLE
Text color of time or date picker does not show up.  

### ISSUE THREAD

**Issue by summonerriftofficial** [mmazzarolo/react-native-modal-datetime-picker#435]
## Environment

System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.45 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms

iOS

## Versions

- iOS: 13.1
- react-native-modal-datetime-picker: latest
- react-native: latest
- react: latest

## Description

Text color of time or date picker does not show up.  

## Reproducible Demo

![IMG_9846](https://user-images.githubusercontent.com/52756966/83974413-d1e32680-a8f5-11ea-9980-dac0f07c90b5.PNG)

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker#i-cant-see-the-picker-on-iosthe-picker-is-white-on-ios

**Comment by tomgreco** [comment]
@mmazzarolo link doesn't work anymore

**Comment by mmazzarolo** [comment]
@tomgreco thanks, https://github.com/mmazzarolo/react-native-modal-datetime-picker#why-is-the-picker-not-visibletransparent-on-ios
