### ISSUE TITLE
Year does not get update, only Day and Month do update on selection

### ISSUE THREAD

**Issue by hamzaouhssain1993** [mmazzarolo/react-native-modal-datetime-picker#436]
Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 25.0.2, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_221 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^2.9.0 => 2.10.0 
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 

 Platforms

BOTH Android and IOS

 Versions

    "react-native-modal-datetime-picker": "^8.7.1",

Description

In detail, the year does not update if I change it.
If I change and modify the day or the month on the picker, this gets an update and I receive from the picker the new exact day and month.
If I try to change the year, this remains the default one ( in this case 2020 ). and it does not give me the new year selected.
I have tried in ios and android and the problem if in both platforms

To reproduce it: Select a different year than one the pickers gives you as default and see if it gets update

This is my DateTimePicker

        <DateTimePicker
            isVisible={this.isTimePickerVisible}
            onConfirm={this.handleTimePicked}
            onCancel={this.hideTimePicker}
            cancelTextIOS={$t('common.cancel')}
            confirmTextIOS={$t('common.confirm')}
            headerTextIOS={this.pickerMode === 'date' ? $t('screen.summary.pickDate') : $t('screen.summary.pickTime')}
            timePickerModeAndroid="clock"
            date={new Date())}
            mode={"date"}
            minuteInterval={15}
            locale={localeStore.locale}
        />

**Comment by mmazzarolo** [comment]
👋 Please follow the issue template and add a reproducible example.
