### ISSUE TITLE
DatePicker not showing in expo android

### ISSUE THREAD

**Issue by andrewjmac** [mmazzarolo/react-native-modal-datetime-picker#443]
Currently using version: 8.7.1

I've just started to add this to my app, and i'm having an issue rendering the android version. IOS version is working fine

this is my component being called:
 const [showEffectiveDatePicker, setShowEffectiveDatePicker] = useState(false);

 <DatePickerInput
                      setDate={(e) => {
                        setHoursChange({ ...hoursChange, effectiveDate: e });
                      }}
                      dismiss={() => setShowEffectiveDatePicker(false)}
                      mode="date"
                      show={showEffectiveDatePicker}
                    />

//this is my component
function DatePickerInput(props) {
  const [date, setDate] = useState(new Date());
  const [mode, setMode] = useState(props.mode);

  const onChange = (selectedDate) => {
    console.log(selectedDate);
    const currentDate = selectedDate || date;
    setDate(currentDate);
    props.setDate(currentDate);
    props.dismiss();
  };
  return (
    <DateTimePickerModal
      value={date}
      mode={mode}
      display="default"
      isVisible={props.show}
      onConfirm={onChange}
      onCancel={props.dismiss}
    />
  );
}

works fine when showEffectiveDatePicker  is set to true, but not when I change from false to true.

Any help would be grateful

**Comment by mmazzarolo** [comment]
Hey @andrewjmac please follow the issue template before submitting a new issue. Thank you.
