### ISSUE TITLE
Modal titile on Android

### ISSUE THREAD

**Issue by mariobrubio** [mmazzarolo/react-native-modal-datetime-picker#444]
## Modal title on Android

How can I modify the modal title or header text on Android? the feature is there on iOS but is missing on Android.

![image](https://user-images.githubusercontent.com/21285099/87061691-ae9be780-c1d1-11ea-9a0f-77a0433fb3b1.png)

**Comment by mmazzarolo** [comment]
You can't do it, the title on Android is set in the native layer (which is not controlled by this component).
