### ISSUE TITLE
Today's date not getting disabled if future date is selected as minimum date

### ISSUE THREAD

**Issue by hrishiakhade** [mmazzarolo/react-native-modal-datetime-picker#450]
## Platforms

Android 
## Versions

- react-native-modal-datetime-picker: 8.7.1
- react-native: 0.61.5
- react: 16.9.0

## Description

![picturemessage_l5sqsbe0 ko3](https://user-images.githubusercontent.com/20705523/87911732-b9843100-ca89-11ea-8308-46446a2e45c8.png)

1. Two Fields Start date and end date
2. First select start date as any future date . eg, if today is 20 July Select 24 July .
3. Set start date as minimum date for end date datepicker.
4. You will see days before 24 July getting disabled as expected .
5. But today's date 20 July is seen as enabled . But actually it is disabled ,which is correct .
6 . Seems like problem  with styles . Today's date should also be greyed out , but it is not.

## Reproducible Demo
1. Two Fields Start date and end date
2. First select start date as any future date . eg, if today is 20 July Select 24 July .
3. Set start date as minimum date for end date datepicker.
4. You will see days before 24 July getting disabled as expected .
5. But today's date 20 July is seen as enabled . But actually it is disabled ,which is correct .
6 . Seems like problem  with styles . Today's date should also be greyed out , but it is not.

**Comment by mmazzarolo** [comment]
Please follow the issue template. Thanks.
