### ISSUE TITLE
Some dates are not displayed at all

### ISSUE THREAD

**Issue by dmdmd** [mmazzarolo/react-native-modal-datetime-picker#456]
## Environment

real device. iPhone 8

## Platforms

iOS

## Versions

- Android: 4.0 AI-193.6911.18.40.6626763
- iOS: 11.4.1/11E503a - /usr/bin/xcodebuild
- react-native-modal-datetime-picker: "^8.7.1",
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): "2.4.0"
- react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
- react: 16.11.0

## Description

On some iOS devices (not all) there is some strange behaviour where the picker doesn't display all dates:

![ezgif-6-f2aec2ab3c1f](https://user-images.githubusercontent.com/1687895/89329509-34a33500-d68f-11ea-8dc7-6f05bbe13f5f.gif)

As suggested on the issue template, I tried using @react-native-community/datetimepicker and it worked as expected. (*Edited*)

## Reproducible Demo

I pasted some relevant parts of my component for some context.
```
...
const [value, setValue] = useState();
const [showDatePicker, setShowDatePicker] = useState(false);
const show = useCallback(() => {
	setShowDatePicker(true);
}, [setShowDatePicker]);
const hide = useCallback(() => {
	setShowDatePicker(false);
}, [setShowDatePicker]);

const setDate = useCallback(
	(date: Date) => {
		setShowDatePicker(false);
		const newDate = moment(date);
		setValue(newDate);
	},
	[setShowDatePicker, setValue]
);

<View style={localStyles.container}>
	<View style={localStyles.dateContainer}>
		<Text style={[localStyles.date, localStyles.label]}>{label}</Text>
		<TouchableOpacity onPress={show}>
			<Text style={localStyles.date}>{displayDate}</Text>
		</TouchableOpacity>
	</View>
	{showDatePicker && (
		<View style={localStyles.datePickerContainer}>
			<DateTimePickerModal
				isVisible={showDatePicker}
				mode="datetime"
				headerTextIOS={"Set time"}
				minimumDate={minimumDate.toDate()}
				maximumDate={maximumDate.toDate()}
				onConfirm={setDate}
				onCancel={hide}
			/>
		</View>
	)}
</View>
```

Thanks in advance!
Let me know if I can give you more info. I'm using this package mainly to support android devices but it would be nice to still use it for iOS.

*Edited*

**Comment by maharjanaman** [comment]
I can also confirm this with expo sdk 38, react-native-modal-datetime-picker ~> 8.7.1, and @react-native-community/datetimepicker ~> 2.1.0.
I tried to force a light theme with `userInterfaceStyle` but does not seems to work.
Using colorScheme from react-native works but breaks when the theme is changed while the app is running. Have to restart the app to make it work again.

**Comment by mmazzarolo** [comment]
How's it different from:
- https://github.com/mmazzarolo/react-native-modal-datetime-picker#is-the-ios-dark-mode-supported
- and https://github.com/mmazzarolo/react-native-modal-datetime-picker#i-cant-see-the-picker-on-iosthe-picker-is-white-on-ios
?

**Comment by dmdmd** [comment]
I can confirm it happens when dark mode is on. I see now you've had a bunch of similar issues being opened (apologies for being one more, I thought I had to opt-in to support dark mode).

To solve this I was forced to support dark mode by using https://docs.expo.io/versions/latest/sdk/appearance/:
* I've added `"userInterfaceStyle": "automatic",` on `app.json`, 
* used the `useColorScheme` hook to detect the mode and 
* used the `DateTimePickerModal` prop `isDarkModeEnabled={colorScheme === "dark"}`

**Comment by mmazzarolo** [comment]
No worries :) 
Yeah this theming thing is confusing, especially on Expo... not much that we can do on our side to fix it though :/

**Comment by maharjanaman** [comment]
I'm trying to force light theme by providing `"userInterfaceStyle": "light"`, but picker is not respecting the light theme when dark mode is enabled. Anything we can do about this?

**Comment by mmazzarolo** [comment]
@maharjanaman please see 
- https://github.com/mmazzarolo/react-native-modal-datetime-picker#is-the-ios-dark-mode-supported
- and https://github.com/mmazzarolo/react-native-modal-datetime-picker#i-cant-see-the-picker-on-iosthe-picker-is-white-on-ios

and @dmdmd solution's above ☝️

**Comment by mmazzarolo** [comment]
or wait for #458

**Comment by dmdmd** [comment]
Supporting dark-mode because of this component gave me trouble on other parts of my app. So I reverted to supporting only light mode. 
But even with version "8.9.3" I still have this bug. And "@react-native-community/datetimepicker" works correctly.

**Comment by mmazzarolo** [comment]
hey @dmdmd , sorry to hear that. If you could provide a (**complete**) reproducible example of the issue that would be great. I tested the example project and it works correctly for on iPhone 11 (both dark and light mode).

**Comment by dmdmd** [comment]
My code is the same as above. 
Did you try adding `"userInterfaceStyle": "light"` on your app.json and enabling dark-mode on your device?

I think I tracked down the issue to the usage of DatePicker inside a Modal (I replaced the Modal from react-native-modal-datetime-picker code with a View and the bug didn't manifest). I'm not sure if the Modal component is respecting the light mode rule...
