### ISSUE TITLE
Cannot read property 'getColorScheme' of undefined error in iOS emulator

### ISSUE THREAD

**Issue by Badbreaddead** [mmazzarolo/react-native-modal-datetime-picker#463]
## Environment

System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 332.75 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - node_modules/.bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 30.0.0
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.13.1 => 16.13.1 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Platforms

iOS emulator

## Versions

- Android:
- iOS: 12.4
- react-native-modal-datetime-picker: 8.9.1
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 2.6.1
- react-native: 0.61.5
- react: 16.13.1

## Description

To repro just go to screen which uses basic DateTimePicker. I think it only happens in iOS emulator, because I wasn't able to repro it in codesandbox
I tried using the picker from @react-native-community/datetimepicker - it doesn't have this error.

![image](https://user-images.githubusercontent.com/22796205/89823755-b34e1580-db5a-11ea-841b-2df0841afaff.png)

I think the error was introduced in this [PR](https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/459)

**Comment by mslipenchuk267** [comment]
Same issue here

**Comment by gabes-dev** [comment]
Same issue here.
Is there any solution? I need to solve this issue ASAP in production mode.

**Comment by mmazzarolo** [comment]
Thanks all for reporting.
I’ll check it out soon. In the meantime, can’t you downgrade to the
previous minor version?
(The previous npm version bump actually had to be a major).

**Comment by mmazzarolo** [comment]
(Found the issue, fixing it)

**Comment by mslipenchuk267** [comment]
@mmazzarolo 🙏🙏🙏 thank you!

**Comment by mmazzarolo** [comment]
anyone willing to give it a try? 
https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/464

you can install it with: `yarn add "mmazzarolo/react-native-modal-datetime-picker#464/head"`

**Comment by idanCemento** [comment]
> Same issue here.
> Is there any solution? I need to solve this issue ASAP in production mode.

same here 😨

**Comment by mmazzarolo** [comment]
@idanCemento please see the message above. If it works I can publish the fix.

**Comment by kratoskp** [comment]
> @idanCemento please see the message above. If it works I can publish the fix.

LGTM!

**Comment by mmazzarolo** [comment]
v8.9.2 is available, LMK if it looks good
https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v8.9.2

**Comment by gabes-dev** [comment]
> v8.9.2 is available, LMK if it looks good
> https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v8.9.2

Yes, it's working now,
Thanks @mmazzarolo

**Comment by mmazzarolo** [comment]
Thanks for reporting 👍
