### ISSUE TITLE
How add title to datetimpicker in android?

### ISSUE THREAD

**Issue by donny08** [mmazzarolo/react-native-modal-datetime-picker#467]
@mmazzarolo Is there anyway I can add title to datetimpicker in android similar to ios ?

**Comment by mmazzarolo** [comment]
@donny08 ad far as I know, nope. You should check the community datepicker to see if it supports such options but I don't think it should

**Comment by donny08** [comment]
@mmazzarolo Is possible for you to add header component for android picker similar to ios?
