### ISSUE TITLE
Disabling dates

### ISSUE THREAD

**Issue by rafmst** [mmazzarolo/react-native-modal-datetime-picker#469]
Is there any way to disable dates in the past?

Thanks

**Comment by mmazzarolo** [comment]
Hey!
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
This means that if your feature is not supported by these components you won't be able to use it with `react-native-datetime-picker`.

**Comment by pernillelorup** [comment]
You can set the prop 'minimumDate'. This library supports all props from the [@react-native-community/react-native-datetimepicker ](https://github.com/react-native-community/datetimepicker) :)
