### ISSUE TITLE
Request: add minuteInterval prop

### ISSUE THREAD

**Issue by spyshower** [mmazzarolo/react-native-modal-datetime-picker#470]
`minuteInterval` has been added to  [@react-native-community/datetimepicker.](https://github.com/react-native-community/datetimepicker/commit/c6c67382dec08fde3cf5e0f21ce66d891e14e17c)

Can we add it too? :)

**Comment by mmazzarolo** [comment]
@spyshower hey! What's stopping you from already using this prop with `react-native-modal-datetime-picker`? We are passing down to the community picker all the additional props specified on this component 😮

**Comment by spyshower** [comment]
@mmazzarolo Thanks for the quick response! I have been trying to do so for the last hour with no luck. Turns out it's still not working when using @react-native-community/datetimepicker instead so I guess it's an issue with that library, not this one!
