### ISSUE TITLE
IOS time picker is empty, there are no values to pick there

### ISSUE THREAD

**Issue by Luckygirlllll** [mmazzarolo/react-native-modal-datetime-picker#471]
## Environment

 OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 171.88 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.7.5 - /Users/iryna/.rvm/gems/ruby-2.6.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_161 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0 
    react-native: ~0.62.2 => 0.62.2 

## Platforms

IOS

## Versions

- Android: -
- iOS: 13.5
- react-native-modal-datetime-picker: 8.9.3
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 3.0.2
- react-native: 0.62.2
- react:16.11.0 

## Description

IOS time picker is empty, there are no values to pick there. 

```
 <DateTimePickerModal
                testId={props.showTimePicker? "start": "end"}
                isVisible={props.showTimePicker || props.showTimeEndPicker}
                style={
                    props.style
                        ? props.style
                        : { position: 'absolute', top: 5, zIndex: 99, height: 300}
                }
                value={new Date(props.value)}
                mode={'time'}
                display={'spinner'}
                is24Hour={false}
                minDate={new Date(props.minDate)}
                headerTextIOS={"Choose time"}
                onConfirm={props.onChange}
                onCancel={props.onCancel}
            />
```

<img width="387" alt="Screenshot 2020-09-08 at 14 27 53" src="https://user-images.githubusercontent.com/10096433/92476585-7cadfe00-f1df-11ea-99d7-3d889bb11921.png">

**Comment by mmazzarolo** [comment]
👋 we need a fully reproducible example. Also, why are you applying that style? Could you try removing it?

**Comment by Luckygirlllll** [comment]
@mmazzarolo ah, true, `style` is causing a problem, I'm refactoring pickers and forget to remove that style. Thanks, problem is solved!
