### ISSUE TITLE
Issue with iOS 14

### ISSUE THREAD

**Issue by zstuder25** [mmazzarolo/react-native-modal-datetime-picker#473]
## Ask your Question

It seems your library is having issues with iOS 14 and is not quite working as expected. When my Xcode updated today to 12 and iOS 14, we no longer have a spinner available. I've tried using @react-native-community/datetimepicker's `display` prop to set it to `spinner` but to no avail, which may have something to do with this library using an older version of the datetimepicker library. Any help would be appreciated. 
![Screen Shot 2020-09-18 at 4 57 15 PM](https://user-images.githubusercontent.com/8691536/93644453-02942b00-f9d0-11ea-971b-f946067b7569.png)

**Comment by jmdelcarmen** [comment]
@zstuder25 - Ran into the same problem. I `display="spinner"` as a prop. Seems to have fixed it.

Reference: https://www.npmjs.com/package/@react-native-community/datetimepicker#display--optional-

**Comment by ricokahler** [comment]
I'm also experiencing an issue here. I'm using expo un-ejected.

![image](https://user-images.githubusercontent.com/10551026/93655650-dfc73e00-f9f2-11ea-9f85-2e800aa89674.png)

**Comment by mmazzarolo** [comment]
Hola! could you please fill in the issue template?
 
> this library using an older version of the datetimepicker library

`@react-native-community/datetimepicker` is a peer-dependency, so you can/should update it as needed 👍

**Comment by mmazzarolo** [comment]
> oh this might actually be a dark mode issue. I can still feel the spinners if I move it.

Yep. It's likely the issue here. (We do support dark-mode out of the box in the latest version btw)

**Comment by mmazzarolo** [comment]
Might be related to: https://github.com/react-native-community/datetimepicker/issues/280
Can't test it on iOS 14 right now unfortunately :/

**Comment by mmazzarolo** [comment]
Testing it, I'll create a PR soonish setting the default display mode to spinner on iOS. In the future we might also wanna support the new date/time picker though.

**Comment by mmazzarolo** [comment]
Mind checking https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/474

**Comment by praveens96** [comment]
received a single row in bottom sheet. upgraded to 9.0.0 to get it right.

**Comment by RupamShaw** [comment]
upgraded to 9.0.0 but still having same issue

**Comment by mmazzarolo** [comment]
Make sure you completely clean the cache

**Comment by mmazzarolo** [comment]
Also https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/474#issuecomment-696175144

**Comment by sunwooz** [comment]
I was able to fix this by adding a few lines to AppDelegate.m

if (@available(iOS 14, *)) {
    UIDatePicker *picker = [UIDatePicker appearance];
    picker.preferredDatePickerStyle = UIDatePickerStyleWheels
 }

inside the didFinishLaunchingWithOptions function.

**Comment by nescroft** [comment]
@sunwooz i tried this but it seems to have no effect

**Comment by gopikasireddy202** [comment]
> @sunwooz i tried this but it seems to have no effect.. edit: GOT IT... had to set display = 'spinner'

Please tell me which react-native version you can used?

**Comment by nescroft** [comment]
@gopikasireddy202 i am using react native version 0.61.5.. i got it working by setting display = 'spinner' and i also added the code @sunwooz recommends above into the xcode AppDelegate.m file inside the didFinishLaunchingWithOptions function.

**Comment by sunwooz** [comment]
@gopikasireddy202 I'm using React Native 0.59.10. DId you remember to rebuild the project?

**Comment by gopikasireddy202** [comment]
@Sunwoo can you please send any documention  for this ?

**Comment by sunwooz** [comment]
@gopikasireddy202 https://developer.apple.com/documentation/uikit/uidatepicker/3526124-preferreddatepickerstyle?language=objc

**Comment by hzburki** [comment]
> I was able to fix this by adding a few lines to AppDelegate.m
> 
> ```
> if (@available(iOS 14, *)) {
>     UIDatePicker *picker = [UIDatePicker appearance];
>     picker.preferredDatePickerStyle = UIDatePickerStyleWheels
>  }
> ```
> 
> inside the didFinishLaunchingWithOptions function.

@sunwooz you missed a trailing comma on the second line. Thanks for the code! 👍

**Comment by imshreyansh** [comment]
@hzburki can you tell me please where exactly we need to add that trailing comma ?

**Comment by mmazzarolo** [comment]
Pretty sure he meant the semicolon on `picker.preferredDatePickerStyle = UIDatePickerStyleWheels`

**Comment by resting** [comment]
```
if (@available(iOS 14, *)) {
    UIDatePicker *picker = [UIDatePicker appearance];
    picker.preferredDatePickerStyle = UIDatePickerStyleWheels
 }
```
Works, but how do I center it?

Looking like this currently
![image](https://user-images.githubusercontent.com/350530/100446327-9594c400-30e9-11eb-8305-a26e93d5ae22.png)

**Comment by mmazzarolo** [comment]
hm, it should already be centered... what device/logs etc are you using?

**Comment by imshreyansh** [comment]
how to resolve this issue in expo ?

**Comment by komelabbbas** [comment]
how to resolve this issue in expo ?

**Comment by komelabbbas** [comment]
I have try many things but not work.
Plz give me any solution to solve ios 14 date picker in expo

**Comment by s-rayed** [comment]
> I have try many things but not work.
> Plz give me any solution to solve ios 14 date picker in expo

+1 i have the issue in prod. Got users complaining, not sure where to go with this

**Comment by imshreyansh** [comment]
@s-rayed I think the best you can do right now is to have different libraries on both the Platforms **(IOS & Android)**,
for time being on **IOS** you can use library **react-native-modal-datetime-picker**,
and for Android you can use library **@react-native-community/datetimepicker**

**Comment by s-rayed** [comment]
> @s-rayed I think the best you can do right now is to have different libraries on both the Platforms **(IOS & Android)**,
> for time being on **IOS** you can use library **react-native-modal-datetime-picker** example:
> <DateTimePicker
> isVisible={this.state.dateVisible}
> mode='date'
> onConfirm={(date) => this.handleDatePicked(date, 'dateVisible')}
> onCancel={() => this.hideDateTimePicker('dateVisible')}
> **display={Platform.OS === "ios" ? "inline" : "default"}** //don't forget to add this line on IOS
> />
> and for Android you can use library **@react-native-community/datetimepicker**
> <DateTimePicker
> testID="dateTimePickerTwo"
> value={this.state.date ? new Date(this.state.date) : new Date()}
> mode="date"
> is24Hour={true}
> display="default"
> onChange={(date) => this.handleDatePicked(date, 'dateVisible')}
> />

Unfortunately my problem is with ios, android works fine, I suppose I could replace ios with the community version. Thank you

**Comment by komelabbbas** [comment]
Now it working perfectly.
I have upgrade expo sdk to latest  and also update react-native-modal-datetime-picker.

**Comment by abdo17rabah** [comment]
How can i update react-native-modal-datetime-picker?

**Comment by abdulrahman18** [comment]
@mmazzarolo same issue happen in IOS 14.4 using expo 

Date Time Picker : 
"@react-native-community/datetimepicker": "3.0.9",
"react-native-modal-datetime-picker": "^9.1.0",

Expo version :
"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",

This is my code 

<DateTimePickerModal
    isVisible={endDatePickerVisible}
    headerTextIOS="Pick a Date"
    minimumDate={new Date(createEventObject.startsAt)}
    display={Platform.OS === "ios" ? "spinner" : "default"}
    mode="date"
    date={new Date(createEventObject.endsAt)}
    onConfirm={handleEndConfirm}
    onCancel={hideDatePicker}
    isDarkModeEnabled={colorTheme === "dark"}
/>

**Comment by methineeinkan** [comment]
> I'm also experiencing an issue here. I'm using expo un-ejected.
> 
> Edit: oh this might actually be a dark mode issue. I can still feel the spinners if I move it.
> 
> ![image](https://user-images.githubusercontent.com/10551026/93655650-dfc73e00-f9f2-11ea-9f85-2e800aa89674.png)

howto fix

**Comment by abdulrahman18** [comment]
@methineeinkan update your modal date picker library.

**Comment by thanhandp147** [comment]
> ```
> if (@available(iOS 14, *)) {
>     UIDatePicker *picker = [UIDatePicker appearance];
>     picker.preferredDatePickerStyle = UIDatePickerStyleWheels
>  }
> ```
> 
> Works, but how do I center it?
> On 6.0.0
> 
> Looking like this currently
> ![image](https://user-images.githubusercontent.com/350530/100446327-9594c400-30e9-11eb-8305-a26e93d5ae22.png)
> 
> Ended up applying a style to it.
> Is there a better solution?
> 
> ```
> datePickerContainerStyleIOS={{paddingHorizontal: 40}}
> ```

justifyContent: 'center

**Comment by mynameisafzal** [comment]
> hm, it should already be centered... what device/logs etc are you using?

iphone 12 and ios 14.4

**Comment by Sargnec** [comment]
> ```
> if (@available(iOS 14, *)) {
>     UIDatePicker *picker = [UIDatePicker appearance];
>     picker.preferredDatePickerStyle = UIDatePickerStyleWheels
>  }
> ```
> 
> Works, but how do I center it?
> On 6.0.0
> 
> Looking like this currently
> ![image](https://user-images.githubusercontent.com/350530/100446327-9594c400-30e9-11eb-8305-a26e93d5ae22.png)
> 
> Ended up applying a style to it.
> Is there a better solution?
> 
> ```
> datePickerContainerStyleIOS={{paddingHorizontal: 40}}
> ```

Mine worked with `pickerContainerStyleIOS={{justifyContent:"center",paddingHorizontal:40}}`

**Comment by kawaljain** [comment]
I am also experiencing an issue here. I found its a styling issue in my case.
 I got it working by setting **isDarkModeEnabled={true}** 
 or
 I also added the style
  pickerContainerStyleIOS={{
    backgroundColor: "black",
    paddingHorizontal: 40
  }}
 **<DateTimePickerModal
    isVisible={this.state.showDatePicker}
    mode="date"
    onConfirm={this.handleDateSelected}
    onCancel={this.hideDatePicker}
    // isDarkModeEnabled={true}
    pickerContainerStyleIOS={{
      backgroundColor: "black",
    }}
/>**

**Comment by iamshivamsingh** [comment]
Add this in your info.plist
```
<key>UIUserInterfaceStyle</key>
<string>Light</string>
```

**Comment by KhoaN56** [comment]
> > I'm also experiencing an issue here. I'm using expo un-ejected.
> > Edit: oh this might actually be a dark mode issue. I can still feel the spinners if I move it.
> > ![image](https://user-images.githubusercontent.com/10551026/93655650-dfc73e00-f9f2-11ea-9f85-2e800aa89674.png)
> 
> howto fix

**Comment by aniruddhbhamare** [comment]
> ```
> if (@available(iOS 14, *)) {
>     UIDatePicker *picker = [UIDatePicker appearance];
>     picker.preferredDatePickerStyle = UIDatePickerStyleWheels
>  }
> ```
> 
> Works, but how do I center it?
> On 6.0.0
> 
> Looking like this currently
> ![image](https://user-images.githubusercontent.com/350530/100446327-9594c400-30e9-11eb-8305-a26e93d5ae22.png)
> 
> Ended up applying a style to it.
> Is there a better solution?
> 
> ```
> datePickerContainerStyleIOS={{paddingHorizontal: 40}}
> ```

hello , did you get any other solution for this ?
