### ISSUE TITLE
Dark mode picker showing blank in iOS 14.

### ISSUE THREAD

**Issue by ketanpatel3377** [mmazzarolo/react-native-modal-datetime-picker#476]
## Description
In Dark mode only showing cancel and confirm button calendar and date not showing but working when scroll.

## Platforms

**iOS**

## Versions

- iOS:
- react-native-modal-datetime-picker 9.0.0

![IMG_2349](https://user-images.githubusercontent.com/49754298/94339567-71990180-0018-11eb-9d03-989521099634.png)

**Comment by mmazzarolo** [comment]
Dark-mode is supported out of the box. Make sure you're using the latest version of react-native-modal-datetime-picker and of the community picker. If it still doesn't work, please follow the issue template in its entirety and create a reproducible repo example 👍 Thanks!

**Comment by shkavro** [comment]
@ketanpatel3377 I've fixed the issue with setting up userInterfaceStyle: 'automatic' in app.config.js.

**Comment by Canser** [comment]
I am not using expo hence I do not have an app.config.js file. Re-installed new versions of both packages but did not work.

Do you know how can we fix this?

**Comment by soullivaneuh** [comment]
The @shkavro solution is right.

@Canser You may have a `app.json` file. It is the same thing:

```json
{
  "expo": {
    "name": "Project",
    "slug": "project",
    "privacy": "unlisted",
    "platforms": ["ios", "android", "web"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "automatic",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "icon": "./assets/icon.android.png"
    }
  }
}
```

**Comment by jota12x** [comment]
I just run into this problem and @soullivaneuh 's solution worked perfectly. Thanks!

**Comment by SamiChab** [comment]
I use iOS 14 with dark mode. I just set `"userInterfaceStyle": "automatic"` in `app.json` (I don't use Expo) before rebuilding. But no success, the picker shows a blank content...

**Comment by enormousrodent** [comment]
Can we have a NON expo specific answer to this please like @SamiChab mentioned above?

**Comment by SamiChab** [comment]
I solved it by setting `themeVariant={'light'}`

**Comment by ujnimz** [comment]
My working code (Thanks to all the contributors):

```
import React from 'react';
import {Appearance} from 'react-native';

const colorScheme = Appearance.getColorScheme();

const [isDark, setIsDark] = React.useState(colorScheme === 'dark');

React.useEffect(() => {
    setIsDark(colorScheme === 'dark');
  }, [colorScheme]);

const DateSelect = () => {
return (
<DateTimePickerModal
        isVisible={isDatePickerVisible}
        mode='date'
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
        isDarkModeEnabled={isDark}
        themeVariant={isDark ? 'dark' : 'light'}
      />)
}

```
