### ISSUE TITLE
minuteInterval prop not working in iOS 14

### ISSUE THREAD

**Issue by shariqwaseem** [mmazzarolo/react-native-modal-datetime-picker#477]
## Environment

System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 56.50 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.0. - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms
iOS only

## Versions

- Android:nan
- iOS:14.0
- react-native-modal-datetime-picker:8.9.3
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):3.0.1
- react-native:0.63.2
- react:16.13.1

## Description
The minuteInterval prop for DateTimePickerModal does not work on iOS 14.0. Please fix this. Thank you.

## Reproducible Demo

`<DateTimePickerModal
          isVisible={isTimePickerVisible}
          mode="time"
          minuteInterval={30}
          date={new Date(time)}
          // value={}
          onConfirm={handleConfirmTimePicker}
          onCancel={hideTimePicker}
        />`

**Comment by mmazzarolo** [comment]
Please use the latest version of `react-native-modal-datetime-picker` and follow the issue template. Thanks.
