### ISSUE TITLE
How Can I disable Current Dates and Future Dates?

### ISSUE THREAD

**Issue by lavarajallu** [mmazzarolo/react-native-modal-datetime-picker#48]
I am using this Module But How Can I Disable Future and Current Dates...

```
_handleDatePicked = (date) => {
    var DateFormat =  moment(date).format("YYYY-MM-DD");
     console.log('A date has been picked:'+DateFormat);

     var d1 =new Date();
    d1.setHours(0,0,0,0)
     var d = new Date(DateFormat);
     d.setHours(0,0,0,0)
    var n = d.getDate();
    var m = d1.getDate();
    
    if(m < n){
        Alert.alert("Hello", 'Current Date and Future Dates Not allowing')  
        console.log("n:"+n +":"+"m:"+m) 
        }
        else{
           this.setState({
          DateOfBirth:DateFormat
         })
       } 
     this._hideDateTimePicker();
   };
```
This Code Is Not Allowing Future Dates But Allowing CurrentDate , I want Disable Current Date Also

**Comment by lavarajallu** [comment]
```
 _handleDatePicked = (date) => {
    var DateFormat =  moment(date).format("YYYY-MM-DD");
     console.log('A date has been picked:'+DateFormat);

     var d1 =new Date();
    d1.setHours(0,0,0,0)
     var d = new Date(DateFormat);
     d.setHours(0,0,0,0)
    var n = d.getDate();
    var m = d1.getDate();
    
    if(m < n){
        Alert.alert("Hello", 'Current Date and Future Dates Not allowing')  
        console.log("n:"+n +":"+"m:"+m) 
        }
        else{
           this.setState({
          DateOfBirth:DateFormat
         })
       } 
     this._hideDateTimePicker();
   };
```

This Code Is Not Allowing Future Dates But Allowing CurrentDate

**Comment by mmazzarolo** [comment]
Hey @lavarajallu, sorry for answering so late. Are you still having the issue?  
I'm on vacation right now, I'll take a look at it when I'll be back.

**Comment by khairunnisaa** [comment]
how can you resolve this issue?

**Comment by SL-A-SH** [comment]
To block future dates initialize your DateTimePicker with maximumDate prop likes so:

```
<DateTimePicker
   isVisible={this.state.isDateTimePickerVisible}
   maximumDate={new Date()}
   onConfirm={this.handleDatePicked}
   onCancel={this.hideDateTimePicker}
/>
```

**Comment by Husnac123** [comment]
> To block future dates initialize your DateTimePicker with maximumDate prop likes so:
> 
> 
> 
> ```
> 
> <DateTimePicker
> 
>    isVisible={this.state.isDateTimePickerVisible}
> 
>    maximumDate={new Date()}
> 
>    onConfirm={this.handleDatePicked}
> 
>    onCancel={this.hideDateTimePicker}
> 
> />
> 
> ```
> 
> 
> 
> To block current date use maximumDate like so:
> 
> 
> 
> ```
> 
> <DateTimePicker
> 
>    isVisible={this.state.isDateTimePickerVisible}
> 
>    onConfirm={this.handleDatePicked}
> 
>    maximumDate={new Date(Date.now() - 86400000)}
> 
>    onCancel={this.hideDateTimePicker}
> 
> />
> 
> ```

Is it done in Html?

**Comment by xerosource01** [comment]
To disable future dates in a ReactJS component, you can use JavaScript's Date object and compare the selected date with the current date. If the selected date is in the future, you can prevent the change and display an error message, or simply ignore the change.

Here is an example of how to disable future dates in a date picker component:

```
 import React, { useState } from 'react';
    
    const DatePicker = () => {
      const [selectedDate, setSelectedDate] = useState(new Date());
      const handleDateChange = (date) => {
        const currentDate = new Date();
        if (date > currentDate) {
          alert("Cannot select a future date");
        } else {
          setSelectedDate(date);
        }
      };
    
      return (
        <input
          type="date"
          value={selectedDate.toISOString().substr(0, 10)}
          onChange={(event) => handleDateChange(new Date(event.target.value))}
        />
      );
    };
    
    export default DatePicker;
```

Another way to achieve the same result is to use the max attribute of the input element. You can set the max attribute to the current date, which will prevent the user from selecting any future dates. Here's an example:

```
import React, { useState } from 'react';
    
    const DatePicker = () => {
      const [selectedDate, setSelectedDate] = useState(new Date());
    
      const handleDateChange = (event) => {
        setSelectedDate(new Date(event.target.value));
      };
    
      return (
        <input
          type="date"
          value={selectedDate.toISOString().substr(0, 10)}
          onChange={handleDateChange}
          max={new Date().toISOString().substr(0, 10)}
        />
      );
    };
    
    export default DatePicker;

```
You can also add a custom validation method to validate the selected date before setting it as the selectedDate state. You can add an error message to be displayed when the selected date is in the future, for example. Here's an example:

```
import React, { useState } from 'react';
    
     const DatePicker = () => {
      const [selectedDate, setSelectedDate] = useState(new Date());
      const [error, setError] = useState(null);
    
      const handleDateChange = (event) => {
        const selected = new Date(event.target.value);
        const currentDate = new Date();
        if (selected > currentDate) {
          setError("Cannot select a future date");
        } else {
          setSelectedDate(selected);
          setError(null);
        }
      };
    
      return (
        <>
          <input
            type="date"
            value={selectedDate.toISOString().substr(0, 10)}
            onChange={handleDateChange}
          />
          {error && <p style={{ color: "red" }}>{error}</p>}
        </>
      );
    };
    
    export default DatePicker;
```


This will allow you to validate the selected date and provide feedback to the user if the selected date is in the future.

[Source..](https://xerosource.com/how-to-disable-future-date-in-react-datepicker/)

How Can I disable Current Dates ReactJs

To disable the current date in a ReactJS component, you can use JavaScript's Date object and compare the selected date with the current date. If the selected date is the current date, you can prevent the change and display an error message, or simply ignore the change.

Here is an example of how to disable the current date in a date picker component:

```
import React, { useState } from 'react';

const DatePicker = () => {
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [error, setError] = useState(null);

  const handleDateChange = (event) => {
    const selected = new Date(event.target.value);
    const currentDate = new Date();
    if (selected.getTime() === currentDate.getTime()) {
      setError("Cannot select the current date");
    } else {
      setSelectedDate(selected);
      setError(null);
    }
  };

  return (
    <>
      <input
        type="date"
        value={selectedDate.toISOString().substr(0, 10)}
        onChange={handleDateChange}
      />
      {error && <p style={{ color: "red" }}>{error}</p>}
    </>
  );
};

export default DatePicker;
```

This will allow you to validate the selected date and provide feedback to the user if the selected date is the current date.
