### ISSUE TITLE
Class Component

### ISSUE THREAD

**Issue by gopikasireddy202** [mmazzarolo/react-native-modal-datetime-picker#486]
Hi ,

I am using react-native-cli: 2.0.1 react-native: 0.59.8 and also using class component.Can you please share code for class component for react-native-modal-datetime-picker v9.0.0 for iOS 14.

Can you suggest which version i am use for resolved this issue?

I am using below code in my project. But v9.0.0 having useState.Please share v9.0.0 code of below class component for iOS 14.

import React, { Component } from "react";
import { Button, View } from "react-native";
import DateTimePicker from "react-native-modal-datetime-picker";
 
export default class DateTimePickerTester extends Component {
  constructor(props) {
    super(props);
    this.state = {
      isDateTimePickerVisible: false
    };
  }
 
  showDateTimePicker = () => {
    this.setState({ isDateTimePickerVisible: true });
  };
 
  hideDateTimePicker = () => {
    this.setState({ isDateTimePickerVisible: false });
  };
 
  handleDatePicked = date => {
    console.log("A date has been picked: ", date);
    this.hideDateTimePicker();
  };
 
  render() {
    return (
      <>
        <Button title="Show Picker" onPress={this.showDateTimePicker} />
        <DateTimePicker
          isVisible={this.state.isDateTimePickerVisible}
          onConfirm={this.handleDatePicked}
          onCancel={this.hideDateTimePicker}
        />
      </>
    );
  }
}

**Comment by mmazzarolo** [comment]
```js
import React, { Component } from "react";
import { Button, View } from "react-native";
import DateTimePicker from "react-native-modal-datetime-picker";

export default class DateTimePickerTester extends Component {
  constructor(props) {
    super(props);
    this.state = {
      isDateTimePickerVisible: false
    };
  }

  showDateTimePicker = () => {
    this.setState({ isDateTimePickerVisible: true });
  };

  hideDateTimePicker = () => {
    this.setState({ isDateTimePickerVisible: false });
  };

  handleDatePicked = date => {
    console.log("A date has been picked: ", date);
    this.hideDateTimePicker();
  };

  render() {
    return (
      <>
        <Button title="Show DatePicker" onPress={this.showDateTimePicker} />
        <DateTimePicker
          isVisible={this.state.isDateTimePickerVisible}
          onConfirm={this.handleDatePicked}
          onCancel={this.hideDateTimePicker}
        />
      </>
    );
  }
}
```

**Comment by gopikasireddy202** [comment]
> ```js
> import React, { Component } from "react";
> import { Button, View } from "react-native";
> import DateTimePicker from "react-native-modal-datetime-picker";
> 
> export default class DateTimePickerTester extends Component {
>   constructor(props) {
>     super(props);
>     this.state = {
>       isDateTimePickerVisible: false
>     };
>   }
> 
>   showDateTimePicker = () => {
>     this.setState({ isDateTimePickerVisible: true });
>   };
> 
>   hideDateTimePicker = () => {
>     this.setState({ isDateTimePickerVisible: false });
>   };
> 
>   handleDatePicked = date => {
>     console.log("A date has been picked: ", date);
>     this.hideDateTimePicker();
>   };
> 
>   render() {
>     return (
>       <>
>         <Button title="Show DatePicker" onPress={this.showDateTimePicker} />
>         <DateTimePicker
>           isVisible={this.state.isDateTimePickerVisible}
>           onConfirm={this.handleDatePicked}
>           onCancel={this.hideDateTimePicker}
>         />
>       </>
>     );
>   }
> }
> ```

When I use this code app is crashed. Please find the screenshot.
I am using react-native version : 0.59.8,16.6.3 for react-native-modal-datepicker.
In updated this library to 9.0.0 and react-native-datetimepicker - 3.0.4. 
Xcode:12.0.1,iOS 14.
Can you please send the version details  for  react-native version : 0.59.8,16.6.3 
![IMG_0438](https://user-images.githubusercontent.com/43564071/96703172-2b815480-13b0-11eb-8b39-a8ab2f978069.PNG)
