### ISSUE TITLE
DatePicker Alignment in iOS 14

### ISSUE THREAD

**Issue by gopikasireddy202** [mmazzarolo/react-native-modal-datetime-picker#488]
Hi Team,

I am using the react-native-modal-datetime-picker": "^6.0.0 for react-native : 0.59.0,react:16.6.3,Xcode:12.0.1,iOS :14.

The DatePicker show current date with no spinner for this i am added native code in AppDelegate didFinishLaunchingWithOptions 
if (@available(iOS 14, *)) {
  UIDatePicker *picker = [UIDatePicker appearance];
  picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
}
 
After this native code DatePicker show all dates and spinner at left side in iPhone and iPad.
Can you please resolve this datepicker at center in both iPhone and iPad.

![DatePicker_iPhone](https://user-images.githubusercontent.com/43564071/97007286-cddf3a80-155e-11eb-8541-82812d9c6b2d.png)
![DatePicker_iPad](https://user-images.githubusercontent.com/43564071/97007308-d5064880-155e-11eb-8cdd-dd0513045711.jpg)
![DatePicker](https://user-images.githubusercontent.com/43564071/97007919-c2d8da00-155f-11eb-91bd-0ab49cc4bc9c.jpg)

**Comment by mmazzarolo** [comment]
Hi @gopikasireddy202 , sorry but we don't provide support for older versions. Your best bet is updating to the latest and check if the issue is fixed there

**Comment by Total-Drive** [comment]
Hi mmazzarolo, 
                  I am using the latest version 2.6.2, I am also facing the same issue. I tried to change the position but it's not working.

**Comment by vb-ben** [comment]
> Hi mmazzarolo,
> I am using the latest version 2.6.2, I am also facing the same issue. I tried to change the position but it's not working.

@Total-Drive , I think you can try to upgrade @react-native-community/datetimepicker to the latest version.
![image](https://user-images.githubusercontent.com/5819750/106232212-03628680-6226-11eb-9612-6545743103b0.png)

**Comment by waqaramjad** [comment]
I am using latest version still have same issue
