### ISSUE TITLE
Chrome debugger crashes on DateTimePickerModal rendering : "Calling synchronous methods on native modules is not supported in Chrome" #316

### ISSUE THREAD

**Issue by SkipCat** [mmazzarolo/react-native-modal-datetime-picker#489]
I swapped react-native-datetime-picker with [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker) and the crash does not happen.

## Environment
```
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 42.18 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.1, 28.0.3, 29.0.2
      System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.1 AI-173.4819257
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_171 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.12.0 => 16.12.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found
```
## Platforms

i have tested only on iOS, but I believe it is related to both.

## Versions

branch master 

- Android:
- iOS: 13.6
- react-native-modal-datetime-picker: 9.0.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 2.6.2
- react-native: 0.62.0
- react: 16.12.0
- React Native Debugger 0.10.6

## Description

As said in the title, I get this error when debugging on an iOS simulator (not tried on Android) with the React Native Debugger desktop app.

<img width="396" alt="Capture d’écran 2020-10-23 à 17 44 39" src="https://user-images.githubusercontent.com/17815245/97028894-0251f700-155d-11eb-9e88-3be96744b6a1.png">

When debug mode is off, there is no error.
I tried to remove all props from DateTimePickerModal to see if any could have triggered the error, but even then the crash still happens.

## Reproducible Demo

I do not know how to provide a reproducible demo for this, and I can not provide code as it belongs to my company. As I said, simply rendering `<DateTimePickerModal />` without any prop will crash when you are in Debug mode.

**Comment by mmazzarolo** [comment]
Running the example (from the example dir) works fine:
![image](https://user-images.githubusercontent.com/9536354/97037241-4d720700-1569-11eb-9d1c-163b6be1c7a0.png)

Make sure you update the community datepicker, 2.6.2 is not supported.

**Comment by SkipCat** [comment]
Hello, I followed your advice and upgraded the community date picker to the latest version (3.0.4), but the error still happens in debug mode :/ 

<img width="564" alt="Capture d’écran 2020-10-26 à 12 15 39" src="https://user-images.githubusercontent.com/17815245/97166267-47587200-1785-11eb-9c4f-89600df54439.png">
<img width="570" alt="Capture d’écran 2020-10-26 à 12 16 02" src="https://user-images.githubusercontent.com/17815245/97166273-47f10880-1785-11eb-963d-59792b44ad07.png">

**Comment by SkipCat** [comment]
Is there any news on this? I still have this issue

**Comment by cesar3030** [comment]
I still have the issue too. Any update? 
Can this be reopened?

**Comment by nlabofa** [comment]
Any update on this?

**Comment by mmazzarolo** [comment]
From the issue template:

> ## Reproducible Demo
> 
> Let us know how to reproduce the issue. Include a code sample or share a project that reproduces the issue.
> Follow the guidelines for providing a minimal example: https://stackoverflow.com/help/mcve
> Please notice that WE WON'T SUPPORT ISSUE REPORTS THAT DON'T HAVE A MINIMAL REPRODUCIBLE EXAMPLE.
