### ISSUE TITLE
onHideAfterConfirm is not working 

### ISSUE THREAD

**Issue by loomis17** [mmazzarolo/react-native-modal-datetime-picker#49]
onHideAfterConfirm behavior does not work at all on both Android and iOS.
By looking at both "index.js", master branch seems to indicate the behavior is implemented and supported. Nevertheless, this implementation is not observed after performing an "npm install react-native-modal-datetime-picker". There is no mention of onHideAfterConfirm in the code that is retrieved by npm install.

EDIT - Version I'm running:
react-native-cli: 2.0.1
react-native: 0.44.0
react-native-modal-datetime-picker@4.6.0

**Comment by mmazzarolo** [comment]
Ops, that feature wasn't available in `v4.6.0`, but [I just published it on the new `v4.7.0`](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v4.7.0).
