### ISSUE TITLE
DateTimePicker + Firebase in iOS is not working

### ISSUE THREAD

**Issue by pavan88** [mmazzarolo/react-native-modal-datetime-picker#490]
## Environment

```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 214.79 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

## Platforms

 iOS only

## Versions

- Android:
- iOS: >13
- react-native-modal-datetime-picker: 9.x
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): >8.x
- react-native: 0.63.x
- react:  >16

## Description

** BUILD FAILED **

**The following build commands failed:
	PhaseScriptExecution [CP-User]\ [RNFB]\ Crashlytics\ Configuration /Users/BOOMUSERS/Library/Developer/Xcode/DerivedData/AwesomeProject-cjigvyhstzsvkogrcanxseiamjcg/Build/Intermediates.noindex/AwesomeProject.build/Debug-iphonesimulator/AwesomeProject.build/Script-F2FF2BB742AFFCD4435BA327.sh
(1 failure)**

### package.json
```
 "dependencies": {
    "@react-native-community/datetimepicker": "^3.0.3",
    "@react-native-firebase/app": "^8.4.5",
    "@react-native-firebase/auth": "^9.2.7",
    "@react-native-firebase/crashlytics": "^8.4.9",
    "react": "16.13.1",
    "react-native": "0.63.3",
   "react-native-modal-datetime-picker": "^9.0.0"
  },
```
```
const App = ({navigation}) => {
const [visible, setVisible] = useState(false);
const [date, setDate] = useState(undefined);
 const showDateTimePicker = () => {
    setVisible(true);
  };

  const hideDateTimePicker = () => {
    setVisible(false);
  };

  const handleDatePicked = (date) => {
    hideDateTimePicker();
    console.log('Selected Date'+ date)
  };

     return( <SafeAreaView>
  
          <Button
            title={date !== undefined ? date : 'Ride Time'}
            color="#007ff5"
            onPress={() => showDateTimePicker()}
          />
          <DateTimePicker
            //              date={new Date()}
            mode={'datetime'}
            isVisible={visible}
            is24Hour={true}
            onConfirm={handleDatePicked}
            onCancel={hideDateTimePicker}
            minuteInterval={5}
          />
      </SafeAreaView>
  );
};


export default App;
```
**With FB/crashlytics Adding dependency failed to compile the code**

**Comment by mmazzarolo** [comment]
👋  @pavan88 , react-native-modal-datetime-picker doesn't have anything to do with firebase, you should make sure you're able to pin down the issue on one of these two libs and report it with a complete reproducible example in the right repo.

**Comment by pavan88** [comment]
Its completely reproducible , I have configurations in my to capture the crash-analytics . if required I will share the git code , I assume sharing the package.json and App.js will help in understanding the issue and help in reproduction.

**Steps to reproduce:-**
1. react-native init HelloWorld
2. update the package.json with above dependence 
3. replace the App.js with above code

**Comment by mmazzarolo** [comment]
Please follow these step:
1. Start with the same example in the `example` dir
2. If it works, add firebase
3. If it doesn't work anymore, then it's probably a firebase issue, not an issue of the picker
