### ISSUE TITLE
 Date and time Picker model component  not showing perfectly on IOS 14

### ISSUE THREAD

**Issue by manishpandia** [mmazzarolo/react-native-modal-datetime-picker#491]
## Versions

- iOS: 14.0
- react-native-modal-datetime-picker: 7.6.0
- react-native:0.59.10
- react:16.6.3
- Xcode : 12.1 

## Description
we are not getting the model which mentioned in the example, it is working fine in version 13.6 

![IMG_0304](https://user-images.githubusercontent.com/73522277/97274839-337f3f80-185b-11eb-8711-0539a427f51d.PNG)

![IMG_0305](https://user-images.githubusercontent.com/73522277/97275368-e6e83400-185b-11eb-8da9-d65491497d15.PNG)

**Comment by mmazzarolo** [comment]
Please update your version of the community datetime picker, see #473
