### ISSUE TITLE
locale not working

### ISSUE THREAD

**Issue by royaldragonit** [mmazzarolo/react-native-modal-datetime-picker#498]
<DateTimePickerModal
          isVisible={this.state.pickerMode !== null}
          mode={this.state.pickerMode}
          onConfirm={this.handleConfirm}
          onCancel={this.hidePicker}
          locale="vi_VN"
/>

I'm Selected 23h25 but it return 16h25

**Comment by daonamutc1** [comment]
Ông fix được lỗi này chưa? Tôi để locale="vi" thì ngày tháng chuyển thành tiếng Việt. Nhưng các button vẫn là tiếng Anh.

**Comment by royaldragonit** [comment]
> Ông fix được lỗi này chưa? Tôi để locale="vi" thì ngày tháng chuyển thành tiếng Việt. Nhưng các button vẫn là tiếng Anh.

Được rồi nhưng lâu rồi nên quên mất, nhớ là custom riêng á.
Với lại React Native cùi lắm. 
Code thuần vẫn hơn bác ơi. 
Đụng sâu sâu tý là lag vãi nồi ra :3

**Comment by daonamutc1** [comment]
Bên react-native-modal-datetime-picker có hỗ trợ hiển thị trên modal rồi.
Nó thêm prop: open
