### ISSUE TITLE
UI bug since iOS14 update

### ISSUE THREAD

**Issue by Fantomiald** [mmazzarolo/react-native-modal-datetime-picker#499]
## Environment

System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 631.33 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms

Expo on iOS14

## Versions

- iOS: 14
- react-native-modal-datetime-picker:  8.5.4
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 2.4.0
- react-native: 38.0.2
- react: 16.13.1

## Description

Since the iOS14 update, i have an UI issue with the modal. As you can see on the screenshot, it is displaying the date in compact mode. I had a look to similar issues and tried to use the display props and assigned it the `Platform.OS === 'ios' ? 'inline' : 'default'` value, but it is not working as expected. I would like to get the spinner version back.

![IMG_1232](https://user-images.githubusercontent.com/35847747/100855376-633ceb00-348a-11eb-9bfc-8fa39797fdac.jpg)

## Reproducible Demo

I'm using the datepicker like this:

`<DateTimePickerModal
      display={Platform.OS === 'ios' ? 'inline' : 'default'}
      isVisible={isVisible}
      mode={mode || 'date'}
      date={date}
      onConfirm={handleConfirm}
      onCancel={handleCancel}
      minimumDate={minimumDate}
    />`

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/473
