### ISSUE TITLE
how to show date and time?

### ISSUE THREAD

**Issue by itcurves** [mmazzarolo/react-native-modal-datetime-picker#5]
I was trying to change the mode prop to 'datetime' but it is not working, how I can show date and time, and I am talking about both iphone and ios.

Thank you

**Comment by mmazzarolo** [comment]
Hi!
What do mean by 'not working'? Let me know :)

**Comment by itcurves** [comment]
I want datetime both for selection, it looks like it shows the date and time but with this:

ExceptionsManager.js:78 Warning: Failed prop type: Invalid prop `mode` of value `datetime` supplied to `CustomDatePickerIOS`, expected one of ["date","time"].

**Comment by mmazzarolo** [comment]
I just tried It and it is working correctly for me.
Please make sure you're using the latest version: `npm install --save react-native-modal-datetime-picker@2.0.3`.

Let me know if it works :)


![simulator screen shot 24 ott 2016 19 21 58](https://cloud.githubusercontent.com/assets/9536354/19656169/25783220-9a1f-11e6-84a3-3c7b308c7ff8.png)

**Comment by itcurves** [comment]
@mmazzarolo Thank you so much I was accidentally using a lot older version.

Thank you

**Comment by mubashiralisiddiqui** [comment]
@mmazzarolo  i have use this but it only pick the date not the time its a datepicker only??

**Comment by mmazzarolo** [comment]
@mubashiralisiddiqui 
you should check the `mode` prop in the readme

**Comment by mubashiralisiddiqui** [comment]
@mmazzarolo  thanks it was my mistake
