### ISSUE TITLE
Feature request: option to force timezone

### ISSUE THREAD

**Issue by ramsestom** [mmazzarolo/react-native-modal-datetime-picker#50]
Currently the picker return a complete date with the local timezone. When picking a date like a birthdate, it can be an issue. For example if my device local timezone is UTC+01 and I select 2000-01-01 as my birthdate, the picker would return  2000-01-01 00:00:00+01. If I convert it to UTC(z) (the default date format used by JSON for example) it would be converted to 1999-12-31:23:00:00.000Z. 
So it would be good to have an option to tell the picker that the returned date should have no timezone (wich would result to UTC+0) or, better, to enforce it's timezone (in which case it could be set to 0 if we want UTC+0 but also any other value like -5 if we want UTC-5 for example). If this option is not set, returned dates would default to use the local timezone of course.

**Comment by mmazzarolo** [comment]
Hey @ramsestom, thanks for opening the issue.  
I'm on vacation right now, do you think you'll be able to send a PR with this feature?  
Otherwise I'll take a look at it when I'll be back.  
Thanks!

**Comment by ramsestom** [comment]
Hi @mmazzarolo . Finally did it out of the react-native-modal-datetime-picker component with moment.js. So not sure it is necessary to bother including this functionality in the component itself actually.

**Comment by mmazzarolo** [comment]
Thank you for the answer :)

**Comment by pencilcheck** [comment]
@ramsestom How did you do it? Did you use moment-timezone and remove the timezone part and swap into the local timezone and then do it back once set? Or something else?
