### ISSUE TITLE
Does this  package supports entering date manually as shown in the image?

### ISSUE THREAD

**Issue by Yandamuri** [mmazzarolo/react-native-modal-datetime-picker#500]
## Ask your Question

![Capture](https://user-images.githubusercontent.com/31983789/100990212-a628bc80-3577-11eb-9d52-5193768267ed.PNG)

Usually date pickers allow users to select any date from the calendar. Besides to that I want to allow user to enter date manually as shown in the image.

**Comment by mmazzarolo** [comment]
👋 This component just wraps the native date-pickers, which don't allow such a feature.
