### ISSUE TITLE
Date picker Modal UI

### ISSUE THREAD

**Issue by darshit-devstree** [mmazzarolo/react-native-modal-datetime-picker#505]
## Platforms

- iOS: in latest iOS Version(14.2) modal is like below. Can you please check into it and make it same as before

![image](https://user-images.githubusercontent.com/53767070/102307154-f77a7800-3f89-11eb-951b-70a98ac4f1dd.png)

Thanks in advance :)

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/473
