### ISSUE TITLE
Suggestion to add onModalHide

### ISSUE THREAD

**Issue by cgathergood** [mmazzarolo/react-native-modal-datetime-picker#506]
I'm having the common issue on iOS where it can't handle multiple modals on screen. Doing the following will immediately close the alert
```
closeDatePicker();
showAlert(); // this will open the alert then close almost immediately
```

I can hack around this with a timeout but it would be ideal to expose a `onModalHide` prop similar to https://github.com/react-native-modal/react-native-modal.

Nice work on both of these libs @mmazzarolo 👏

**Comment by mmazzarolo** [comment]
@cgathergood isn't [`onHide` enough for this use](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/157d1297966aba1e2264303c88aaf76534cd5004/src/Modal.js#L97) case 🤔 ?

**Comment by cgathergood** [comment]
@mmazzarolo I tried this but it still seems to show the next alert before the date picker is dismissed.

**Comment by mmazzarolo** [comment]
It seems to be working for me 🤔 Can you create a minimum reproducible example and open a new issue? Thanks!

**Comment by cgathergood** [comment]
Thanks @mmazzarolo here's an issue with a demo + video - https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/512
