### ISSUE TITLE
Broken on iOS14 ?

### ISSUE THREAD

**Issue by elnygren** [mmazzarolo/react-native-modal-datetime-picker#508]
Modal looks like:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/6632349/103092358-a1e44200-45ff-11eb-8f87-aba43b57ce39.png">

Clicking either of those buttons looks like:

<img width="254" alt="image" src="https://user-images.githubusercontent.com/6632349/103092373-b0325e00-45ff-11eb-9b12-8c41e4f94b37.png">

Even though I have `is24Hour={true}`.

Did iOS radically change something and now this library works in a very different way suddenly that does not match the screenshots in README at all ?

**Comment by elnygren** [comment]
looks like solution is to set
`display='spinner'` to get the "old" look of the spinner

**Comment by JoshArkMortgage** [comment]
> looks like solution is to set
> `display='spinner'` to get the "old" look of the spinner

Display prop seems to not be functioning correctly https://github.com/react-native-datetimepicker/datetimepicker/issues/365

**Comment by mmazzarolo** [comment]
> ooks like solution is to set
display='spinner' to get the "old" look of the spinner

Not sure I'm following btw, [we're already setting `display="spinner"`](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/e34a3b8b1aa9f5f28e4a20c3dcaeddd70adbd843/src/DateTimePickerModal.ios.js#L154)

> Display prop seems to not be functioning correctly (SEE ISSUE HERE: react-native-datetimepicker/datetimepicker#365 ) Unless this is only affecting my simulator for iOS.

For what is worth, the component is working fine for me on iOS14 on multiple devices (simulators & real devices) on non-expo apps.

**Comment by JoshArkMortgage** [comment]
I have display prop set to 'spinner' on iOS however I still receive the 'new' UI
<img width="1019" alt="Screen Shot 2020-12-29 at 1 27 29 PM" src="https://user-images.githubusercontent.com/69160735/103305633-a29f1e80-49d9-11eb-97a4-171819c9ad51.png">

**Comment by mmazzarolo** [comment]
Why are you setting the `display` prop to `spinner` manually? [We're already setting it](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/e34a3b8b1aa9f5f28e4a20c3dcaeddd70adbd843/src/DateTimePickerModal.ios.js#L154) 🤔 
What version of React-Native are you using and of the community picker are you using? Are you 100% sure you're on the latest versions (and that your cache is clear `npm run start -- --reset-cache`)?

**Comment by JoshArkMortgage** [comment]
I figured I would try setting it manually since it wasn't working

RNdatetimepicker is version 2.1.0 and RN version 0.63.3

**Comment by JoshArkMortgage** [comment]
> I figured I would try setting it manually since it wasn't working
> 
> RNdatetimepicker is version 2.1.0 and modal version 8.1.1 and RN version 0.63.3

I will try to update

**Comment by mmazzarolo** [comment]
[RNdatetimepicker must be > 3](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/f6c339eba8a2c0e73587279ee27575fd15a4c914/package.json#L53)

**Comment by JoshArkMortgage** [comment]
> RNdatetimepicker must be > 3

TYSM! Feel like an idiot but its working now!

**Comment by mmazzarolo** [comment]
no worries, it happens :) glad it works!

**Comment by gr0x0** [comment]
Hey guys I'm having the same trouble and I need some help here. Already did all recommended above (set RNdatetimepicker to ^3.0.0 on package.json, deleted node_modules and reinstalled everything), but I'm still not getting the spinner mode.

This is also only on iOS, Android works great. Any tips?

**Comment by mmazzarolo** [comment]
@gr0x0 Did you already try cleaning up the cache with `react-native start --reset-cache`?

**Comment by gr0x0** [comment]
@mmazzarolo I did, sorry i forgot to mention. I'm using yarn so I ran yarn cache clean, but it didn't work. I really don't know what I am missing...
