### ISSUE TITLE
is24Hour param is ignored for mode='datetime' scenario

### ISSUE THREAD

**Issue by raduflp** [mmazzarolo/react-native-modal-datetime-picker#51]
When settings mode='datetime' the timepicker ignores the is24Hour flag

the issue is in src/CustomDatePickerAndroid/index.js:52-54 where the is24Hour prop should be added to the time options. 

let me know If you want a PR for that.

**Comment by mmazzarolo** [comment]
I'm on vacation right now, PRs are welcome :) thanks!

**Comment by mmazzarolo** [comment]
Merged! 
I'll bump this thread when the PR will be available on npm.
