### ISSUE TITLE
showPicker color and Confirm button 

### ISSUE THREAD

**Issue by hnoella** [mmazzarolo/react-native-modal-datetime-picker#514]
My show date picker is black, and I want it to be white. That is the scroll wheel where you pick the time or date. How do I change it to be white in my code? My code is the same version as the one given. Nothing changed. Also, how do I display the time on the page and not on the console? The first picture looks like, that's what I want it to look like when you select the time from the picker. How do I implement that in the code?
![IMG_0162](https://user-images.githubusercontent.com/75348765/103340422-a2d70280-4a49-11eb-9685-ce3758512a43.PNG)
![IMG_0161](https://user-images.githubusercontent.com/75348765/103340432-a8344d00-4a49-11eb-9a3d-136aa63f5176.PNG)

**Comment by mmazzarolo** [comment]
- The picker is black because the device is in dark mode -- if you want to force it to stay white use the `isDarkModeEnabled` prop.
- You should keep the time/date reference in the state of your component in order to show it correctly (set it in the state when the user confirms the selection).

**Comment by hnoella** [comment]
I am confused about the second part. What are you saying I should do?

**Comment by hnoella** [comment]
Also, is there a way I can change the pick a date in the picker to pick a time?
