### ISSUE TITLE
Can I use "isDayBlocked" or similar prop?

### ISSUE THREAD

**Issue by Filippinifra** [mmazzarolo/react-native-modal-datetime-picker#515]
## Ask your Question

Hi! Tonight I tried 4 react native date picker libraries and only this is so cool! THANKS!

Is there a similar prop of "isDayBlocked" (as the airbnb picker https://github.com/airbnb/react-dates)?

I know that there are the "minimumDate" and the "maximumDate" prop but in my project I have a invalid date between the minimum and the maximum date

example:

minimumDate={new Date(2020, 1, 1)}
maximumDate={new Date(2020, 10, 10)}

if the date 5th April 2020 is invalid, how I can disable the 5th April?

**Comment by mmazzarolo** [comment]
👋 Short answer: you can't. React-native-modal-datetime-picker uses a native iOS/Android picker under the hood and, as far as I know, the native picker doesn't allow you to block specific dates.
