### ISSUE TITLE
Default Date

### ISSUE THREAD

**Issue by mwlai288** [mmazzarolo/react-native-modal-datetime-picker#521]
Is there a way to set the default date to be the current day's date?

When I press `Confirm` the value I get is `null` after immediately opening the modal. I want to be able to select the current date without having to scroll to a different date and back to the original date for it to be selected. I would just like to hit `Confirm` for the current date the first time I open the modal.

**Comment by mmazzarolo** [comment]
> When I press `Confirm` the value I get is `undefined`

Does it also happen if you provide the initial date in the `date` prop? In that case, it might be an issue of the `react-native-datetimepicker` component. I suppose you could assume in that case that `undefined` is the same date you passed as a prop in `date`.

**Comment by mwlai288** [comment]
I meant `null` and fixed that in original comment. After adding the `date` prop I still get `null` after the first time I open the modal and press `Confirm`. The second time I open and press the button I get today's value.

**Comment by mmazzarolo** [comment]
Weird 🤔 https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/0f6a6650728318d35f57bcfe48d29ac77116bdce/src/DateTimePickerModal.ios.js#L81

**Comment by mwlai288** [comment]
I think it's an issue with combining this with React Hook Form. I've come up with an alternate fix. Thanks.

**Comment by Jeet1912** [comment]
@mwlai288 can you share it?
