### ISSUE TITLE
tried to register two views with the same name rndatetimepicker

### ISSUE THREAD

**Issue by PhuongNguyenRikai** [mmazzarolo/react-native-modal-datetime-picker#522]
## Versions

- Android:
- iOS:
- react-native-modal-datetime-picker:
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):
- react-native:
- react:

**Comment by sonizef** [comment]
How do you fix that?

**Comment by devPinheiro** [comment]
I have an exact issue, how can I fix it?

**Comment by akashdeepsharma1991** [comment]
hello guys, any update on this issue
