### ISSUE TITLE
Cannot choose earlier or future date in iOS 14.3 devices

### ISSUE THREAD

**Issue by Maharshi01** [mmazzarolo/react-native-modal-datetime-picker#524]
![image_2021-02-04_07-46-56](https://user-images.githubusercontent.com/48430425/106839462-490acd80-66c4-11eb-8768-26ddac3e9ce3.png)
![image_2021-02-04_07-46-56](https://user-images.githubusercontent.com/48430425/106839518-5e7ff780-66c4-11eb-9b97-f4c9342a4b0a.png)

## Versions

- iOS: 14.3
- react-native-modal-datetime-picker: 9.1.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 3.0.9
- react-native: 0.61.2
- react: 16.9.0

## Description

Iam unable to select earlier or future date only in iOS 14.3 device, in other andorid or iOS devices i am able to select though...the code which implemeted is :
 <DateTimePicker
            cancelTextStyle={{ color: '#173154' }}
            isVisible={this.state.showTime}
            onConfirm={this.handleTimePicked}
            title={strings.customerSupport.Set_Time}
            is24Hour={false}
            titleIOS={strings.customerSupport.setTime}
            mode={"time"}
            maximumDate={this.state.date === moment(new Date()).format('DD MMM YYYY') ? new Date() : null}
            onCancel={this.hideTimePicker}
            isDarkModeEnabled={false}
         />
  Can help please...
  For your reference i attached a video and image...

https://user-images.githubusercontent.com/48430425/106839406-25478780-66c4-11eb-8a3b-e633d0f53fbd.mp4

**Comment by mmazzarolo** [comment]
You should remove `maximumDate={this.state.date === moment(new Date()).format('DD MMM YYYY') ? new Date() : null}`

**Comment by Maharshi01** [comment]
Hey @mmazzarolo I had written that to restrict the user to not select the date beyond today......I have attached a image for your reference to show it is working in other devices.but not in 14.3

**Comment by mmazzarolo** [comment]
I would check if this is an issue with the community picker then... https://github.com/react-native-datetimepicker/datetimepicker

**Comment by Maharshi01** [comment]
Thanks @mmazzarolo

**Comment by ticketapp** [comment]
I almost have the same bug: it appears only on iOS and not all iPhone devices.

If I don't set minimumDate and maximumDate (both of them) I can turn the wheel but nothing is written (neither date nor time). If I set both of them I'm able to see dates and times before now (and not the one in the future).

I have the last version of this package and the community picker as well with the last version of iOS
