### ISSUE TITLE
Can we slice the date that is returned

### ISSUE THREAD

**Issue by Ritzz03** [mmazzarolo/react-native-modal-datetime-picker#526]
Can we slice the data that has been returned by the DateTimePickerModal?
So this is what I'm talking about...
For example,
if the returned data is like this
**'2021-06-03T16:24:08.000Z'**...I only want '**2021-06-03**' this part of the data, if you have any idea on how to do this please let me know!

By the way this is the code that I've written for my onConfirm function

const handleConfirm = (date) => {  
     ### //visitDate is a state that i create to store my date value
      this.setState({ visitDate: date });
      hideModal();
};

Thanks!!

**Comment by mmazzarolo** [comment]
Hey @Ritzz03 , the date returned by the component is a standard JS day, so you can use [the plan JS date API to manipulate it](https://stackoverflow.com/questions/23593052/format-javascript-date-as-yyyy-mm-dd).

**Comment by Ritzz03** [comment]
Thank you so much!
