### ISSUE TITLE
Picker modal dates timing not showing on the modal. Empty modal displayed

### ISSUE THREAD

**Issue by ahteshamshah780** [mmazzarolo/react-native-modal-datetime-picker#528]
## Environment
React-native

## Platforms
iOS

## Versions

- Android:
- iOS:
- react-native-modal-datetime-picker:
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):
- react-native:
- react:

## Description
Thanks for the great library. Its working properly on android but getting this issue on iOS.

![WhatsApp Image 2021-02-10 at 7 36 55 PM](https://user-images.githubusercontent.com/59429146/107522877-26077e80-6bda-11eb-9633-66a69ac9fff5.jpeg)

**Comment by lucijafrkovic** [comment]
I'm experiencing the same issue. Picker displays fine on iOS simulator, but it's empty just like the example when running on iOS device.

**Comment by gpessa** [comment]
I have the same

**Comment by lucijafrkovic** [comment]
For me, it was due to my iPhone being set to use dark mode and the app trying to set the theme to dark. Once I forced the app to only use light/universal theme, the picker worked fine.
