### ISSUE TITLE
Initial selected date/time using date prop in iOS not working & works in android

### ISSUE THREAD

**Issue by vamshigupta8** [mmazzarolo/react-native-modal-datetime-picker#529]
In Android, if the custom date was passed as the initial value its working & in iOS it only shows the current date & time.

**Comment by vamshigupta8** [comment]
@mmazzarolo Need solution for this please ?

**Comment by Jeet1912** [comment]
this is still an issue.

**Comment by AsABarranco** [comment]
+1

**Comment by dayaki** [comment]
Please any update on this? still an issue
