### ISSUE TITLE
time keeps adding 3hrs

### ISSUE THREAD

**Issue by 16isaac89** [mmazzarolo/react-native-modal-datetime-picker#534]
**time picker keeps adding 3 hours to the time i pick**, the date is fine.
here is how i implemented it
 <DateTimePickerModal
        isVisible={this.props.datefromVisible}
        mode="datetime"
        onConfirm={(time)=>this.props.handleConfirm(time)}
        onCancel={()=>this.props.closeDatefrom()}
      />

**Comment by PedroGSantos** [comment]
I am having the same problem
