### ISSUE TITLE
tried to register two views with the same name rndatetimepicker 

### ISSUE THREAD

**Issue by devPinheiro** [mmazzarolo/react-native-modal-datetime-picker#537]
## Environment

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 117.45 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms

Both iOS and Android

## Versions

- Android: 
- iOS: 12
- react-native-modal-datetime-picker:
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):
- react-native: 0.63.2
- react: 16.13.1

## Description

I get this error

 "tried to register two views with the same name rndatetimepicker"
 
 I swap react-native-datetime-picker with [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker) to check if the problem persists, and yet it still exists.

**Comment by mmazzarolo** [comment]
https://github.com/react-native-datetimepicker/datetimepicker/issues/401

**Comment by devPinheiro** [comment]
> > I swap react-native-datetime-picker with react-native-community/datetimepicker to check if the problem persists, and yet it still exists.
> 
> This issue should be reported in the community picker repo than 👍

okay
Thank you

**Comment by akashdeepsharma1991** [comment]
Hii any update on this issue.
