### ISSUE TITLE
Display calender horizontally

### ISSUE THREAD

**Issue by vaiosyndicates** [mmazzarolo/react-native-modal-datetime-picker#538]
## Ask your Question

how to make calender show horizontally at date mode?
i already use display props, but it make my app crash

**Comment by mmazzarolo** [comment]
could you add some more details to your question and provide a screenshot/example of what you mean?

**Comment by vaiosyndicates** [comment]
thank you for your resposne
so basically  i want to make the calender display "horizontally" like this
[https://ibb.co/kqRj0j4](url)

but at my devices ( android 11 ), the calender seems different from your documentation
[https://ibb.co/7bskHJW](url)

how i can achieve that?

**Comment by mmazzarolo** [comment]
You can't. 
The picker is shown differently on iOS (first screenshot) and Android (second picture). 
-- unless there's a display property on the Native android to show it horizontally (and I don't think there is). 

For more info: https://github.com/react-native-datetimepicker/datetimepicker
