### ISSUE TITLE
Keyboard overlaps TimePicker in iOS 14

### ISSUE THREAD

**Issue by vaibhavpadalia** [mmazzarolo/react-native-modal-datetime-picker#539]
## Environment

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 163.72 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms

iOS 14

## Versions

- Android: -
- iOS: 14.3
- react-native-modal-datetime-picker: 9.2.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 3.0.4
- react-native: 0.63.4
- react: 16.13.1

## Description

When the mode prop of date picker is set to "time" and display prop is set to "inline", on selecting the time field the keyboard pops up and it covers the time picker modal. 

This can be solved by wrapping the components inside the modal using KeyboardAvoidingView.

![1](https://user-images.githubusercontent.com/23230806/111062420-9aca2300-84ce-11eb-82d7-10da0b755dcc.png)

![2](https://user-images.githubusercontent.com/23230806/111062425-a3baf480-84ce-11eb-8ed0-d1f79a592964.png)

## Reproducible Demo

```
<DateTimePickerModal
    {...props}
    mode={props.mode}
    isVisible={props.show}
    value={new Date()}
    onCancel={props.onCancel}
    is24Hour={true}
    onConfirm={props.setDate}
/>
```

**Comment by mmazzarolo** [comment]
Hi @vaibhavpadalia !

> and display prop is set to "inline",

Thanks for reporting, but we don't "officially" support the `display` prop — so any issue related with the usage of a non-default `display` prop won't be fixed internally by the lib (glad you were able to find a workaround though!)

**Comment by vaibhavpadalia** [comment]
I just have one more question. Can we wrap "react-native-modal-datetime-picker" in another modal?

**Comment by mmazzarolo** [comment]
🤔 well I suppose you can wrap https://github.com/react-native-datetimepicker/datetimepicker at that point, right?

**Comment by vaibhavpadalia** [comment]
But then I will have to handle all the methods like onConfirm and onCancel manually. I think I will stick to KeyboardAvoidingView for now. Thanks @mmazzarolo 😃

**Comment by andre169** [comment]
Hi @vaibhavpadalia ! 
Did you find solution for that?

**Comment by vaibhavpadalia** [comment]
Hey @andre169 !
I tried wrapping the component using KeyboardAvoidingView. And it worked for my case. However, I had to revert the UI to keep it consistent for all versions of iOS.
