### ISSUE TITLE
DatePickerIOS property minuteInterval not working

### ISSUE THREAD

**Issue by DarthFowla** [mmazzarolo/react-native-modal-datetime-picker#54]
I've added a DatePicker with a mode of 'time' and it continues to show 1 minute intervals despite setting the minuteInterval to 30.
I've also tried all the other possible values. None of them seem to work.

**Comment by mmazzarolo** [comment]
Hi!
Does the issue persist even when using react-native's own [datePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html)?

**Comment by MaxToyberman** [comment]
@mmazzarolo just tried it with datePickerIOS and it doesn't work also...

**Comment by mmazzarolo** [comment]
It is indeed a [datePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html) issue then... do you mind reporting the issue on the [react-native](https://github.com/facebook/react-native/issues) repo?  
P.S.: You'll probably need to add an example for reproducing the issue and more complete description of it (eg.: the interested React-Native issue).  

In the meanwhile, I'll leave this issue open :)

**Comment by MaxToyberman** [comment]
@mmazzarolo actually the are many issues with that , here is one of them : 
https://github.com/facebook/react-native/issues/5967

**Comment by MaxToyberman** [comment]
meanwhile you can add `width: 320` to styles in `DatePickerIOS.ios.js` . I know this is not a good solution but it works.

**Comment by mmazzarolo** [comment]
@MaxToyberman thank you for the workaround and for keeping the issue updated 👍

**Comment by suvarnat** [comment]
Hi @MaxToyberman, if user doesn't change time by scrolling, it shows random time.

<DateTimePickerModal
              isVisible={isDatePickerVisible}
              mode="time"
              minuteInterval={30}
              date={new Date("July 1, 1999")}
              headerTextIOS="Pick a Time"
              onConfirm={handleTimeConfirm}
              onCancel={hideDatePicker}
            />
