### ISSUE TITLE
Show until today's date

### ISSUE THREAD

**Issue by fabioplaka** [mmazzarolo/react-native-modal-datetime-picker#541]
Hello

I have 2 questions about the usage of the library.
1. How to limit react-native-modal-datetime-picker calendar until today's date?
2. How to limit in a range of dates?

I will appreciate if I will have an answer as soon as possible.

Thanks in advance

**Comment by mmazzarolo** [comment]
@fabioplaka please check the documentation of https://github.com/react-native-datetimepicker/datetimepicker for the available props. 
TL;DR:

> How to limit react-native-modal-datetime-picker calendar until today's date?
Use the `minimumDate` and `maximumDate` props

> How to limit in a range of dates?

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker#how-can-i-set-a-minimum-andor-maximum-date
