### ISSUE TITLE
Is there a way to show only dates and times in the future?

### ISSUE THREAD

**Issue by zendevil** [mmazzarolo/react-native-modal-datetime-picker#544]
## Ask your Question
In our app, we have a use case in which the user picks the date and time, but only future dates and times are applicable. Is there a way to restrict the modal such that the user can pick only future dates and times?

**Comment by mmazzarolo** [comment]
Hi,
https://github.com/mmazzarolo/react-native-modal-datetime-picker#how-can-i-set-a-minimum-andor-maximum-date
