### ISSUE TITLE
Heading of the Time Picker is "Pick a Date" 

### ISSUE THREAD

**Issue by SehanRathnayake** [mmazzarolo/react-native-modal-datetime-picker#545]
Heading of the Time Picker is "Pick a Date" which should be "Pick Time"

**Comment by mmazzarolo** [comment]
Thanks for reporting @SehanRathnayake !
Mind submitting a PR to fix it? In the meanwhile, you can use the `headerTextIOS` prop.

**Comment by mmazzarolo** [comment]
Fixed by #566
