### ISSUE TITLE
Getting different picker

### ISSUE THREAD

**Issue by bastolaxantos** [mmazzarolo/react-native-modal-datetime-picker#546]
## Ask your Question

 

Hi, I am getting different ui than shown in the documentation. How do I fix it?

https://user-images.githubusercontent.com/24861728/114357943-0d8ff200-9b92-11eb-90e7-9e494b05ed61.mov

What I want:
![image](https://user-images.githubusercontent.com/24861728/114358040-2e584780-9b92-11eb-9003-c83af44c4c21.png)

My Code:
![image](https://user-images.githubusercontent.com/24861728/114358763-05848200-9b93-11eb-8d2f-8126c84c3856.png)

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/533
