### ISSUE TITLE
Weird header in android when maximumDate is setted

### ISSUE THREAD

**Issue by ctorresthrash** [mmazzarolo/react-native-modal-datetime-picker#55]
Hi, first of all, thank you for making this nice module.

When i set the property maximumDate it works as expected in both platforms, but in android it shows an ugly header, this error is not shown when i set the minimumDate prop.

![screenshot_1498099830](https://user-images.githubusercontent.com/4590204/27415262-b1b1e1fa-56cb-11e7-8fa3-c57db985911e.png)

This is my code

```javascript
<DateTimePicker
            isVisible={this.state.showDob}
            titleIOS="Select Your Birth Day"
            maximumDate={Moment().subtract(18, 'years').startOf('day').toDate()}
            onConfirm={date=>{
              dob.onChange(Moment(date).format("YYYY/MM/DD"))        
              this.setState({showDob: false})
            }}
            onCancel={()=>{this.setState({showDob: false})}}/>```

**Comment by mmazzarolo** [comment]
Hi! 
Does it show the header even when using react-native's own [datePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html)?

**Comment by ctorresthrash** [comment]
Yes, it does, thank you for your response, I'll close this issue.

**Comment by mmazzarolo** [comment]
No worries! :)

PS.: If you're going to open an issue on the react-native repos could you link it here too? Thanks!

**Comment by kallayyash** [comment]
how  to make expiry mm/yy format picker in react native?
