### ISSUE TITLE
expo dsk 41

### ISSUE THREAD

**Issue by mohamedsl22** [mmazzarolo/react-native-modal-datetime-picker#555]
Hi there,
I was working with expo sdk 40 and the datepicker was working wonderful, but after I updated to sdk 41, I can't see the dates!
if I add maximumDate I can see the dates after but not befrore!! please fix it :)))

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker#the-picker-is-not-showing-the-right-layout-on-ios--14

**Comment by mohamedsl22** [comment]
I'am on "@react-native-community/datetimepicker": "^3.4.7" and
"react-native-modal-datetime-picker": "^9.2.1"
and still not working as expected  ! same problem

**Comment by JelHe** [comment]
Hello, @mmazzarolo, 
our versions on expo 41:
"@react-native-community/datetimepicker": "^3.4.7"
"react-native-modal-datetime-picker": "^9.2.3"

And it's seems we have the same issue, we have got screen from our client (iphone 11 pro, ios 14.5) where previous dates not displayed.
Could you help on this? Thank you very much!
![Screenshot 2021-05-12 at 20 59 45](https://user-images.githubusercontent.com/78354099/118022842-7de28c80-b365-11eb-8e67-d68bca457750.png)

**Comment by mohamedsl22** [comment]
@JelHe  I fixed it with adding textColor="#3897FD"
hope it works for you too :)

**Comment by JelHe** [comment]
@mohamedsl22 Thank you very much, it works!
