### ISSUE TITLE
expo sdk 41 -- expo go app version 2.19.3

### ISSUE THREAD

**Issue by mohamedsl22** [mmazzarolo/react-native-modal-datetime-picker#556]
Hi there,
I was working with expo sdk 40 and the datepicker was working wonderful, but after I updated to sdk 41, I can't see the dates!
if I add maximumDate I can see the dates after but not befrore!! please fix it :)))
I'am on "@react-native-community/datetimepicker": "^3.4.7" and
"react-native-modal-datetime-picker": "^9.2.1"
ios 13.4.1 and also tried on the latest ios 14
expo go app version 2.19.3

*********it might be because of the new "expo go" app version because when I tried it before I update the expo app everything was working fine on ios 13 but after I updated the app I noticed the problem

**Comment by mmazzarolo** [comment]
Please follow the issue template, thank you.
