### ISSUE TITLE
New Hide Header Prop

### ISSUE THREAD

**Issue by scott-massey** [mmazzarolo/react-native-modal-datetime-picker#557]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-modal-datetime-picker@9.2.1` for the project I'm working on.

I'm trying to localize the "Cancel" and "Confirm" buttons in my project, and don't really need the header. So I added a new prop called `hideHeaderIOS` which, when true, will keep the HeaderComponent from rendering.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-modal-datetime-picker/src/DateTimePickerModal.ios.js b/node_modules/react-native-modal-datetime-picker/src/DateTimePickerModal.ios.js
index 644da63..d22dab9 100644
--- a/node_modules/react-native-modal-datetime-picker/src/DateTimePickerModal.ios.js
+++ b/node_modules/react-native-modal-datetime-picker/src/DateTimePickerModal.ios.js
@@ -45,6 +45,7 @@ export class DateTimePickerModal extends React.PureComponent {
     onHide: PropTypes.func,
     maximumDate: PropTypes.instanceOf(Date),
     minimumDate: PropTypes.instanceOf(Date),
+    hideHeaderIOS: PropTypes.bool,
   };
 
   static defaultProps = {
@@ -116,6 +117,7 @@ export class DateTimePickerModal extends React.PureComponent {
       onConfirm,
       onChange,
       onHide,
+      hideHeaderIOS,
       ...otherProps
     } = this.props;
     const isAppearanceModuleAvailable = !!(
@@ -150,7 +152,7 @@ export class DateTimePickerModal extends React.PureComponent {
             pickerContainerStyleIOS,
           ]}
         >
-          <HeaderComponent label={headerTextIOS} />
+          {!hideHeaderIOS && <HeaderComponent label={headerTextIOS} />}
           <PickerComponent
             display="spinner"
             {...otherProps}
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by scott-massey** [comment]
Totally fine if you think this adds bloat to the package, but thought I may as well share my changes...

**Comment by mmazzarolo** [comment]
Hey @scott-massey ! Mind sharing a screenshot of how the picker looks like without the header? Since the header is one of the non-standard UI elements adding a prop to disable it **might** actually be something we can add to the repo.

**Comment by scott-massey** [comment]
![Screen Shot 2021-04-30 at 10 10 39 AM](https://user-images.githubusercontent.com/54546509/116715995-dc3e6100-a99c-11eb-946c-6c947c800f3d.png)
![Screen Shot 2021-04-30 at 10 13 13 AM](https://user-images.githubusercontent.com/54546509/116715996-dcd6f780-a99c-11eb-8a27-c529f693e775.png)
![Screen Shot 2021-04-30 at 10 13 25 AM](https://user-images.githubusercontent.com/54546509/116715997-dcd6f780-a99c-11eb-913b-cab86739163f.png)

I've got three screenshots here. Not sure which order they uploaded in, but they are:
- What it looks like with the spinner
- What it looks like with `display={'inline'}`. I personally like this setting much more, but without the heading there's some missing padding.
- So the other screenshot is the same component but I added extra padding using the `pickerContainerStyleIOS` prop

**Comment by mmazzarolo** [comment]
@scott-massey, mind checking #558 and giving it a try? I always wanted to remove the header because it didn't make too much sense imho. 
This PR should solve both of your issues. 
It's a breaking change, but I'm pretty sure it will be ok for you. 
FYI, I'm also planning to add default to the "inline" implementation of the date/datetime picker modes in the future (so except for time).
