### ISSUE TITLE
Cannot read property getTime of null inside DateTimePickerModal.android.js (Android Only)

### ISSUE THREAD

**Issue by AlixH** [mmazzarolo/react-native-modal-datetime-picker#569]
## Environment

System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 348.36 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 29.0.2, 29.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_271 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms

Android

## Versions

- Android: 10 API level 29
- iOS: irrelevant
- react-native-modal-datetime-picker: 9.2.1
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 3.4.7
- react-native: 0.64.1
- react: 17.0.1

## Description

I have an input showing the date chosen inside the date picker modal. When clearing the date value (setting it as null), it is passed back to the picker via the date property. 
Then, I have the below error showing up.

![1621432789838](https://user-images.githubusercontent.com/32574035/118827902-17a5be80-b8bd-11eb-8aa4-0ce7845779d9.jpg)

**A simple fix would be to add a chaining operator before the getTime() call**

**Comment by mmazzarolo** [comment]
Hey @AlixH ! 
Thanks for reporting, but the `date` prop is required, so throwing an error in this case is the right behaviour (we could throw a more descriptive error though).

**Comment by AlixH** [comment]
> Hey @AlixH !
> Thanks for reporting, but the `date` prop is required, so throwing an error in this case is the right behaviour (we could throw a more descriptive error though).

Hello, 
Thanks for answering. So we cannot pass null/undefined ? Because what's weird is that it's working on IOS.

**Comment by mmazzarolo** [comment]
That's correct. It "works" because the underneath library handles it, but you shouldn't pass null/undefined because in the future there might be updates that will make it not work. You should always initialize the date used in the picker 👍
