### ISSUE TITLE
iOS Date Picker is not Changing Date, using Spinner

### ISSUE THREAD

**Issue by kmayatwal** [mmazzarolo/react-native-modal-datetime-picker#572]
## Environment
Trying to change the date using spinner, but it's not stopping on any date, month or year, it'll go back to the initial Stage.

## Platforms
iOS Version 14.3
iPhone 8

## Versions

- Android:
- iOS: 14.3
- react-native-modal-datetime-picker: 9.2.3
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 3.5.0
- react-native: 0.61.5
- react: 16.9.0

## Description

i've added latest version of both library and on picker, if i try to move the spinner, it won't stop on any particular place, it go back to it's initial state. in attached gif file you can see, when i try to set day, month or year, it'll fall back to it's initial state.
![Simulator Screen Shot - iPhone 8 - 2021-05-28 at 17 31 26](https://user-images.githubusercontent.com/4996287/119980984-b081bb80-bfda-11eb-9e92-f4949df47686.png)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/4996287/119981594-7238cc00-bfdb-11eb-938f-809b1e86edff.gif)

**Comment by mmazzarolo** [comment]
Hi @kmayatwal, we need a minimal reproducible example to help.

From the issue template:
> Let us know how to reproduce the issue. Include a code sample or share a project that reproduces the issue.
> Follow the guidelines for providing a minimal example: https://stackoverflow.com/help/mcve
> Please notice that WE WON'T SUPPORT ISSUE REPORTS THAT DON'T HAVE A MINIMAL REPRODUCIBLE EXAMPLE.
