### ISSUE TITLE
How to change the theme of the picker in iOS

### ISSUE THREAD

**Issue by Ritzz03** [mmazzarolo/react-native-modal-datetime-picker#573]
## How to change the theme of the picker in iOS

Hello! I'm currently using the date-time picker for iOS and if my simulator or device is in dark mode I can't see the text.

I tried using `isDarkModeEnabled`...it works in dark mode but if I change it back to light it's not working in light mode

I also tried using `themeVariant` but it still didn't work if you know how to fix this please let me know...Thanks! 

**(btw I'm having this issue only in spinner mode)**

**Comment by mmazzarolo** [comment]
Under the hood react-native-modal-datetime-picker uses @react-native-community/datetimepicker. Did you already try swapping react-native-datetime-picker with @react-native-community/datetimepicker to see if the issue persists?

**Comment by Ritzz03** [comment]
@mmazzarolo I tried changing packages an it worked Thank you so much!
