### ISSUE TITLE
Open default inputs on timepicker (Android)

### ISSUE THREAD

**Issue by jordiepasman** [mmazzarolo/react-native-modal-datetime-picker#574]
## Open default inputs on timepicker (Android)

Currently when de timpicker opens you get a clock to enter your time.
![Screenshot 2021-06-02 at 12 24 08](https://user-images.githubusercontent.com/47739539/120464676-7bd88000-c39d-11eb-9ab8-23b02ceb6df4.png)

And you can switch to the inputs, where you can manually entering your time, by clicking on the keyboard icon. 
Our question is if we also can showing this view by default when the timepicker opens?

![Screenshot 2021-06-02 at 12 24 19](https://user-images.githubusercontent.com/47739539/120465131-edb0c980-c39d-11eb-9909-87f442a3dcca.png)

- Mode: datetime
- Version: 9.1.0

**Comment by mmazzarolo** [comment]
I think you can use the [`display` prop](https://github.com/react-native-datetimepicker/datetimepicker#display-optional) for this... not sure which value will enable it though 🤔
