### ISSUE TITLE
onconfirm changed date to today date even when spinner does not move - on first open 

### ISSUE THREAD

**Issue by morelgarisi** [mmazzarolo/react-native-modal-datetime-picker#576]
hi , 
setting up min date - for datepicker , and on first time open and pressing confirm button change the date being picked to today.
see example 
![Screen-Recording-2021-06-06-at-1](https://user-images.githubusercontent.com/18554479/120922857-31743d80-c6d4-11eb-9bcd-1b225d4c585e.gif)

  handleDatePicked = date => {
//console log date on first time date is today and not the min date that was set and picked on calendar 
    this.setState({ form: { ...this.state.form, date }, errorDate: isWeekendDay(date) })
    this.hideDatePicker()
  }

  <DateTimePicker 
            onConfirm={this.handleDatePicked} 
            onCancel={this.hideDatePicker} 
            minimumDate={new Date(minimumDate)} 
            maximumDate={new Date(maximumDate)} 
            mode={'date'} 
            locale={'he'} 
/>

on the video - min date set up to 8.6.2021
but on confirm - changed ti 6.6.2021-> today's date

**Comment by mmazzarolo** [comment]
Hi, in order to help you with these issues you need to fully follow the issue template providing a minimum reproducible example. Thanks.

**Comment by tandu** [comment]
Bug really exists. Nothing special is required is to reproduce. I faced the same issue. Set max date to let's say -5 years, open calendar click "confirm" and you get today date in the handler. So The resulting date and what you see in calendar are not synced until you select another date.
