### ISSUE TITLE
Bug when I open the datepicker on android and date config was setted

### ISSUE THREAD

**Issue by marcelodiegues** [mmazzarolo/react-native-modal-datetime-picker#577]
## Environment

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 1000.73 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.21.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 21, 23, 28, 29, 30
      Build Tools: 21.1.2, 23.0.2, 25.0.1, 28.0.3, 29.0.2, 30.0.0, 30.0.3
      System Images: android-23 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

## Platforms

Android

## Versions

N/A

- Android: API 30
- iOS: 13.3
- react-native-modal-datetime-picker: 9.2.3
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): ^2.1.0
- react-native: 0.61.5
- react: 16.9.0

## Description
Problem with modal datepicker in Android. I found a bug when I try to set the date params. When I do this the modal on Android close and open again. I tried with the community component and the same error happens

`
    const [isDatePickerVisible, setDatePickerVisibility] = useState(false);
    const [date, setDate] = useState(new Date())

    const showDatePicker = () => {
        setDatePickerVisibility(true)
    };

    const hideDatePicker = () => {
        setDatePickerVisibility(false)
    };

    const handleConfirm = (date) => {
        setDate(date)
        props.setDateFunction(date)
        hideDatePicker()
    };
   <DateTimePickerModal
       isVisible={isDatePickerVisible}
        mode="date"
        date={date}
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
    />

`

## Reproducible Demo

https://user-images.githubusercontent.com/755404/121095433-b8094780-c7c6-11eb-8e19-1eb6173fd72a.mov

**Comment by mmazzarolo** [comment]
@marcelodiegues thank you. 
I'm pretty sure the issue is the one listed in the [FAQs in the README.md](https://github.com/mmazzarolo/react-native-modal-datetime-picker#the-picker-shows-up-twice-on-android).  
If it's not, please submit the issue in the community picker repo (since we can't do much if the issue comes from the underlying library.

**Comment by AsABarranco** [comment]
+1
