### ISSUE TITLE
Date Picker default selected date issue with daylight saving time

### ISSUE THREAD

**Issue by yasirunilan** [mmazzarolo/react-native-modal-datetime-picker#579]
## Ask your Question

I'm using react native modal datetime picker in my react native mobile app and I have come across a scenario like this and I don't have a solution for this. My time zone is America/Mexico_city (-5) and it's  CDT . In my date picker I want to display '1985-08-17' date as the default selected date. But when I pass the date object is shows the previous day  in the picker. Is there something wrong that I'm doing 

```
<DateTimePicker
                    isVisible={true}
                    date={new Date('1985-01-17')}
                    onConfirm={()=>()}
                    onCancel={()=>()}
                    mode={'date'}
                />
```
In the same -5 time zone if I change my device timezone to America/Chicago issue is not reproducible. It's also in the same CDT timezone

**Comment by mmazzarolo** [comment]
Hey @yasirunilan , did you try using the community picker directly? I don't think this is something we have any control on in this component.

**Comment by yasirunilan** [comment]
@mmazzarolo I did't use it yet. Will install it and try there too
