### ISSUE TITLE
DateTimePicker selecting the wrong time.

### ISSUE THREAD

**Issue by luqiborges** [mmazzarolo/react-native-modal-datetime-picker#580]
Hello everyone, when I select a date and a time using the modal on mode="datetime", the time is setting 3 hours after the time I picked. 

I'm testing using the emulator of android studio.

Code: 
```
import DateTimePickerModal from 'react-native-modal-datetime-picker';

<TouchableOpacity onPress={() => setIsInitialPickerActive(true)}>
        <Text>Set Initial Date</Text>
      </TouchableOpacity>

      <DateTimePickerModal
        isVisible={isInitialPickerActive}
        mode="datetime"
        onConfirm={newDate => {
          setInitialDate(
            newDate.toISOString().replace('T', ' ').replace('Z', ''),
          );
          setIsInitialPickerActive(false);
        }}
        onCancel={() => setIsInitialPickerActive(false)}
      />
```

Prints of the screen:
![image](https://user-images.githubusercontent.com/55192262/123681055-b5c36780-d81f-11eb-9ff9-c75fe95ba30e.png)

![image](https://user-images.githubusercontent.com/55192262/123681034-b1974a00-d81f-11eb-8f9c-108ebaa12344.png)

**Comment by mmazzarolo** [comment]
Hey @luqiborges did you already try using the community picker to see if the issue still persists?

**Comment by luqiborges** [comment]
It fixed! Thanks!
