### ISSUE TITLE
Internationalization "react-native-modal-datetime-picker"

### ISSUE THREAD

**Issue by rathierry** [mmazzarolo/react-native-modal-datetime-picker#583]
Hi guys,

I would like to customise all calendar languages (month (short or long) and date (short or long) to the selected language (eg: **DE** for Deutch) in my app.

How can I fixe it ?

Thanks

<img width="448" alt="Screen Shot 2021-07-14 at 11 26 49" src="https://user-images.githubusercontent.com/10048076/125589649-a99a6c65-2707-4422-8329-c9a1ea872e60.png">

**Comment by mmazzarolo** [comment]
👋 Since under-the-hood a native module is being used, locale can be handled only at the OS level https://github.com/mmazzarolo/react-native-modal-datetime-picker#how-can-i-set-an-automatic-locale-in-ios

**Comment by rathierry** [comment]
@mmazzarolo, and how can I retrieve the new calendar value (either date or time) in **Android** and show it in console.log ?

Thanks

**Comment by mmazzarolo** [comment]
Just use the same pattern used in the example :) 
```
import React, { useState } from "react";
import { Button, View } from "react-native";
import DateTimePickerModal from "react-native-modal-datetime-picker";

const Example = () => {
  const [isDatePickerVisible, setDatePickerVisibility] = useState(false);

  const showDatePicker = () => {
    setDatePickerVisibility(true);
  };

  const hideDatePicker = () => {
    setDatePickerVisibility(false);
  };

  const handleConfirm = (date) => {
    console.warn("A date has been picked: ", date);
    hideDatePicker();
  };

  return (
    <View>
      <Button title="Show Date Picker" onPress={showDatePicker} />
      <DateTimePickerModal
        isVisible={isDatePickerVisible}
        mode="date"
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
      />
    </View>
  );
};

export default Example;

```
