### ISSUE TITLE
Add minimum and maximum time

### ISSUE THREAD

**Issue by Omar-8** [mmazzarolo/react-native-modal-datetime-picker#588]
The current minimum / maximum date prop only works for dates. It would be great to extend it to time as well --> User can select specific timings.

**Comment by christopher-18** [comment]
@Omar-8  how did you achieve this?

**Comment by vishva-simform** [comment]
@Omar-8 Can you please share how did you solve that issue?

**Comment by Omar-8** [comment]
I handled it manually. The onConfirm function will have to check if the timing is wrong or not available and then notify the user about it by showing an error caption or alert. Would have been better ux design to restrict the user in the first place from picking the wrong time, but I guess that ain't coming soon.

**Comment by Omar-8** [comment]
> @Omar-8 Can you please share how did you solve that issue?
> @Omar-8 how did you achieve this?

I handled it manually. The onConfirm function will have to check if the timing is wrong or not available and then notify the user about it by showing an error caption or alert. Would have been better ux design to restrict the user in the first place from picking the wrong time, but I guess that ain't coming soon.
