### ISSUE TITLE
Is jalali calendar supported ?

### ISSUE THREAD

**Issue by mehdikhody** [mmazzarolo/react-native-modal-datetime-picker#589]
Hi, I want to know how to change calendar to Jalali.

**Comment by mmazzarolo** [comment]
Hi @mehdikhody !
You should probably check https://github.com/mmazzarolo/react-native-modal-datetime-picker#how-can-i-set-an-automatic-locale-in-ios. Please keep in mind that under the hood we're using a native component, so we're just using whatever language/calendar-type is used at the system level.
