### ISSUE TITLE
minimumDate doesnt work ,maximumDate work well?

### ISSUE THREAD

**Issue by Mscynol** [mmazzarolo/react-native-modal-datetime-picker#59]
minimumDate doesnt work ,maximumDate work well?

**Comment by mmazzarolo** [comment]
Hi, are you on Android? 
[This might be interesting](https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/60)

**Comment by Mscynol** [comment]
Yes ,when I try it on Android, I'm amazing

**Comment by mmazzarolo** [comment]
Unfortunately it's not supported on Android 👎
