### ISSUE TITLE
Invisible text when device has dark theme, but app has light appearance

### ISSUE THREAD

**Issue by Anybowdy** [mmazzarolo/react-native-modal-datetime-picker#590]
## Environment

React native SDK42, Expo

## Platforms

iOS

## Versions

10.0.0

- Android:
- iOS:
- react-native-modal-datetime-picker:
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):
- react-native:
- react:

## Description

Still having the problem of white text on white background when the device is using dark theme.
Even though I forced appearance to be light, the text does not adapt.
I tried to use to textColor props, and isDarkThemeEnabled but not useful.

![IMG_7521](https://user-images.githubusercontent.com/36242531/129928030-8049de4d-f7f8-4891-82e3-165914eaf615.PNG)

**Comment by mmazzarolo** [comment]
Hey @Anybowdy ! I'm sorry but we cannot help unless you provide a minimal reproducible repository. Please check the issue template for more info 👍 

> Let us know how to reproduce the issue. Include a code sample or share a project that reproduces the issue.
> Follow the guidelines for providing a minimal example: https://stackoverflow.com/help/mcve 
> Please notice that WE WON'T SUPPORT ISSUE REPORTS THAT DON'T HAVE A MINIMAL REPRODUCIBLE EXAMPLE.

**Comment by jakewtaylor** [comment]
Hey - I had this issue too using Expo, with this in my app.json:
```
"userInterfaceStyle": "light",
```

I had the `isDarkModeEnabled` prop set to true which caused it to go dark - I removed that prop, which made it white but the text was invisible. I could get it visible by setting a `textColor="black"` prop. Works in both iOS light & dark mode.

@Anybowdy  - hope that helps!

**Comment by palicko** [comment]
You can also use `themeVariant` prop and specify light variant like this `themeVariant="light"`.

**Comment by pCyril** [comment]
Juste to complete your answer @palicko https://github.com/react-native-datetimepicker/datetimepicker#themevariant-optional-ios-only
