### ISSUE TITLE
how to custom japanese time language

### ISSUE THREAD

**Issue by Sonsieg** [mmazzarolo/react-native-modal-datetime-picker#593]
I want to change Time and day format japanes YYYY年M月D日, how to custom japanese time language ? Please help me, thank all <3

**Comment by mmazzarolo** [comment]
👋 Hello hello @Sonsieg .
See: https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/README.md#how-can-i-change-the-picker-languagelocale

Under the hood this library is using @react-native-community/datetimepicker. You can't change the language/locale from react-native-modal-datetime-picker. Locale/language is set at the native level, on the device itself.
