### ISSUE TITLE
Warning due to use of depreciated method: EventEmitter.removeListener('didUpdateDimensions', ...)

### ISSUE THREAD

**Issue by prosperevergreen** [mmazzarolo/react-native-modal-datetime-picker#594]
## Environment

System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 21.12 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.20.5 - /usr/local/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-26 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: javac 14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms

Android and iOS

## Versions

- Android:
- iOS:
- react-native-modal-datetime-picker: ^10.2.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): ^3.5.2
- react-native: 0.65.1 => 0.65.1 
- react: 17.0.2 => 17.0.2 

## Description

When I try to toggle the view component that renders the date picker, I get the warning: **EventEmitter.removeListener('didUpdateDimensions', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.**

## Reproducible Demo

```js
import React, { useState } from 'react';
import {View,Button} from 'react-native';
import RNDateTimePickerModal from 'react-native-modal-datetime-picker';

const App = () => {
const [showDateView, setShowDateView] = useState(true);
return (
        <View>
          {showDateView && (
            <RNDateTimePickerModal
              isVisible={false}
              mode="date"
              onCancel={() => {}}
              onConfirm={() => {}}
            />
          )}
          <Button
            title="toggle"
            onPress={() => setShowDateView(!showDateView)}
          />
        </View>
)};
```

PS: The warning is most likely related to [https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/Modal.js](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/Modal.js), line: 51.

**Comment by mmazzarolo** [comment]
@prosperevergreen thanks for reporting. This PR should fix it. Could you give it a try? https://github.com/mmazzarolo/react-native-modal-datetime-picker/pull/591

**Comment by prosperevergreen** [comment]
I tried using PR #591 and it seemed to fix the issue, could merge it to master, kinda feels unsafe using PR version :).

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v11.0.0
