### ISSUE TITLE
confirm button doesn't work on iPad iOS 14

### ISSUE THREAD

**Issue by Mariam-K-code-care** [mmazzarolo/react-native-modal-datetime-picker#595]
## Environment
System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 71.36 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.5.0/bin/yarn
    npm: 7.20.5 - ~/.nvm/versions/node/v16.5.0/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-clean-project: 3.6.4
    react-native-cli: 2.0.1
## Platforms

issue takes place on ipad, ios 14.6, 14.7, 14.7.1

## Versions

- Android:
- iOS 14.6, 14.7, 14.7.1
- react-native-modal-datetime-picker:  6.0.8 and the latest one
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):
- react-native: 0.61.4
- react: 16.9.8

## Description
when testing on ipad with ios versions that are mentioned above, confirm button doesn't work after picking the date/time, on iphone it does work but not on ipad.

https://user-images.githubusercontent.com/85952669/131488321-432a04af-21a1-4e4c-a480-4890ce44b302.mp4

## Reproducible Demo

```
<DateTimePicker
          mode="datetime"
          isVisible={visible}
          onConfirm={this._onDateTimeConfirmed}
          onCancel={this._onDateTimeCancelled}
        />
```
        
        
this is the sample code of how I have it in my project, nothing special, and it works everywhere except on iPad. I have tested it with  iOS 14.6, 14.7, 14.7.1, on emulator (ipad pro (12,9 inch) 4th gen, ios 14.0.1) and in browserstack, same result for all of them

**Comment by mmazzarolo** [comment]
@Mariam-K-code-care could you please provide the entire code? We can't help with a single snippet.
