### ISSUE TITLE
translation of the months

### ISSUE THREAD

**Issue by imnotvirus** [mmazzarolo/react-native-modal-datetime-picker#596]
## additional configuration at the expo

even with the emulator localized in Brazil, the language of the months is still in english, is there any specific configuration to solve using expo?
 
![image](https://user-images.githubusercontent.com/11259073/132769831-5f106ab9-8fb5-4446-aea2-1f35019a3cd7.png)
![image](https://user-images.githubusercontent.com/11259073/132769895-4526259f-19e2-4aea-bace-5244ed030e64.png)

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker#how-can-i-change-the-picker-languagelocale

We don't have any control on the language used in the date/time picker, so I won't be able to help, sorry.
