### ISSUE TITLE
Texts of PickerItem is hard to see in dark-mode.

### ISSUE THREAD

**Issue by KhoaN56** [mmazzarolo/react-native-modal-datetime-picker#598]
## Ask your Question

When I allow using dark-mode. The layout get dark but the text of the picker component is still remain the light-mode. I hope dark-mode will soon be updated to cover this case.

**Comment by jaydeep911** [comment]
This is still happens. 
Basically when system theme is dark and our app theme is light and so we are passing isDarkModeEnabled={false}
at the moment text is not showing.

**Comment by AyoCodess** [comment]
is there a fix for this?

**Comment by SusulAdam** [comment]
Solution for it on android can be:
        
        positiveButton={{
          textColor:
            Appearance.getColorScheme() === 'dark'
              ? "#ffffff"
              : undefined,
        }} // android only
        negativeButton={{
          textColor:
            Appearance.getColorScheme() === 'dark'
              ? "#ffffff"
              : undefined,
        }} // android only
