### ISSUE TITLE
Confirm and Cancel button is not working at ios 14.5

### ISSUE THREAD

**Issue by justb** [mmazzarolo/react-native-modal-datetime-picker#609]
## Platforms

System:
    OS: macOS 11.3.1
    CPU: (8) x64 Apple M1
    Memory: 512.50 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - ~/.tnvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 7.15.1 - ~/.tnvm/versions/node/v16.3.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
  IDEs:
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

## Versions

"@react-native-community/datetimepicker": "^3.5.2",
"react-native-modal-datetime-picker": "^12.0.0",

## Description

Confirm and Cancel button is not working

## Reproducible Demo

```
import React, { useState } from 'react'
import { Button, View } from 'react-native'
import DateTimePickerModal from 'react-native-modal-datetime-picker'
import DropDownPicker from 'components/DropDownPicker'
import moment from 'moment'

const Example = ({ onConfirm = (e: string) => {} }) => {
  const [isDatePickerVisible, setDatePickerVisibility] = useState(false)
  const [display, setdisplay] = useState()

  const showDatePicker = () => {
    setDatePickerVisibility(true)
  }

  const hideDatePicker = () => {
    setDatePickerVisibility(false)
  }

  const handleConfirm = (date) => {
    setdisplay(moment(date).format('HH:mm'))
    onConfirm(moment(date).format('HH:mm'))
    hideDatePicker()
  }

  return (
    <View>
      <DropDownPicker onPress={showDatePicker} open={false} placeholder={display}></DropDownPicker>
      <DateTimePickerModal
        isVisible={isDatePickerVisible}
        mode="time"
        minuteInterval={5}
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
      />
    </View>
  )
}

export default Example

```

**Comment by Arch1js** [comment]
If you are using expo, those two buttons don't seem to work in debug mode.

**Comment by metehankurucu** [comment]
Same issue. I am using bare react native.

**Comment by mmazzarolo** [comment]
Could you create a minimal reproducible example? The example in the README.md works fine for me on iOS (both in debug and in production mode) on bare react-native.

**Comment by Harshit31** [comment]
Facing the same issue on ios 15

**Comment by Harshit31** [comment]
Here is the screen recording of the behaviour on the simulator.

https://user-images.githubusercontent.com/16761098/143007934-ce6dd629-ad46-49a5-81b8-92a9cfd8b2b7.mov

**Comment by mmazzarolo** [comment]
@Harshit31 Could you create a minimal reproducible example? The example in the README.md works fine for me on iOS (both in debug and in production mode) on bare react-native.
