### ISSUE TITLE
Only the date picker shows up, not the time picker

### ISSUE THREAD

**Issue by yukkeechang** [mmazzarolo/react-native-modal-datetime-picker#61]
I might be applying this wrong but I copy the example and a time picker does not show up for me however the console log still prints out a time when a date is selected. How can I make the time picker show up as well?

**Comment by OskarHeden** [comment]
Use the 'mode' prop and change the value to 'time'

**Comment by yukkeechang** [comment]
that worked! thanks! I shouldve been more careful looking at the provided props :)

**Comment by mmazzarolo** [comment]
@yukkeechang no worries, it happens :)
