### ISSUE TITLE
On Android, the date I selected does not change in the popup

### ISSUE THREAD

**Issue by ahmetbasdan** [mmazzarolo/react-native-modal-datetime-picker#614]
Selected date: 12/16/2021
Date displayed in popup: Now Date => 12/01/2021
[snack.expo.dev/@ahmetbasdan/react-native-modal-datetime-picker-example](https://snack.expo.dev/@ahmetbasdan/react-native-modal-datetime-picker-example)

![ss1](https://user-images.githubusercontent.com/18085857/144208587-1f666ea9-e553-45d1-accc-d81ac9e73402.png)

![ss2 1](https://user-images.githubusercontent.com/18085857/144209671-df6962a9-5b83-47e7-a47b-b77acbcf00e3.png)

**Comment by mmazzarolo** [comment]
Please follow the issue template before creating new issues, thanks!
