### ISSUE TITLE
iOS 15.1.1 picker not showing the month field

### ISSUE THREAD

**Issue by northout-praveen** [mmazzarolo/react-native-modal-datetime-picker#617]
## Environment
iOS - OS version 15.1.1 didn't get the error proper wheel picker response

## Platforms
iOS

## Versions
15.1.1 

-- react-native- iOS:
- react-native-modal-datetime-picker:
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):

## Description
Please check the below-attached image below this is occurring on ios 15.1.1 device iphone 13 pro max
only showing date and year month is not displaying in this picker and also the font color is dull.
![picker error](https://user-images.githubusercontent.com/58068544/145165591-4e80c4b6-435c-4fbe-ab7f-6cac0eb95835.jpg)

**Comment by northout-praveen** [comment]
@mmazzarolo why are you closing this any solution on this issue..?

**Comment by xaviserrag** [comment]
I am having the same problem on iOS after version 15 release.

**Comment by LukhiKartik** [comment]
Why this is closed without any solution? I am facing same issue in iOS 15

**Comment by vatsal-gadhiya-searce** [comment]
@mmazzarolo To dig further It's not working in dark mode only.

**Comment by vizFlux** [comment]
Reproducible when setting Appearance set to Dark in iOS Settings > Display & Brightness

```JSX
const colorScheme = Appearance.getColorScheme();
const isDarkModeEnabled = colorScheme === 'dark';
console.log(isDarkModeEnabled) // false

<DateTimePickerModal
    isVisible={isDatePickerVisible}
    mode="date"
    display="spinner"
    onConfirm={handleDateConfirm}
    onCancel={hideDatePicker}
    isDarkModeEnabled={isDarkModeEnabled}
/>
```

The issue is colorScheme will alway return 'light' in debugging mode.

The issue is not reproducible when I turn Stop Debugging from the React Native Debug Menu. I think it is related to this issue: https://github.com/facebook/react-native/issues/29144
