### ISSUE TITLE
Android cannot change button text color in Expo managed workflow app

### ISSUE THREAD

**Issue by simplex-linz** [mmazzarolo/react-native-modal-datetime-picker#620]
## Environment

All

## Platforms

Android

## Versions

- Expo ：SDK 43（43.0.3）
- Android:API29、API30
- react-native-modal-datetime-picker:13.0.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):5.0.1
- react-native:0.64.3
- react:17.0.2

## Description

I’m using the react native community Date Time Picker in my managed workflow Expo app
I recently found out that on older Android phones, the text color of the module would render as white, thus not visible on white background.

This only happens when using display “spinner” and not the “calendar” (default) one. In spinner display, I have a green text color on recent Android and white on old ones. In calendar, I have a nice blue color.

I saw a lot of issues on their github to fix this, and all solutions include managing the style file in the android folder.

Another solution I tried was adding a “primaryColor” field in Expo config file, but this changed nothing.

Does someone know how to fix this issue, changing color or preventing it to render as white in a managed expo app?

## Reproducible Demo

[bug Demo for snack.expo](https://snack.expo.dev/@expo151388/rndatetimepicker-text-color)

**Comment by mmazzarolo** [comment]
Hey @simplex-linz , sorry but this is not a react-native-modal-datetime-picker issue. As you mentioned, this is something that should be solved on the Expo (in its config) side — and I don't really know how to do it :/ I would try asking on StackOverflow or check in the community picker if there's any issue related to this.
