### ISSUE TITLE
Navigating through calendar breaks maximumDate prop 

### ISSUE THREAD

**Issue by AlixH** [mmazzarolo/react-native-modal-datetime-picker#624]
## Environment

System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 28.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 29.0.2, 29.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_271 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms

Only tested Android

## Versions

9.2.3

- Android: 11
- iOS:
- react-native-modal-datetime-picker: 9.2.3
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 3.5.0
- react-native: 0.64.2
- react: 17.0.1

## Description

I open the modal with a default date of 2021-03-01
When I navigate to the year 2022, the header of the modal still shows the same month and day e.g 2022-03-01, even if the maximumDate is 2022-01-20. However, the maximum selectable date is 2022-01-20.  So if I click on "confirm" and I don't click on the date inside the calendar, my date will not respect the maximumDate and the output will be 2022-03-01.

## Reproducible Demo

Link to the code: https://github.com/sap-labs-france/ev-mobile/blob/filter_my_car/src/components/search/filter/controls/date/DateFilterControlComponent.tsx

reproductible demo: https://snack.expo.dev/@alixh/react-native-modal-datetime-picker

**Comment by mmazzarolo** [comment]
@AlixH did you already try using directly the community component?
Please see the issue template:

> NOTE: Under the hood react-native-modal-datetime-picker uses [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker).
Before reporting a bug, swap react-native-datetime-picker with [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker) to check if the problem persists. If it does please report the issue in the [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker) repo instead. -->
Please notice that WE WON'T SUPPORT ISSUE IF YOU HAVEN'T TRIED USING THE COMMUNITY COMPONENT ALONE.

**Comment by mmazzarolo** [comment]
👍 thanks for reporting
