### ISSUE TITLE
display='inline' crashes on android

### ISSUE THREAD

**Issue by harshnagalla** [mmazzarolo/react-native-modal-datetime-picker#626]
## Versions

- Android:
- iOS:
- react-native-modal-datetime-picker:
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):
- react-native:
- react:

**Comment by Shogobg** [comment]
@harshnagalla you can use platform [specific code](https://reactnative.dev/docs/platform-specific-code) and set it only on iOS
