### ISSUE TITLE
Expo install - Could not resolve dependency: peer react-native@">=0.65.0"

### ISSUE THREAD

**Issue by fnipo** [mmazzarolo/react-native-modal-datetime-picker#627]
## Environment

System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 13.71 GB / 31.85 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8092744
    Visual Studio: 16.4.29728.190 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: ^0.64.3 => 0.64.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8092744
    npmPackages:
      expo: ~44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: ^0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

## Platforms

Both

## Versions

- react-native-modal-datetime-picker: 4.0.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 13.0.1
- react-native: 0.64.3

## Description

Setup for Expo projects doesn't work with `expo install` command

Expo currently supports `react-native` up to its **0.64.3** version and is unable to find the compatible `react-native-modal-datetime-picker@10.2.0` package

I am not sure whether it requires changes on the `react-native-modal-datetime-picker` or `expo-cli` repo for the mapping to work correctly.

## Reproducible Demo

Command:
> expo install react-native-modal-datetime-picker @react-native-community/datetimepicker

Output:
```
Installing 1 SDK 44.0.0 compatible native module and 1 other package using npm.
> npm install

added 1 package, and audited 902 packages in 2s

30 packages are looking for funding
  run `npm fund` for details

15 vulnerabilities (4 low, 10 moderate, 1 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> npm install --save react-native-modal-datetime-picker
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: habitodo@1.0.0
npm ERR! Found: react-native@0.64.3
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.64.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@">=0.65.0" from react-native-modal-datetime-picker@13.0.1
npm ERR! node_modules/react-native-modal-datetime-picker
npm ERR!   react-native-modal-datetime-picker@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\fpnip\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fpnip\AppData\Local\npm-cache\_logs\2022-02-04T12_34_44_501Z-debug.log

npm exited with non-zero code: 1
Error: npm exited with non-zero code: 1
    at ChildProcess.completionListener (C:\Users\fpnip\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.cp.emit (C:\Users\fpnip\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)
    ...
    at Object.spawnAsync [as default] (C:\Users\fpnip\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at NpmPackageManager._runAsync (C:\Users\fpnip\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:166:31)
    at NpmPackageManager.addAsync (C:\Users\fpnip\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:108:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at actionAsync (C:\Users\fpnip\AppData\Roaming\npm\node_modules\expo-cli\src\commands\installAsync.ts:125:3)
```

**Comment by yesIamFaded** [comment]
Sooo.. what are we ment to do now? I have the same Issue when creating a brand new Project.

**Comment by mmazzarolo** [comment]
@fnipo there's some confusion in the issue report. 

1. In the Versions section you're saying you're on v4.0 (which is extremely old):
<img width="560" alt="image" src="https://user-images.githubusercontent.com/9536354/154072342-8154211b-acf2-4e54-af1b-fb55e53a7920.png">

2. In the Description section you're mentioning v10.2.0:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/9536354/154072442-9eafdcd5-0e67-41b8-a7c8-7681187641ec.png">

3. In the console output you're trying to use v13.0.1:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/9536354/154072521-cecb1583-8d61-449c-8be8-8d6da4cb32c8.png">

From v11 onward we require React-Native 0.65. 
If you're forced to stay on React-Native 0.65, I'd recommend trying `react-native-modal-datetime-picker@10.2.0`.

**Comment by bdgrichards** [comment]
Just ran into this same issue myself and can confirm `react-native-modal-datetime-picker@10.2.0` fixes this for the latest Expo SDK 44, as recommended by @mmazzarolo!

**Comment by mmazzarolo** [comment]
Thank you for reporting back @bdgrichards :)

**Comment by mmazzarolo** [comment]
@SrBrahma sounds good to me, mind submitting a PR for it? Thanks!
