### ISSUE TITLE
In time mode returning Date , Solution is below try it.Basically It's returning time in 24 hours format .

### ISSUE THREAD

**Issue by ArjunVaskale** [mmazzarolo/react-native-modal-datetime-picker#628]
In time mode returning Date , Solution is below try it.
Basically It's returning time in 24 hours format .
So this is how I handled it.
          

> <DateTimePickerModal
>                 isVisible={this.state.showDate}
>                 mode={"time"}
>                 onConfirm={this.onChangeDate}
>                 onCancel={this.hideDatePicker}
>                 date={new Date()}
>                 minuteInterval={1}
>            />

below is my onChangeDate function where I handled this issue.

      onChangeDate = (text: any) => {
        let hours = parseInt(JSON.stringify(text).slice(12, 14)) - 6;
            let minutes = parseInt(JSON.stringify(text).slice(15, 17)) - 30;
            console.warn("befor", hours, text);
        
            if (minutes < 0) {
              hours = hours - 1;
              minutes = 60 + minutes;
            }
            if (hours < 0) {
              hours = 24 + hours;
            }
        
            if (hours > 12) {
              hours = hours - 12;
              console.warn(`Time is => ${hours}:${minutes} AM`);
            } else {
              console.warn(`Time is => ${hours}:${minutes} PM`);
            }     
        this.hideDatePicker(); 
     }

Now It's Working fine.

_Originally posted by @ArjunVaskale in https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/578#issuecomment-1033412960_

**Comment by mmazzarolo** [comment]
Let's keep the discussion in #578 👍
