### ISSUE TITLE
Cant reopen the Picker after confirming the Date

### ISSUE THREAD

**Issue by yesIamFaded** [mmazzarolo/react-native-modal-datetime-picker#630]
## Environment

I cant run that command on Windows it says that is not known.. If you tell me how to run it (even though I dont think that the problem is comming from here) I can provide that info.

## Platforms

Definetly on Android, cant test on IOS atm.

## Versions

- Android: API 29
- iOS: x
- react-native-modal-datetime-picker: ^7.6.1
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): ^3.5.2
- react-native: sdk 42.0.0
- react: 16.13.1

## Description
Basically I cant open the DateTimePicker again after I pressen "OK", if I press cancel it works - I can open it as often as I want.

My Code:

```
  showDatePickerHandler = () => {
    this.setState({
      showDatePicker: true
    })
  }
  hideDatePickerHandler = () => {
    this.setState({
      showDatePicker: false
    })
  }

  handleConfirmDatePicker = (date) => {
    this.resetSOFT()            
    this.setState({ 
      // activityDate: date,
      activityDate: Moment(date).format("YYYY-MM-DD"), // this works !
      checked: false,
      // showDatePicker: false
    },
     () => {
      this.allowedCheckHandler();
      this.changeMonthLock();                            
      this.getVacationLeft();
      this.getHoliday();
      this.isHourstypeCompeting();
      this.fillHourstype();                             
      this.displayWorkingModel(this.state.activityDate); 
    }
    )  
    this.hideDatePickerHandler
  }
```
- The Bug happens even when I dont run the Functions in the setState callback

The actual DateTimePicker:

```
<Button onPress={this.showDatePickerHandler} title="Pick Date"/>

            <DateTimePickerModal 
            isVisible={this.state.showDatePicker}
              // style={{width: "60%"}}
              // value={this.state.activityDate}
              date={this.state.activityDate}
              placeholderText="Bitte Datum wählen"
              mode="date"
              onConfirm={this.handleConfirmDatePicker}
              onCancel={this.hideDatePickerHandler}
            />
```
I tried using the "orignial" Community DateTimePicker but it is terrible.

UPDATE: It seems like my hideDatePickerHandler is not getting called in the handleConfirmDatePicker - so the state gets never set to false when confirming

So basically where would you move that call to guarantee that it runs? 
I tried onHideAfterConfirm (and in onHide) and set the State to false again - wich works because I can see it in the logs, but when I press the Button again now it crashes the app........ 😠

**Comment by yesIamFaded** [comment]
So you labeled my BUG as invalid.. what do I do now? This is a critical BUG that makes the Module unusable. I provided all the info I have. 🙏

**Comment by mmazzarolo** [comment]
@yesIamFaded , see the issue template:

> Let us know how to reproduce the issue. Include a code sample or share a project that reproduces the issue.
Follow the guidelines for providing a minimal example: https://stackoverflow.com/help/mcve
Please notice that WE WON'T SUPPORT ISSUE REPORTS THAT DON'T HAVE A MINIMAL REPRODUCIBLE EXAMPLE. 

The code you provided is not a minimal reproducible example: we can't run it and it has a ton of variable/context we don't have. 
Please copy the example from https://github.com/mmazzarolo/react-native-modal-datetime-picker#usage and reproduce it from there. 
Also, please notice that what you're reporting is not a "bug", but more of a support request (that we can't provide in this module).
