### ISSUE TITLE
Unable to install using Expo - peer dependency errors

### ISSUE THREAD

**Issue by dmathisen** [mmazzarolo/react-native-modal-datetime-picker#639]
## Environment

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 18.66 GB / 31.84 GB

  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD        
    npm: 7.22.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found

  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found

  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
    Visual Studio: Not Found

  Languages:
    Java: Not Found

  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-native-windows: Not Found

  npmGlobalPackages:
    *react-native*: Not Found

## Platforms

All

## Versions

- Android: 11
- iOS: 15
- expo: 5.3.1
- react-native-modal-datetime-picker: 13.1.2
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 6.1.2 / 4.0.0
- react-native: 0.64.3
- react: 17.0.1

## Description

When I run `expo install react-native-modal-datetime-picker @react-native-community/datetimepicker`, it installs react-native-community/datetimepicker **4.0.0** and I'm getting errors re: unresolved dependencies. Screenshot below.

However, when I install using `npm install ...` it installs react-native-community/datetimepicker **6.1.2** and everything works fine. I don't know if this is an Expo issue, community datepicker or a mmazzarolo datepicker issue.

![image](https://user-images.githubusercontent.com/684701/163092265-7316f3aa-b70e-4414-83fb-e5a0c2166f9f.png)
 
Dependencies:

![image](https://user-images.githubusercontent.com/684701/163092866-454e3d2f-21de-4be9-9e47-ddfb8d6fc59c.png)

## Reproducible Demo

Steps:
`npm install --global expo-cli`
`expo init my-project`
`expo install react-native-modal-datetime-picker @react-native-community/datetimepicker`

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/627 ?

**Comment by dmathisen** [comment]
Yep, same one! Thanks. Closing.

It looks like the answer is...
1) Use `npm install...` instead of  `expo install...`
or
2) Do `expo install react-native-modal-datetime-picker@10.2.0 @react-native-community/datetimepicker`
