### ISSUE TITLE
Error in recent react-native version

### ISSUE THREAD

**Issue by hyochan35** [mmazzarolo/react-native-modal-datetime-picker#64]
I recently updated to new react-native 0.46.1 and following bugs appear in this library.
It appears when I set isVisible state to true.

![image](https://user-images.githubusercontent.com/20625109/28490240-fb1d5bec-6f0f-11e7-8068-9c6ec0b91a21.png)

please fix this issue in npm module. Thank you.

**Comment by mmazzarolo** [comment]
Related to [this react-native-modal issue](https://github.com/react-native-community/react-native-modal/issues/42).  
I'll try to investigare asap. 
Help on this would be apreciated.

**Comment by hyochan35** [comment]
Can you change your modal import to 'react-native-modalbox'? (link https://github.com/maxs15/react-native-modalbox)
I've been using react-native-modal but changed to this one and error is gone.

Also you can close modal touching the background which is useful.

I feel much comfortable using this and it also fixes the bug.
Hope you can change your library to this one!

**Comment by mmazzarolo** [comment]
@hyochan35 sorry but I won't change the modal component used for this module.    

You can still contribute to the issue of `react-native-modal` though or, in the meanwhile, you can stay on the previous RN version :)

Also, are you on Expo?

**Comment by hyochan35** [comment]
Yes I am on Expo.

Sad to hear from you that you won't change the modal component.

Can I pull your source and fix your library to my own taste and use it for my project?

What I want from your library it to close the modal when tab on back without clicking on cancel button.

**Comment by mmazzarolo** [comment]
It's an Expo issue then, I'll investigate it soon (I never used Expo).    

Yep, you can fork it as much as you want, of course!

**Comment by hyochan35** [comment]
Thanks. Glad to hear that. I will update your library to react-native-modalbox for my project.

Also checkout my starter project for React-Native if you don't like expo.
https://github.com/hyochan35/starter-rn.git

**Comment by mmazzarolo** [comment]
Hey @hyochan35, from my testing the issue seems to be related to the last Expo release.  

Also, [I opened an issue on the official Expo repo](https://github.com/expo/expo/issues/404).

**Comment by mmazzarolo** [comment]
The issue has been fixed in the last Expo release (`19.0.1`)
