### ISSUE TITLE
How to hide previous time on current date

### ISSUE THREAD

**Issue by Etelligens-design** [mmazzarolo/react-native-modal-datetime-picker#642]
## Versions

- Android:
- iOS:
- react-native-modal-datetime-picker:
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):
- react-native:
- react:

**Comment by Etelligens-design** [comment]
not getting solution

 "react-dom": "^17.0.2",
 "react-native": "0.66.1",
 "react": "17.0.2",

**Comment by christopher-18** [comment]
@Etelligens-design Did you got it working? Facing same issue on android. 
@mmazzarolo Any suggestions?
