### ISSUE TITLE
Potentially missing translation key

### ISSUE THREAD

**Issue by ceIia** [mmazzarolo/react-native-modal-datetime-picker#643]
## Platforms

iOS only, as we're using the inline datepicker.

## Versions

- Android: N/A
- iOS: 15.5
- react-native-modal-datetime-picker: 13.1.2
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 4.0.0
- react-native: 0.64.3
- react: 17.0.1

## Description

hey! i'm currently using the lib for our datepicker, works fine. the calendar part itself of the inline version of the component seems to translate itself fine depending on the native/phone's locale. i did however need to use the `locale` prop to localize the time picker (i.e. 1:00pm to 13:00 in France), that works fine. 

but there is still a string that did not get translated, and that i cannot find a prop for, how can i access it?

<img width="609" alt="Screenshot 2022-05-18 at 12 36 17" src="https://user-images.githubusercontent.com/25929147/169021364-960fa0a8-ebd7-477a-9b93-23526cdbdd17.png">

thanks a lot for making this lib, saved me a lot of time, and works perfectly :)

## Reproducible Demo
```tsx
const { t, i18n } = useTranslation();

<DateTimePickerModal
        isVisible={isDatePickerVisible}
        mode="datetime"
        onConfirm={handleDateSelect}
        onCancel={() => setDatePickerVisible(false)}
        confirmTextIOS={t('post.new.datepicker_confirm')}
        cancelTextIOS={t('post.new.datepicker_cancel')}
        minimumDate={new Date()}
        display={Platform.OS === 'ios' ? 'inline' : 'default'}
        locale={i18n.language}
/>
```

**Comment by mmazzarolo** [comment]
Hey @ceIia ! 
Could you please follow the issue template? I can't help you unless you follow it :) 
Also, I think the issue is coming from https://github.com/react-native-community/react-native-datetimepicker
