### ISSUE TITLE
Not opening in production, works fine in development

### ISSUE THREAD

**Issue by basit3407** [mmazzarolo/react-native-modal-datetime-picker#645]
## Environment
 System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    npmPackages:
      expo: ~45.0.0 => 45.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: ^0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

## Platforms

Android

## Versions

- react-native-modal-datetime-picker:13.1.2
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):6.1.2
- react-native:0.68.2
- react:17.0.2

## Description

Picker just doesn't open in production. I tried the sample example also. Following is the code of app.js (same of sample example):

import React, { useState } from "react";
import { Button, View } from "react-native";
import DateTimePickerModal from "react-native-modal-datetime-picker";

[const Example = () => {
  const [isDatePickerVisible, setDatePickerVisibility] = useState(false);

  const showDatePicker = () => {
    setDatePickerVisibility(true);
  };

  const hideDatePicker = () => {
    setDatePickerVisibility(false);
  };

  const handleConfirm = (date) => {
    console.warn("A date has been picked: ", date);
    hideDatePicker();
  };

  return (
    <View>
      <Button title="Show Date Picker" onPress={showDatePicker} />
      <DateTimePickerModal
        isVisible={isDatePickerVisible}
        mode="date"
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
      />
    </View>
  );
};

export default Example;

When i used the original library i.e @react-native-community/datetimepicker it works fine. I have made a separate branch in 
testing repo for checking result in original library

## Reproducible Demo
git clone https://github.com/basit3407/testing_time_picker
run npm install
run eas build -p android --profile preview

**Comment by dim0627** [comment]
I have same issue
And maybe it is as well
https://github.com/react-native-datetimepicker/datetimepicker/issues/613


```
TypeError: null is not an object (evaluating 'o.NativeModules.RNDatePickerAndroid.dismiss')
  at ? (app:///index.android.bundle:2139:760)
  at y(app:///index.android.bundle:124:587)
  at ? (app:///index.android.bundle:124:1892)
  at y(app:///index.android.bundle:124:587)
  at o(app:///index.android.bundle:124:1068)
  at ? (app:///index.android.bundle:124:1425)
  at c(app:///index.android.bundle:120:205)
  at X(app:///index.android.bundle:120:1586)
  at _(app:///index.android.bundle:120:484)
  at h(app:///index.android.bundle:124:1409)
  at _invoke(app:///index.android.bundle:124:1461)
  at async(app:///index.android.bundle:124:3864)
  at value(app:///index.android.bundle:2139:651)
  at dismiss(app:///index.android.bundle:2142:1775)
  at ? (app:///index.android.bundle:2135:571)
  at ci(app:///index.android.bundle:100:82557)
  at unstable_runWithPriority(app:///index.android.bundle:197:3807)
  at ? (app:///index.android.bundle:100:82023)
  at W(app:///index.android.bundle:197:2867)
  at n(app:///index.android.bundle:197:392)
  at k(app:///index.android.bundle:126:536)
  at callTimers(app:///index.android.bundle:126:2633)
  at value(app:///index.android.bundle:49:3493)
  at ? (app:///index.android.bundle:49:748)
  at value(app:///index.android.bundle:49:2539)
  at value(app:///index.android.bundle:49:720)
  at value([native code])
```

**Comment by basit3407** [comment]
My problem was that i had not installed the parent library of react native community. strangely it was working ok in expo go, however in production this issue was coming. once i installed the parent library my issue was resolved

**Comment by onurcskun** [comment]
@basit3407 hey! When I try to install @react-native-community/datetimepicker, there will be an error like "Tried to register two views with the same name RNDateTimePicker". did you face with it?

**Comment by AbdulmalekAlshugaa** [comment]
When I try to install @react-native-community/datetimepicker, there will be an error like "Tried to register two views with the same name RNDateTimePicker". did you face with it?

**Comment by dodyeid** [comment]
Im having this issue as well. date time picker modal not working in production but working fine in expo go. unsure how to solve! "My problem was that i had not installed the parent library of react native community." what does this mean? which parent library? how do i install? Thanks in advance!

**Comment by sanket2226** [comment]
what is solutions @basit3407

**Comment by tonoli** [comment]
Hello everyone! 

Any update on this @basit3407 ? 

 I have the same issue: 
 I'm using a library `tamagui-extras` that has react-native-modal-datetime-picker as peer dependency 

But I get this error: 
`requireNativeComponent: RNDateTimePicker was not found in the UIManager.
`
and when I install it manually on my expo app with `npx expo install react-native-modal-datetime-picker @react-native-community/datetimepicker` 

I get the error above: `Tried to register two views with the same name RNDateTimePicker`

Don't understand why you closed the issue it seems to be an ongoing one

Many thanks for your help and consideration!

**Comment by basit3407** [comment]
> what is solutions @basi

> Hello everyone!
> 
> Any update on this @basit3407 ?
> 
> I have the same issue: I'm using a library `tamagui-extras` that has react-native-modal-datetime-picker as peer dependency
> 
> But I get this error: `requireNativeComponent: RNDateTimePicker was not found in the UIManager. ` and when I install it manually on my expo app with `npx expo install react-native-modal-datetime-picker @react-native-community/datetimepicker`
> 
> I get the error above: `Tried to register two views with the same name RNDateTimePicker`
> 
> Don't understand why you closed the issue it seems to be an ongoing one
> 
> Many thanks for your help and consideration!

my issue was resolved apparently. that is why i had closed it. you can read my closing comment. Thank you.

**Comment by basit3407** [comment]
> what is solutions @basit3407

my issue was resolved apparently. that is why i had closed it. you can see my closing comment

**Comment by tonoli** [comment]
> @basit3407 hey! When I try to install @react-native-community/datetimepicker, there will be an error like "Tried to register two views with the same name RNDateTimePicker". did you face with it?

Did you find any solution for this?

**Comment by basit3407** [comment]
> > @basit3407 hey! When I try to install @react-native-community/datetimepicker, there will be an error like "Tried to register two views with the same name RNDateTimePicker". did you face with it?
> 
> Did you find any solution for this? 

I didn't face this problem. Actually it says in the docs that we have to install it as well. 

https://github.com/mmazzarolo/react-native-modal-datetime-picker
