### ISSUE TITLE
Date picker modal does not showing cancel and confirm buttons on android

### ISSUE THREAD

**Issue by vimukthinuclei** [mmazzarolo/react-native-modal-datetime-picker#652]
## Platforms

Android

## Versions

- react-native-modal-datetime-picker: 13.1.2
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 6.3.1
- react-native: 0.66.0
- react: 17.0.2

## Description

Date picker modal does not showing cancel and confirm buttons on android.  But button are in the position we can press. But not visible for some reason.

Works on IOS perfect.

![WhatsApp Image 2022-08-08 at 10 00 37 AM](https://user-images.githubusercontent.com/89640477/183355804-5f44e5dd-466d-4220-8563-423a17b2132f.jpeg)

## Reproducible Demo

```
<DateTimePickerModal
    isVisible={dateModalStatus}
    mode={'date'}
    date={new Date(birth)}
    display={'spinner'}
    onConfirm={date => {
      timeStampDate?.(date);
      onChange(moment(date).format('YYYY-MM-DD'));
      setDateModalStatus(false);
    }}
    onCancel={() => setDateModalStatus(false)}
/>
```

**Comment by mmazzarolo** [comment]
👋 please follow the entire issue template

Under the hood react-native-modal-datetime-picker uses [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker).
Before reporting a bug, swap react-native-datetime-picker with [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker) to check if the problem persists. If it does please report the issue in the [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker) repo instead. 
Please notice that WE WON'T SUPPORT ISSUE IF YOU HAVEN'T TRIED USING THE COMMUNITY COMPONENT ALONE. 
- For QUESTIONS and FEEDBACK, please use the [discussions](https://github.com/mmazzarolo/react-native-modal-datetime-picker/discussions) section.  
Also, please check the FAQs before submitting new issues. Thanks!
