### ISSUE TITLE
modal not showing in android

### ISSUE THREAD

**Issue by vivekMss** [mmazzarolo/react-native-modal-datetime-picker#661]
## Platforms
Android

## Versions

- Android:
- iOS:
- react-native-modal-datetime-picker:
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):
- react-native:
- react:

## Description
although if i'm using react-native-community/datetimepicker pacakage n get date picker it does get but there's some issue 
so i want to us this package instead of using the community one cause it's working fine on android

**Comment by mmazzarolo** [comment]
We can't help unless you provide **all** the info asked in the issue template.
