### ISSUE TITLE
Date changes - then slingshots back to original date

### ISSUE THREAD

**Issue by guts716** [mmazzarolo/react-native-modal-datetime-picker#665]
I love this library and I have used it for a few weeks. Today, I noticed a weird behavior that has not shown in the past. Has anyone seen something like this? I have no idea what could be causing it, as I have had it working in the past with no changes. 

I have only noticed this problem on Android. What could possibly be causing this? Nothing has changed from when it was working days ago. 

![bug](https://user-images.githubusercontent.com/61165909/190483753-87ac0832-4d60-41de-9f9c-9a0da94325c8.gif)

**Comment by SutharRohit** [comment]
I am facing issue in android

**Comment by mmazzarolo** [comment]
I'm sorry but I can't help you unless you follow the issue template :/

**Comment by SutharRohit** [comment]
I am facing the same issue with android.. there is one logic if no default date is selected then I have to show 18 years before the date.

but, when I set this kind of thing. then it is behaving the same as above...
I removed this `date` props, then it is working.. but the logic for 18 years is not working.

```
<DateTimePickerModal
        isVisible={isDatePickerVisible}
        mode={StringConstant.MODE_DATE}
        date={
          inputDOB && inputDOB !== ''
            ? new Date(moment(inputDOB))
            : new Date(moment().subtract(18, 'years'))
        }
        maximumDate={new Date(moment().subtract(18, 'years'))}
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
      />
```
