### ISSUE TITLE
Unimplemented component: <ModalHostView>

### ISSUE THREAD

**Issue by emelie** [mmazzarolo/react-native-modal-datetime-picker#671]
## Environment

System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 511.44 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: Not Found
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms

iOS

## Versions

- iOS: 15.4
- react-native-modal-datetime-picker: 14.0.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 6.5.2
- react-native: 0.70.0
- react: 18.1.0

## Description

I have been using this package previously without any issues. In my latest project, using React Native version 0.70.0, I am getting the following error:

Unimplemented component: `<ModalHostView>`

![react-native-modal-datetime-picker-issue](https://user-images.githubusercontent.com/994567/196961660-0f464f6e-6e02-4789-8dee-de2ba3abe685.png)

I found this related issue [https://github.com/facebook/react-native/issues/33652](https://github.com/facebook/react-native/issues/33652) and it seems to be a problem with the new Architecture and the new renderer (Fabric).
Will `react-native-modal-datetime-picker` implement Fabric in the future?

## Reproducible Demo

This error message can be seen by simply using DateTimePickerModal component.

**Comment by mMarcos208** [comment]
Not running in **Android** too.

the same issue.

**Hermes** and **newArchEnabled** enabled.

_CMake Error at /home/marconi/Documentos/pocs/testingLibrariesnewArc/android/app/build/generated/rncli/src/main/jni/Android-rncli.cmake:6 (add_subdirectory):
    add_subdirectory given source
    "/home/marconi/Documentos/pocs/testingLibrariesnewArc/node_modules/@react-native-community/datetimepicker/android/build/generated/source/codegen/jni/"
    which is not an existing directory.
  Call Stack (most recent call first):
    /home/marconi/Documentos/pocs/testingLibrariesnewArc/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:59 (include)
    CMakeLists.txt:7 (include)_

**Comment by BraveEvidence** [comment]
If interested I have achieved this functionality for new architecture using fabric https://www.youtube.com/watch?v=W3m-8_QuC14&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=4 and
https://www.youtube.com/watch?v=38dpw_s2YKE&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=3

**Comment by mmazzarolo** [comment]
The one thing I'm missing here is: what changes should we make to `react-native-modal-datetime-picker` to support the new arch? We don't deal directly with native code in this project, that lives in [`@react-native-community/datetimepicker`](https://github.com/react-native-community/react-native-datetimepicker).

**Comment by emelie** [comment]
This was an issue with React Native. React Native's Modal component now supports the new architecture.
