### ISSUE TITLE
Week Name not showing on real device but shows on simulator

### ISSUE THREAD

**Issue by ajimae** [mmazzarolo/react-native-modal-datetime-picker#674]
## Environment
MacBook, Running MacOS 12.5.1

## Platforms
iOS

## Versions

- Android:
- iOS: 16.1
- react-native-modal-datetime-picker: 14.0.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): [6.1.3, 6.7.0, 6.3.2]
- react-native: 0.70.4
- react: 18.1.0

## Description
Having issues displaying the **week names** on the calendar (Sun, Mon etc) on iPhone 12 running iOS 15.6.1 however, on the iOS simulator it works and shows all the week names.

## Reproducible Demo
![image](https://user-images.githubusercontent.com/32770340/202867279-02e27e62-aa88-4ed9-8000-41bb22ba5a24.png)

## Code
```js
<DateTimePickerModal
  isVisible={isDatePickerVisible}
  mode={isDate ? "date" : "time"}
  onConfirm={handleConfirm}
  onCancel={hideDatePicker}
  display={isDate ? "inline" : "spinner"}
/>
```

**Comment by ajimae** [comment]
@mmazzarolo 

Why would you label this issue as invalid?

Did you even take the time to run it on a real device.

Don't be quick to add an `invalid` label if you can show this works on a real device specified in the issue.

**Comment by mmazzarolo** [comment]
It's marked as invalid because it doesn't follow the issue template and there's no indication of you testing the community picker (as stated in the issue template), so I can't give proper support, sorry.

**Comment by mmazzarolo** [comment]
Let's continue the discussion in #672
