### ISSUE TITLE
Change Default color of date time picker

### ISSUE THREAD

**Issue by MariamIdeen** [mmazzarolo/react-native-modal-datetime-picker#678]
### Discussed in https://github.com/mmazzarolo/react-native-modal-datetime-picker/discussions/677

<div type='discussions-op-text'>

<sup>Originally posted by **MariamIdeen** December 12, 2022</sup>
How to change the color of the date time picker according to the app theme while using expo. (Need to change blue to green)
Versions: 
      "expo": "~46.0.16",
      "react": "18.0.0",
      "react-native": "0.69.6",
      "react-native-modal-datetime-picker": "^14.0.0",
![Screenshot](https://user-images.githubusercontent.com/117250792/206965268-696776b7-0200-4a75-ad2a-549c31728365.jpeg)
</div>

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker#how-do-i-change-the-color-of-the-android-date-and-time-pickers
