### ISSUE TITLE
Iphone X keyboard overlapping issue

### ISSUE THREAD

**Issue by manishpandia** [mmazzarolo/react-native-modal-datetime-picker#679]
Verified on iOS application
Device- iPhone X
iOS version - 16.0.3 (latest)

![iosIssue](https://user-images.githubusercontent.com/73522277/207608566-c43c68b1-8693-421f-ac0b-b513b8b9cdf6.png)

**Comment by mmazzarolo** [comment]
Please follow the issue template, thank you!
