### ISSUE TITLE
Set custom time slots

### ISSUE THREAD

**Issue by tanerparcali** [mmazzarolo/react-native-modal-datetime-picker#687]
Can we specify custom time intervals in date and time format? For example, if we want to make only 11 am and 10 pm range selectable, is there a way to do this?

Thanks.

**Comment by mmazzarolo** [comment]
Hey, the only way to do it is by using [@react-native-community/datetimepicker](https://github.com/react-native-community/react-native-datetimepicker) the `minimumDate` and `maximumDate` props.
