### ISSUE TITLE
Swap styles in CancelButton (ios)

### ISSUE THREAD

**Issue by madly0894** [mmazzarolo/react-native-modal-datetime-picker#689]
Hi. I have a problem with custom styles **customCancelButtonIOS**. I can't style the **backgroundColor** because the passed style comes first. You are correct put style for the **ConfirmButton** but not for the **CancelButton**.
You correctly marked the places in the 1st picture. But in the 2nd photo he does not see him, because he goes first. Would you please switch places for **CancelButton**?

// Confirm button
![image](https://user-images.githubusercontent.com/29377127/214876894-705e4944-5524-41c0-89d1-93807124fa8c.png)

// Cancel button
![Screenshot from 2023-01-26 19-29-31](https://user-images.githubusercontent.com/29377127/214880722-f0100170-b615-4b00-87d7-f32d09f9467e.png)

**Comment by mmazzarolo** [comment]
Ha! Good catch. Mind submitting a PR to fix it?

**Comment by madly0894** [comment]
Yes, I think. This component would give us the ability to style it. Otherwise, hardcoding turns out

**Comment by madly0894** [comment]
> Ha! Good catch. Mind submitting a PR to fix it?

Yes, I think. This component would give us the ability to style it. Otherwise, hardcoding turns out

**Comment by mucahittceylann** [comment]
same problem, is it resolved
