### ISSUE TITLE
Date Picker Off By 1 Day

### ISSUE THREAD

**Issue by VISWESWARAN1998** [mmazzarolo/react-native-modal-datetime-picker#692]
When using this date picker anywhere between 12:00 AM to 12:59 AM (I suspect) the picked date is off by one day!

For example my code has mode selected to **date**:

```javascript
<DateTimePickerModal
    isVisible={dp_visible}
    mode="date"                    
    onConfirm={handleConfirm}
    onCancel={hideDatePicker}
/>
```

And I am picking 21st of February 2023 and I would expect the results to come 21st of February but the picked date is shown for 20th of February like this:

```
A date has been picked:  2023-02-20
Original date  2023-02-20T17:52:01.000Z
```

My handleConfirm code:

```javascript
const handleConfirm = (date) => {
    console.log("A date has been picked: ", date.toISOString().split('T')[0]);
    console.log("Original date ", date);        
    hideDatePicker();
};
```

## Note:
Date picker is **usually working fine on my working hours (09:00 AM to 06:00PM)**

## Platforms
Both

**Comment by mmazzarolo** [comment]
👋 I'm sorry but I won't be able to help you unless you follow the issue template.

**Comment by shahawi** [comment]
Use this

<DateTimePickerModal
    isVisible={dp_visible}
    mode="date"                    
    onConfirm={handleConfirm}
    onCancel={hideDatePicker}
    timeZoneOffsetInMinutes={0}
/>

**Comment by shahawi** [comment]
This may work
timeZoneOffsetInMinutes={0}
