### ISSUE TITLE
Can't change month

### ISSUE THREAD

**Issue by minifisk** [mmazzarolo/react-native-modal-datetime-picker#693]
## Environment

ystem:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 46.53 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.3 is now available (your project is running on v0.70.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.3
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.70.5
info For more info, check out "https://reactnative.dev/docs/upgrading".

## Platforms

Only tested on iOS so far

## Versions

- Android:
- iOS:
- react-native-modal-datetime-picker: "^14.0.1"
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):
- react-native:  "0.70.5"
- react:

## Description

Nothing happens when I click on the arrows to switch month

## Reproducible Demo

 ```
 const [datePickerOpened, setDatePickerOpened] = useState(false);


  const handleDateConfirm = (date) => {
    let date_string = date.toISOString().substring(0, 10);
    setSelectedReceipt({
      ...selectedReceipt,
      purchase_date: date_string,
    });
    hideDatePicker();
  };

  const hideDatePicker = () => {
    setDatePickerOpened(false);
  };

  const renderDateTimePickerModal = () => {
    return (
      <DateTimePickerModal
        date={new Date(selectedReceipt.purchase_date)}
        isVisible={datePickerOpened}
        mode="date"
        onConfirm={handleDateConfirm}
        onCancel={hideDatePicker}
      />
    );
  };

return (
      {renderDateTimePickerModal()}
)
```

**Comment by mmazzarolo** [comment]
Please follow the issue template. I can't use your reproducible example. Please edit the `README.md` example to reproduce your issue.
