### ISSUE TITLE
DatePicker reopens on Android after date select

### ISSUE THREAD

**Issue by vp-donutsocial** [mmazzarolo/react-native-modal-datetime-picker#699]
## Environment

System:
    OS: macOS 12.6.3
    CPU: (8) arm64 Apple M1
    Memory: 98.23 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
    Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/deodes/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms

Android

## Versions

- Android: 12
- react-native-modal-datetime-picker: ^15.0.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): ^7.0.1
- react-native: 0.70.6
- react: 18.1.0

## Description

After selecting new Date in Android, modal reopens. After second select, everything is fine
## Reproducible Demo

```
const showDatePicker = () => {
  setDatePickerVisibility(true);
};

const hideDatePicker = () => {
  setDatePickerVisibility(false);
};

const handleConfirm = (date: Date) => {
  setDate(date);
  setDatePickerVisibility(false);
};

return (
    <View>
      <TextButtonInput
        style={styles.input}
        label="Date of birth"
        value={date ? formatDate(date) : ''}
        onPress={showDatePicker}
      />
      <DateTimePickerModal
      display="inline"
      isVisible={isDatePickerVisible}
      mode="date"
      onConfirm={handleConfirm}
      onCancel={hideDatePicker}
      date={date}
      minimumDate={new Date('1900')}
      maximumDate={new Date()}
      />
    </View>
)
```

https://user-images.githubusercontent.com/126552148/233345001-b817b9c8-529a-4ab7-96d7-31fe034b0129.mov

**Comment by mmazzarolo** [comment]
In your example in the `onConfirm` callback you're setting a new date (`setDate(date);`) that you pass down to the component (that triggers a re-render) before hiding it. 
By the way, in these cases I recommend starting from scratch from the example in the README to understand what is causing issues on your ends.

**Comment by Pragnesh-Dharajiya** [comment]
https://github.com/mmazzarolo/react-native-modal-datetime-picker/assets/70627522/d859f02c-02ad-4c22-b6f4-c4e5e356277f

**Comment by Pragnesh-Dharajiya** [comment]
<DateTimePickerModal
                        date={
                          (item.startTime && new Date(item.startTime)) ||
                          new Date()
                        }
                        isVisible={startDatePickerVisible}
                        mode="time"
                        onConfirm={(date: Date) => {
                          handleStartDateConfirm(date, index);
                        }}
                        onCancel={() => setStartDatePickerVisible(false)}
                      />

**Comment by Pragnesh-Dharajiya** [comment]
const handleStartDateConfirm = (date: Date, index: number) => {
    const dates = moment(date).format('YYYY-MM-DD HH:mm:ss');

    let tempWeeklyData = [...weeklyData];
    if (!switchValue) {
      tempWeeklyData[index].startTime = dates;
    } else {
      tempWeeklyData?.forEach(item => {
        item.startTime = dates;
      });
    }

    setWeeklyData([...tempWeeklyData]);
    setStartDatePickerVisible(false);
  };
