### ISSUE TITLE
Android datetime style - do we have choice to select date and time in one page

### ISSUE THREAD

**Issue by alickcai** [mmazzarolo/react-native-modal-datetime-picker#700]
In IOS devices, we can select datatime in one-go and can we do same in Android?
In Android devices, the default style is select date first and time in second page...and I haven't found params to change...

**Comment by alickcai** [comment]
even if I set display = "inline", time selector is not shown in Andoird
in IOS if we use "inline" style, time selector is hidden half and not working properly

**Comment by mmazzarolo** [comment]
> In IOS devices, we can select datatime in one-go and can we do same in Android?

Nope, as far as I know you can't. You have to use the two-steps way.
