### ISSUE TITLE
Native module RNDatePicker tried to override RNDatePicker

### ISSUE THREAD

**Issue by DiguinhoLNS** [mmazzarolo/react-native-modal-datetime-picker#701]
![Screenshot_20230428-105251](https://user-images.githubusercontent.com/58148787/235167096-13f539ab-41e2-466c-abf9-f0b04caec577.png)

"@react-native-community/datetimepicker": "^7.0.1",
"react-native-modal-datetime-picker": "^15.0.0",

**Comment by DiguinhoLNS** [comment]
@mmazzarolo can you help me with this issue?

**Comment by DusanSpasojevic98** [comment]
@mmazzarolo @DiguinhoLNS  This happened to me when I had  @react-native-community/datetimepicker also installed, you can downgrade this package version to  "@react-native-community/datetimepicker": "^6.7.5") for a temporary solution.

**Comment by chunghn** [comment]
Looking for a proper update to fix it.
