### ISSUE TITLE
`onCancel` type includes `date` parameter 

### ISSUE THREAD

**Issue by robert-nash** [mmazzarolo/react-native-modal-datetime-picker#709]
The  typings currently include a date parameter for the onCancel function. As far as I can tell this is not correct? I don't think this would ordinarily cause much of an issue but I am trying to create a component which implements ReactNativeModalDateTimePickerProps for use on web which has brought it to the fore. 

https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/4aee8ae499d4dec2989ca8cf38462de06f18c295/typings/index.d.ts#L274

**Comment by mmazzarolo** [comment]
Yep looks like a bug might submitting a PR?
