### ISSUE TITLE
Not able to see Date and time picker, Only Confirm and Cancel buttons are visible in IOS after upgrade to latest version 17.0.0 

### ISSUE THREAD

**Issue by kaushalpanda22** [mmazzarolo/react-native-modal-datetime-picker#717]
After upgrading the react-native-modal-datetime-picker version from "9.1.0" to "17.0.0", i am not able to see Date and time picker and only Confirm and Cancel buttons are visible in IOS after upgraded to latest version 17.0.0.
<img width="441" alt="Screenshot 2023-08-11 at 2 33 57 PM" src="https://github.com/mmazzarolo/react-native-modal-datetime-picker/assets/63090701/2c169113-3655-4afb-9432-904361239a0d">

**Comment by kaushalpanda22** [comment]
It has been resolved  after go through this FAQ https://github.com/mmazzarolo/react-native-modal-datetime-picker#why-is-the-picker-is-not-showing-the-right-layout-on-ios--14  and updating the latest version of "@react-native-community/datetimepicker": "**7.4.1**"

**Comment by Buk1m** [comment]
Since updating to 7.4.2 didn't help me, here is a link to the solution that worked:

https://github.com/react-native-datetimepicker/datetimepicker/issues/749
