### ISSUE TITLE
Time range picker

### ISSUE THREAD

**Issue by jbyrneie** [mmazzarolo/react-native-modal-datetime-picker#72]
Can you support picking multiple times or a range of times when I open the Calendar for a day

**Comment by mmazzarolo** [comment]
Short answer: no 😞 

This component behind the hood uses react-native's own [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html). 
This means that a feature like the one you're proposing must be supported by both DatePickerAndroid and DatePickerIOS for being implemented correctly on `react-native-modal-datetime-picker`.

**Comment by Niphery** [comment]
@mmazzarolo not sure if it recently changed but DatePickerAndroid & DatePickerIOS both support now minDate and maxDate.
