### ISSUE TITLE
How can i set a format?

### ISSUE THREAD

**Issue by lXSPandora** [mmazzarolo/react-native-modal-datetime-picker#73]
Hello,
How can i set a format to the datepicker to pick the data like yyyy-mm-dd.

Example
2017-08-14

**Comment by mmazzarolo** [comment]
Hello @lXSPandora, this is more a Javascript related question then a `react-native-modal-datetime-picker` one.   
You should handle the date formatting on your own component.  
The date returned by `react-native-modal-datetime-picker` is a plain JS Date object so you can format it using [the plain JS Date API](https://www.w3schools.com/js/js_date_formats.asp), [date-fns](https://date-fns.org/docs/format), [Moment.js](https://momentjs.com/) or any other library you want.
