### ISSUE TITLE
keyboardShouldPersistTaps={true} Deprecated

### ISSUE THREAD

**Issue by davidroman0O** [mmazzarolo/react-native-modal-datetime-picker#76]
Hi!

I'm just reporting a small issue! :)

@mmazzarolo you should change the keyboardShouldPersistTaps={true} to keyboardShouldPersistTaps="always".

'Cause it's deprecated on the console :)

Thx a lot for you lib! :)

**Comment by mmazzarolo** [comment]
Hi @davidroman0O, I'm probably missing something `react-native-modal-datetime-picker` is not using any `ScrollView`/`ListView`/`keyboardShouldPersistTaps` prop 🤔

**Comment by davidroman0O** [comment]
Aaaand https://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps

In fact, it's in the ScrollView ! :p

**Comment by davidroman0O** [comment]
I guess I missed a scrollview on my side...

**Comment by davidroman0O** [comment]
@mmazzarolo It's not your fault.
It's the react-native-modal-picker i use on my side. 
Sorry!! :p

**Comment by mmazzarolo** [comment]
@davidroman0O no worries :)
