### ISSUE TITLE
Does it support TimePicker functionality also ?

### ISSUE THREAD

**Issue by ajaysaini-sgvu** [mmazzarolo/react-native-modal-datetime-picker#77]
Hi I couldn't find a way to open `TimePicker` using this package. Suggested example in read.me opens `DatePicker` only. 

Can you confirm if it supports `TimePicker` also ? If so then how ?

**Comment by mmazzarolo** [comment]
Hi!
Take a look at the `mode` prop on the README.md:

| Name | Type| Default | Description |
| --- | --- | --- | --- |
| mode | string | 'date' | Datepicker? 'date' Timepicker? 'time' Both? 'datetime' |
