### ISSUE TITLE
backdrop setter

### ISSUE THREAD

**Issue by ezha86** [mmazzarolo/react-native-modal-datetime-picker#78]
hi there
is there any chance to set props that use react-native-modal eg backdropColor/backdropOpacity etc ?

**Comment by mmazzarolo** [comment]
Hello @ezha86 
That's doable for sure, but it would work only for iOS thought... 🤔

**Comment by ezha86** [comment]
yes, only for ios. i have are few modals in my screen and 1 datetime picker and it would be great to add possibility to control it backdropColor/backdropOpacity  for consistency

**Comment by mmazzarolo** [comment]
Hey @ezha86, I added `reactNativeModalPropsIOS` on last [v4.1.0 release](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v4.10.0).

**Comment by ezha86** [comment]
Brilliant
Thanks
