### ISSUE TITLE
Suggestions: Creating common Props for android and ios

### ISSUE THREAD

**Issue by geekvijay** [mmazzarolo/react-native-modal-datetime-picker#8]
We have to use different Props name for Android and IOS. 

**Android:**
1) minDateAndroid
2) maxDateAndroid

**IOS:**
1) minimumDate
2) maximumDate

Can we create common property for this like we can use only minimumDate and maximumDate for both Android and IOS.

**Comment by mmazzarolo** [comment]
Hey @geekvijay, seems nice :)
Are you able to make a pull request on this matter? It shouldn't be too complex.  
Otherwise I can take a look at it in my free time.

**Comment by geekvijay** [comment]
Let me try and then i will send pull request.

**Comment by geekvijay** [comment]
@mmazzarolo i have created the pull request for this issue 😄

**Comment by mmazzarolo** [comment]
Yep, thanks you man!
