### ISSUE TITLE
While using your dummy code getting issue

### ISSUE THREAD

**Issue by sunnynegi** [mmazzarolo/react-native-modal-datetime-picker#85]
Hi there trying to implement datepicker but it's give error

export default addTodo;`
Failed prop type: The prop `onCancel` is marked as required in `CustomDatePickerAndroid`, but its value is `undefined`.

[https://gist.github.com/sunnynegi/63a9a228ac0ae209fd22752a8a1fddc0](url)

**Comment by sunnynegi** [comment]
Even the documentation is not good

**Comment by mmazzarolo** [comment]
Hello @sunnynegi, I'm sorry you're not able to make the component work.    
Please fill app the issue template so we'll be able to give you a faster feedback.  
  
### When reporting a bug, please be sure to check if the issue still persists with react-native original date/time pickers:
Under the hood `react-native-modal-datetime-picker` react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
Before reporting a bug, try swapping `react-native-datetime-picker` with react-native original date/time pickers to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [ ] The outcome of the `react-native-modal-datetime-picker` swap described above
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `react-native-modal-datetime-picker` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior


### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

### Please note by far the quickest way to get a new feature is to file a Pull Request.

**Comment by sunnynegi** [comment]
Well i am getting issue,
1.issue
 Failed prop type: The prop onCancel is marked as required in CustomDatePickerAndroid, but its value is undefined.

How can i pass props On cancel or onConfirm so plz kindly help me

**Comment by sunnynegi** [comment]
Well i am getting issue,
1.issue
Failed prop type: The prop onCancel is marked as required in CustomDatePickerAndroid, but its value is undefined.

How can i pass props On cancel or onConfirm so plz kindly help me

**Comment by mmazzarolo** [comment]
@sunnynegi please install and check [the example](https://github.com/mmazzarolo/react-native-modal-datetime-picker/tree/master/example) or at least paste here the code you're using.

**Comment by sunnynegi** [comment]
Check ths gist 
https://gist.github.com/sunnynegi/272b835d146a4303b56ac41429dce03f

**Comment by mmazzarolo** [comment]
In the gist you provided the `alert` variable you provided to the `onCancel` prop is not defined

**Comment by sunnynegi** [comment]
This is how i defined in constructor
this.onConfirm = ()=>{
        console.log('confirmed');
    }

    this.onCancel = ()=>{
        console.log('confirmed');
    }

**Comment by mmazzarolo** [comment]
The constructor is totally unrelated to the components you're rendering. 

Please change the DateTimePicker this way and let me know if it prints the log correctly. 
```javascript
<DateTimePicker
            isVisible={this.state.isDateTimePickerVisible}
            onConfirm={()=>{ console.log('Confirmed') }}
            onCancel={()=>{ console.log('Canceled) }}
          />
```

**Comment by sunnynegi** [comment]
Well i added, But nothing is happened

https://gist.github.com/sunnynegi/705261018d7640e965134d61e9a18dce

**Comment by sunnynegi** [comment]
Ok thanks @mmazzarolo , I will checked what's the issue, Will you please update you doc.
Like how datepicker is work with input box etc, so it's easy for everyone (newbie or expert).
Move to another Datepicker, Thanks for your response
