### ISSUE TITLE
[help] How can I set second ?

### ISSUE THREAD

**Issue by perfecten** [mmazzarolo/react-native-modal-datetime-picker#86]
I need HH:MM:SS。
does the component just set Hour and Minute ?
How can I set Second ?

thank you for your help

**Comment by mmazzarolo** [comment]
Hi @perfecten,
Under the hood `react-native-modal-datetime-picker` react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).  
Unfortunately these components don't support the `seconds`.
