### ISSUE TITLE
how to change the theme color for android picker ?  

### ISSUE THREAD

**Issue by SachinHiker** [mmazzarolo/react-native-modal-datetime-picker#88]
how to change the theme color for android picker ?  

<img width="368" alt="screen shot 2017-09-22 at 11 59 08 am" src="https://user-images.githubusercontent.com/29193170/30731877-8ee42a6a-9f8d-11e7-9dde-8de8f6c9cd47.png">

**Comment by mmazzarolo** [comment]
Hello @SachinHiker please check [this issue](https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/29).

**Comment by animeclover** [comment]
I try the below blog for adding datePickerAndroid and it's working fine also provide when a user has multiple input field for date solution.

https://infinitbility.com/how-to-add-datepickerandroid-in-react-native-with-color-changes
