### ISSUE TITLE
is24Hour doesnt work when the mode is time. time picker always opens in with 24 Hours enable no matter what the value of is24Hour is . 

### ISSUE THREAD

**Issue by abhi4973** [mmazzarolo/react-native-modal-datetime-picker#91]
### When reporting a bug, please be sure to check if the issue still persists with react-native original date/time pickers:
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    
Before reporting a bug, try swapping `react-native-datetime-picker` with react-native original date/time pickers to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [ ] The outcome of the `react-native-modal-datetime-picker` swap described above
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `react-native-modal-datetime-picker` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior

### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

**Comment by mmazzarolo** [comment]
Could you please take a look at the template (the one you posted above)?

**Comment by mmazzarolo** [comment]
Closing, feel free to open another issue (after taking a look at the template above) if needed!
