### ISSUE TITLE
Automatically disabled the before time from current time

### ISSUE THREAD

**Issue by harikanammi** [mmazzarolo/react-native-modal-datetime-picker#94]
I am using this module, it's all working fine. I am running a sample app. If i pick a time from the time picker automatically it disables the before time from the current time. 

Here is my code:
```

class ModalDatePicker extends Component {
  constructor(props){
      super(props);
      this.state={
         isTimePickerVisible: false,
         currentTime:moment().format('h:mm a').toUpperCase()
      }
    }
    _showTimePicker = () => this.setState({ isTimePickerVisible: true });

   _hideTimePicker = () => this.setState({ isTimePickerVisible: false });

   _handleTimePicked = (time) => {
     var time = moment(time).format("hh:mm a");
       this.setState({
         currentTime : time.toUpperCase()
       },()=>{
         if(this.state.currentTime < time){
          this.setState({
            currentTime : this.state.currentTime
          })
         }
       })
     this._hideTimePicker();
   };

render(){
      return(
  <View style = {styles.buttonView}>
        <TouchableOpacity onPress={this._showTimePicker}>
        <View style ={styles.pickUpBorderView}>
        <Text>Pickup Time {this.state.currentTime}</Text>
        <DateTimePicker
          isVisible={this.state.isTimePickerVisible}
          onConfirm={this._handleTimePicked}
          onCancel={this._hideTimePicker}
          mode = {'time'}
        />
        </View>
        </TouchableOpacity>
        </View>
)}
}
```
Here is my screenshot
![screen shot 2017-10-13 at 4 18 54 pm](https://user-images.githubusercontent.com/31063894/31543092-422ce7ce-b032-11e7-8b76-57c6402044a9.png)
Please give any suggestion for this issue. Thank you

**Comment by mmazzarolo** [comment]
Hey @harikanammi,
I'm sorry but I can't understand the issue 😞 
Could you please explain the following sentence a bit more? 

> it disables the before time from the current time

Thanks!

**Comment by harikanammi** [comment]
I want to disabled the completed time in the time picker

**Comment by harikanammi** [comment]
I want to disable the previous time in the time picker. It enables only future time in the time picker.

**Comment by mmazzarolo** [comment]
You should provide the `minimumDate` to the picker just like you would do with [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).

**Comment by harikanammi** [comment]
This is my code.```
<View style ={styles.pickUpBorderView}>
        <Text>Pickup Time {this.state.currentTime}</Text>
        <DateTimePicker
          isVisible={this.state.isTimePickerVisible}
          onConfirm={this._handleTimePicked}
          is24Hour = {true}
          onCancel={this._hideTimePicker}
          mode = {'time'}
        />
        </View>
```
 How can i give this `minimumDate` into my code.

**Comment by mmazzarolo** [comment]
```
<DateTimePicker
      isVisible={this.state.isTimePickerVisible}
      onConfirm={this._handleTimePicked}
      is24Hour = {true}
      minimumDate={your minumum date}
      onCancel={this._hideTimePicker}
      mode = {'time'}
    />
```

**Comment by harikanammi** [comment]
```
  <DateTimePicker
          isVisible={this.state.isTimePickerVisible}
          onConfirm={this._handleTimePicked}
          is24Hour = {true}
          onCancel={this._hideTimePicker}
          mode = {'time'}
          minimumDate = {this.state.currentTime}
        />
```
![screen shot 2017-10-13 at 7 08 58 pm](https://user-images.githubusercontent.com/31063894/31548876-036cd946-b04a-11e7-8938-a1992b314ffd.png)
I am getting this error.

**Comment by mmazzarolo** [comment]
```  
<DateTimePicker
          isVisible={this.state.isTimePickerVisible}
          onConfirm={this._handleTimePicked}
          is24Hour = {true}
          onCancel={this._hideTimePicker}
          mode = {'time'}
          minimumDate = {new Date()}
        />
```
Does this work? It should not allow you to select a date before the current moment

**Comment by harikanammi** [comment]
Thank You for your support, it's working

**Comment by mmazzarolo** [comment]
👍 have fun!

**Comment by bilalyaqoob** [comment]
I have an issue using this modal i just need date from 1 to 18 date it is showing correct result but after 18 date it start showing me day name and time.

**Comment by christopher-18** [comment]
@mmazzarolo  Any idea how can i enable selection of future time as well, if date selected is of past date?

**Comment by amancoder487** [comment]
How to give any start time in this code 

<DateTimePicker
          isVisible={this. state.isTimePickerVisible}
          onConfirm={this._handleTimePicked}
          is24Hour={true}
          onCancel={this._hideTimePicker}
          mode={'time'}
          minimum date = {new Date()}
        />

**Comment by amancoder487** [comment]
@mmazzarolo 

How to give any start time in this code

<DateTimePicker
isVisible={this. state.isTimePickerVisible}
onConfirm={this._handleTimePicked}
is24Hour={true}
onCancel={this._hideTimePicker}
mode={'time'}
minimum date = {new Date()}
/>

**Comment by krupavahora** [comment]
its not working in android

> minimumDate
