### ISSUE TITLE
onHideAfterCancel or just onHide

### ISSUE THREAD

**Issue by ofilipowicz** [mmazzarolo/react-native-modal-datetime-picker#95]
Is there any way to trigger function when modal closes after pressing Cancel? There is only onHideAfterConfirm callback. It would be nice if there would be onHideAfterCancel or just onHide (similar to react-native-modal's onModalHide)

**Comment by mmazzarolo** [comment]
Hey @ofilipowicz, Isn't `onCancel` enough for your use case? Am I missing something? 🤔

**Comment by ofilipowicz** [comment]
@mmazzarolo it triggers on button press, I need a hook on animation ends. I want to display another modal, but this one needs to be hidden first.

**Comment by mmazzarolo** [comment]
Oh I got it!
Well, you should be able to pass `onHide` function to `reactNativeModalPropsIOS`, which is an Object o props that will be passed to the modal.

**Comment by mmazzarolo** [comment]
My bad, I just noticed. 
`onHideAfterConfirm` seems to get triggered [even when pressing the cancel button](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/src/CustomDatePickerIOS/index.js#L129)

**Comment by mmazzarolo** [comment]
@ofilipowicz yeah sorry

yep, it is not doable (yet) for Android since the "modal" is controlled natively by Android
