### ISSUE TITLE
How to init date for datetime-picker

### ISSUE THREAD

**Issue by truongluong1314520** [mmazzarolo/react-native-modal-datetime-picker#99]
Hi Mmazzarolo,

I am stuck at init the date for datetime-picker. What I want is that when I open the calendar, instead of showing the current day, it will show the date which I setup before.

I search around and find this code:
`date={new Date()}`

However, if I put in the date I want like:
`date={new Date("1993,6,27")}`

The calendar still keep showing the current date instead of the date "27/06/1993". Following, when I select a date, press OK, the function "onConfirm" return "A date has been picked: , Invalid Date".

Please let me know if I miss anything to show the init date I want. Thank you in advance!

**Comment by mmazzarolo** [comment]
Hey @truongluong1314520 
Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html).    

Could you please check if your issue persists even when using [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html) alone?

**Comment by ZhouXiongXiong** [comment]
Hi Mmazzarolo,
Month how to display in Chinese?
 Thank you in advance!

**Comment by mmazzarolo** [comment]
Please @ZhouXiongXiong refer to the other issue you opened #101
